// Copyright Epic Games, Inc. All Rights Reserved.

import 'dart:async';

import '../../models/native/native_object.dart';
import '../../models/native/native_object_manager.dart';
import '../api/ar_api.g.dart';
import '../api/session_api.dart';

/// A session in the native AR framework.
class ArSession extends NativeObject {
  ArSession({ArSessionApi? api}) : this.api = api ?? ArSessionApi.instance;

  /// The API used to communicate with the host language.
  final ArSessionApi api;

  /// The current tracking state of the session's camera.
  ArTrackingState _state = ArTrackingState.unavailable;

  /// The current tracking state of the session's camera.
  ArTrackingState get state => _state;

  /// A stream that broadcasts whenever a frame is received.
  Stream<ArFrame> get frameEvent => _frameEvent.stream;

  /// A stream that broadcasts whenever the tracking state changes.
  Stream<ArTrackingState> get stateChangedEvent => _stateChangedEvent.stream;

  @override
  NativeObjectManager<NativeObject> get manager => api.manager;

  /// Stream controller for [frameEvent].
  final StreamController<ArFrame> _frameEvent = StreamController.broadcast();

  /// Stream controller for [stateChangedEvent].
  final StreamController<ArTrackingState> _stateChangedEvent = StreamController.broadcast();

  /// Run the AR session.
  void run() {
    api.host.run(id);
  }

  /// Pause the AR session.
  void pause() {
    api.host.pause(id);
  }

  /// Called when a new [frame] is generated by the native AR plugin.
  void onFrame(ArFrame frame) {
    _frameEvent.add(frame);
  }

  /// Called when the camera tracking for this AR session changes.
  void onTrackingStateChanged(ArTrackingState state) {
    _state = state;
    _stateChangedEvent.add(state);
  }

  @override
  Future<int> internalInit() => api.host.create();

  @override
  Future<void> internalDispose() => api.host.dispose(id);
}
