// Copyright Epic Games, Inc. All Rights Reserved.
// 
// This is an auto-generated file. See FlutterLiveLinkVCAM/pigeons/README for information on how to
// modify the original source and generate a new file.
// 
// Autogenerated from Pigeon (v14.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// Supported types for [RtcSessionDescription].
enum RtcSessionDescriptionType {
  answer,
  offer,
  pranswer,
  rollback,
}

/// State of an [RtcPeerConnection]'s connection to the corresponding peer.
enum RtcPeerConnectionState {
  newConnection,
  connecting,
  connected,
  disconnected,
  failed,
  closed,
}

/// Kinds of MediaStreamTrack that can be created.
enum RtcMediaStreamTrackKind {
  audio,
  video,
}

/// State of an [RtcDataChannel].
enum RtcDataChannelState {
  connecting,
  open,
  closing,
  closed,
}

/// A buffer passed from/to WebRTC, which may contain either binary or text data.
class RtcDataBuffer {
  RtcDataBuffer({
    required this.data,
    required this.bIsBinary,
  });

  /// The binary data contained in the buffer.
  Uint8List data;

  /// True if the buffer contains binary data; otherwise, it contains UTF-8 text.
  bool bIsBinary;

  Object encode() {
    return <Object?>[
      data,
      bIsBinary,
    ];
  }

  static RtcDataBuffer decode(Object result) {
    result as List<Object?>;
    return RtcDataBuffer(
      data: result[0]! as Uint8List,
      bIsBinary: result[1]! as bool,
    );
  }
}

/// Describes the configuration of one end of a peer-to-peer WebRtc connection.
class RtcSessionDescription {
  RtcSessionDescription({
    required this.type,
    required this.sdp,
  });

  /// The type of description.
  RtcSessionDescriptionType type;

  /// The SDP information describing the session.
  String sdp;

  Object encode() {
    return <Object?>[
      type.index,
      sdp,
    ];
  }

  static RtcSessionDescription decode(Object result) {
    result as List<Object?>;
    return RtcSessionDescription(
      type: RtcSessionDescriptionType.values[result[0]! as int],
      sdp: result[1]! as String,
    );
  }
}

/// A candidate for interactive connectivity establishment (ICE) to a peer.
class RtcIceCandidate {
  RtcIceCandidate({
    required this.candidate,
    required this.sdpMid,
    required this.sdpMLineIndex,
  });

  /// A string describing the candidate (taken from the SDP "candidate" field).
  String candidate;

  /// A string specifying the candidate's unique media stream ID tag.
  String sdpMid;

  /// The index number of the media description within the SDP.
  int sdpMLineIndex;

  Object encode() {
    return <Object?>[
      candidate,
      sdpMid,
      sdpMLineIndex,
    ];
  }

  static RtcIceCandidate decode(Object result) {
    result as List<Object?>;
    return RtcIceCandidate(
      candidate: result[0]! as String,
      sdpMid: result[1]! as String,
      sdpMLineIndex: result[2]! as int,
    );
  }
}

/// Event data for when a track is added to a stream in a [RtcPeerConnection].
class RtcTrackEvent {
  RtcTrackEvent({
    required this.trackId,
    required this.kind,
  });

  /// The unique ID of the media track used to refer to it when communicating with the native plugin.
  int trackId;

  /// The kind of media in this track.
  RtcMediaStreamTrackKind kind;

  Object encode() {
    return <Object?>[
      trackId,
      kind.index,
    ];
  }

  static RtcTrackEvent decode(Object result) {
    result as List<Object?>;
    return RtcTrackEvent(
      trackId: result[0]! as int,
      kind: RtcMediaStreamTrackKind.values[result[1]! as int],
    );
  }
}

/// Reported statistics about a single object inspected as part of a WebRTC report.
class RtcStats {
  RtcStats({
    required this.timestampUs,
    required this.type,
    required this.id,
    required this.values,
  });

  /// Timestamp at which the stats were gathered (in microseconds).
  double timestampUs;

  /// The type of object for which these stats were collected.
  String type;

  /// The unique ID of the stats object.
  String id;

  /// Map from stat name to its value.
  Map<String?, Object?> values;

  Object encode() {
    return <Object?>[
      timestampUs,
      type,
      id,
      values,
    ];
  }

  static RtcStats decode(Object result) {
    result as List<Object?>;
    return RtcStats(
      timestampUs: result[0]! as double,
      type: result[1]! as String,
      id: result[2]! as String,
      values: (result[3] as Map<Object?, Object?>?)!.cast<String?, Object?>(),
    );
  }
}

/// A collection of reported statistics gathered about a WebRTC peer connection.
class RtcStatsReport {
  RtcStatsReport({
    required this.timestampUs,
    required this.stats,
  });

  /// Timestamp at which the stats were gathered (in microseconds).
  double timestampUs;

  /// Map from object name to the stats associated with it.
  Map<String?, RtcStats?> stats;

  Object encode() {
    return <Object?>[
      timestampUs,
      stats,
    ];
  }

  static RtcStatsReport decode(Object result) {
    result as List<Object?>;
    return RtcStatsReport(
      timestampUs: result[0]! as double,
      stats: (result[1] as Map<Object?, Object?>?)!.cast<String?, RtcStats?>(),
    );
  }
}

class _RtcPeerConnectionHostApiCodec extends StandardMessageCodec {
  const _RtcPeerConnectionHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is RtcIceCandidate) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is RtcSessionDescription) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is RtcStats) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is RtcStatsReport) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return RtcIceCandidate.decode(readValue(buffer)!);
      case 129: 
        return RtcSessionDescription.decode(readValue(buffer)!);
      case 130: 
        return RtcStats.decode(readValue(buffer)!);
      case 131: 
        return RtcStatsReport.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// API that receives messages about RtcPeerConnection instances in the host language.
class RtcPeerConnectionHostApi {
  /// Constructor for [RtcPeerConnectionHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  RtcPeerConnectionHostApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _RtcPeerConnectionHostApiCodec();

  /// Set the field trial keys and values enabled for future PeerConnections.
  Future<void> setFieldTrials(Map<String?, String?>? fieldTrials) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionHostApi.setFieldTrials';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[fieldTrials]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Create a PeerConnection.
  /// Returns an ID which can be used to refer to the native object in future calls.
  Future<int> create() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionHostApi.create';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as int?)!;
    }
  }

  /// Dispose of the PeerConnection with the given [connectionId].
  Future<void> dispose(int connectionId) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionHostApi.dispose';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[connectionId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Set the [description] of the remote peer for the PeerConnection with the given [connectionId].
  Future<void> setRemoteDescription(int connectionId, RtcSessionDescription description) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionHostApi.setRemoteDescription';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[connectionId, description]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Set the [description] of the local peer for the PeerConnection with the given [connectionId].
  Future<void> setLocalDescription(int connectionId, RtcSessionDescription description) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionHostApi.setLocalDescription';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[connectionId, description]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Add an ICE [candidate] for connecting to the remote peer.
  Future<void> addRemoteCandidate(int connectionId, RtcIceCandidate candidate) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionHostApi.addRemoteCandidate';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[connectionId, candidate]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Create an answer to a WebRTC offer for the PeerConnection with the given [connectionId].
  Future<RtcSessionDescription> createAnswer(int connectionId) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionHostApi.createAnswer';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[connectionId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as RtcSessionDescription?)!;
    }
  }

  /// Generate a stats report about the PeerConnection with the given [connectionId].
  /// If [typeFilter] is provided, the report will only contain stats matching types in that list, reducing the codec
  /// overhead from the native platform.
  Future<RtcStatsReport> getStats(int connectionId, List<String?>? typeFilter) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionHostApi.getStats';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[connectionId, typeFilter]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as RtcStatsReport?)!;
    }
  }
}

class _RtcPeerConnectionFlutterApiCodec extends StandardMessageCodec {
  const _RtcPeerConnectionFlutterApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is RtcIceCandidate) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is RtcTrackEvent) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return RtcIceCandidate.decode(readValue(buffer)!);
      case 129: 
        return RtcTrackEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// API that receives messages about RtcPeerConnection instances in Flutter.
abstract class RtcPeerConnectionFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _RtcPeerConnectionFlutterApiCodec();

  /// Called when a new local ICE [candidate] is found for the PeerConnection with the given [connectionId].
  void onIceCandidate(int connectionId, RtcIceCandidate? candidate);

  /// Called when the [state] of the PeerConnection with the given [connectionId] changes.
  void onStateChanged(int connectionId, RtcPeerConnectionState state);

  /// Called when a MediaStreamTrack (described in [event]) is added to the PeerConnection with the given
  /// [connectionId].
  void onTrack(int connectionId, RtcTrackEvent event);

  /// Called when a DataChannel with the given [dataChannelId] is added to the PeerConnection with the given
  /// [connectionId].
  void onDataChannel(int connectionId, int dataChannelId);

  static void setup(RtcPeerConnectionFlutterApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionFlutterApi.onIceCandidate', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionFlutterApi.onIceCandidate was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_connectionId = (args[0] as int?);
          assert(arg_connectionId != null,
              'Argument for dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionFlutterApi.onIceCandidate was null, expected non-null int.');
          final RtcIceCandidate? arg_candidate = (args[1] as RtcIceCandidate?);
          try {
            api.onIceCandidate(arg_connectionId!, arg_candidate);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionFlutterApi.onStateChanged', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionFlutterApi.onStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_connectionId = (args[0] as int?);
          assert(arg_connectionId != null,
              'Argument for dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionFlutterApi.onStateChanged was null, expected non-null int.');
          final RtcPeerConnectionState? arg_state = args[1] == null ? null : RtcPeerConnectionState.values[args[1]! as int];
          assert(arg_state != null,
              'Argument for dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionFlutterApi.onStateChanged was null, expected non-null RtcPeerConnectionState.');
          try {
            api.onStateChanged(arg_connectionId!, arg_state!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionFlutterApi.onTrack', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionFlutterApi.onTrack was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_connectionId = (args[0] as int?);
          assert(arg_connectionId != null,
              'Argument for dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionFlutterApi.onTrack was null, expected non-null int.');
          final RtcTrackEvent? arg_event = (args[1] as RtcTrackEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionFlutterApi.onTrack was null, expected non-null RtcTrackEvent.');
          try {
            api.onTrack(arg_connectionId!, arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionFlutterApi.onDataChannel', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionFlutterApi.onDataChannel was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_connectionId = (args[0] as int?);
          assert(arg_connectionId != null,
              'Argument for dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionFlutterApi.onDataChannel was null, expected non-null int.');
          final int? arg_dataChannelId = (args[1] as int?);
          assert(arg_dataChannelId != null,
              'Argument for dev.flutter.pigeon.live_link_vcam.RtcPeerConnectionFlutterApi.onDataChannel was null, expected non-null int.');
          try {
            api.onDataChannel(arg_connectionId!, arg_dataChannelId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

class _RtcDataChannelHostApiCodec extends StandardMessageCodec {
  const _RtcDataChannelHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is RtcDataBuffer) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return RtcDataBuffer.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// API that receives messages about RtcDataChannel instances in the host language.
class RtcDataChannelHostApi {
  /// Constructor for [RtcDataChannelHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  RtcDataChannelHostApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _RtcDataChannelHostApiCodec();

  /// Send a message contained in [buffer] on the data channel with the given [dataChannelId].
  Future<void> sendMessage(int dataChannelId, RtcDataBuffer buffer) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.live_link_vcam.RtcDataChannelHostApi.sendMessage';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[dataChannelId, buffer]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }
}

class _RtcDataChannelFlutterApiCodec extends StandardMessageCodec {
  const _RtcDataChannelFlutterApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is RtcDataBuffer) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return RtcDataBuffer.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// API that receives messages about RtcDataChannel instances in Flutter.
abstract class RtcDataChannelFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _RtcDataChannelFlutterApiCodec();

  /// Called when the [state] of the DataChannel with the given [dataChannelId] changes.
  void onStateChanged(int dataChannelId, RtcDataChannelState state);

  /// Called when a message contained in [buffer] is received on the data channel with the given [dataChannelId].
  void onMessage(int dataChannelId, RtcDataBuffer buffer);

  static void setup(RtcDataChannelFlutterApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.live_link_vcam.RtcDataChannelFlutterApi.onStateChanged', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.live_link_vcam.RtcDataChannelFlutterApi.onStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_dataChannelId = (args[0] as int?);
          assert(arg_dataChannelId != null,
              'Argument for dev.flutter.pigeon.live_link_vcam.RtcDataChannelFlutterApi.onStateChanged was null, expected non-null int.');
          final RtcDataChannelState? arg_state = args[1] == null ? null : RtcDataChannelState.values[args[1]! as int];
          assert(arg_state != null,
              'Argument for dev.flutter.pigeon.live_link_vcam.RtcDataChannelFlutterApi.onStateChanged was null, expected non-null RtcDataChannelState.');
          try {
            api.onStateChanged(arg_dataChannelId!, arg_state!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.live_link_vcam.RtcDataChannelFlutterApi.onMessage', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.live_link_vcam.RtcDataChannelFlutterApi.onMessage was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_dataChannelId = (args[0] as int?);
          assert(arg_dataChannelId != null,
              'Argument for dev.flutter.pigeon.live_link_vcam.RtcDataChannelFlutterApi.onMessage was null, expected non-null int.');
          final RtcDataBuffer? arg_buffer = (args[1] as RtcDataBuffer?);
          assert(arg_buffer != null,
              'Argument for dev.flutter.pigeon.live_link_vcam.RtcDataChannelFlutterApi.onMessage was null, expected non-null RtcDataBuffer.');
          try {
            api.onMessage(arg_dataChannelId!, arg_buffer!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

/// API that receives messages about VideoViewController instances in the host language.
class RtcVideoViewControllerHostApi {
  /// Constructor for [RtcVideoViewControllerHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  RtcVideoViewControllerHostApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = StandardMessageCodec();

  /// Create a VideoViewController.
  /// Returns an ID which can be used to refer to the native object in future calls.
  Future<int> create() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.live_link_vcam.RtcVideoViewControllerHostApi.create';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as int?)!;
    }
  }

  /// Set the video track of the VideoViewController with the given [controllerId] to the track with the given
  /// [trackId].
  Future<void> setTrack(int controllerId, int trackId) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.live_link_vcam.RtcVideoViewControllerHostApi.setTrack';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[controllerId, trackId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Get the texture ID associated with the VideoViewController with the given [controllerId].
  Future<int> getTextureId(int controllerId) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.live_link_vcam.RtcVideoViewControllerHostApi.getTextureId';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[controllerId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as int?)!;
    }
  }

  /// Clear the image of the VideoViewController with the given [controllerId].
  Future<void> clear(int controllerId) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.live_link_vcam.RtcVideoViewControllerHostApi.clear';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[controllerId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Dispose of the VideoViewController with the given [controllerId].
  Future<void> dispose(int controllerId) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.live_link_vcam.RtcVideoViewControllerHostApi.dispose';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[controllerId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }
}

/// API that receives messages about VideoViewController instances in Flutter.
abstract class RtcVideoViewControllerFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = StandardMessageCodec();

  /// Called when the VideoViewController with the given [controllerId] has rendered its first frame since it was
  /// created or cleared (whichever is latest).
  void onFirstFrameRendered(int controllerId);

  /// Called when the size of a VideoViewController's frame size changes.
  void onFrameSizeChanged(int controllerId, int width, int height);

  static void setup(RtcVideoViewControllerFlutterApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.live_link_vcam.RtcVideoViewControllerFlutterApi.onFirstFrameRendered', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.live_link_vcam.RtcVideoViewControllerFlutterApi.onFirstFrameRendered was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_controllerId = (args[0] as int?);
          assert(arg_controllerId != null,
              'Argument for dev.flutter.pigeon.live_link_vcam.RtcVideoViewControllerFlutterApi.onFirstFrameRendered was null, expected non-null int.');
          try {
            api.onFirstFrameRendered(arg_controllerId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.live_link_vcam.RtcVideoViewControllerFlutterApi.onFrameSizeChanged', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.live_link_vcam.RtcVideoViewControllerFlutterApi.onFrameSizeChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_controllerId = (args[0] as int?);
          assert(arg_controllerId != null,
              'Argument for dev.flutter.pigeon.live_link_vcam.RtcVideoViewControllerFlutterApi.onFrameSizeChanged was null, expected non-null int.');
          final int? arg_width = (args[1] as int?);
          assert(arg_width != null,
              'Argument for dev.flutter.pigeon.live_link_vcam.RtcVideoViewControllerFlutterApi.onFrameSizeChanged was null, expected non-null int.');
          final int? arg_height = (args[2] as int?);
          assert(arg_height != null,
              'Argument for dev.flutter.pigeon.live_link_vcam.RtcVideoViewControllerFlutterApi.onFrameSizeChanged was null, expected non-null int.');
          try {
            api.onFrameSizeChanged(arg_controllerId!, arg_width!, arg_height!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
