// Copyright Epic Games, Inc. All Rights Reserved.
//
// This is an auto-generated file. See FlutterLiveLinkVCAM/pigeons/README for information on how to
// modify the original source and generate a new file.
//
// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// Types of Tentacle products.
enum TentacleProductId {
  generic,
  syncE,
  trackE,
  timebar,
}

/// Information about a Tentacle device. This only includes data which is expected to be requested infrequently, so it
/// excludes the time code, last seen time, etc.
class TentacleDeviceInfo {
  TentacleDeviceInfo({
    required this.bIsInGreenMode,
    required this.bIsCharging,
    required this.bIsDropFrame,
    required this.batteryLevel,
    required this.frameRate,
    required this.lastSeenTimestamp,
    required this.iconIndex,
    required this.signalStrength,
    required this.productId,
    required this.identifier,
    required this.name,
  });

  /// True if the device is generating timecodes.
  bool bIsInGreenMode;

  /// Whether the battery is charging.
  bool bIsCharging;

  /// Whether the device is generating drop-frame timecodes.
  bool bIsDropFrame;

  /// Current battery level in percent.
  int batteryLevel;

  /// Frame rate of the timecodes generated by this device in frames per second.
  double frameRate;

  /// Device timestamp (seconds since boot) when the device was last detected.
  double lastSeenTimestamp;

  /// Index of the icon used to represent this device.
  int iconIndex;

  /// Received signal strength in decibel-milliwatts.
  int signalStrength;

  /// The type of Tentacle product.
  TentacleProductId productId;

  /// Unique identifier string for the device.
  String identifier;

  /// User-assigned name for the device.
  String name;

  Object encode() {
    return <Object?>[
      bIsInGreenMode,
      bIsCharging,
      bIsDropFrame,
      batteryLevel,
      frameRate,
      lastSeenTimestamp,
      iconIndex,
      signalStrength,
      productId,
      identifier,
      name,
    ];
  }

  static TentacleDeviceInfo decode(Object result) {
    result as List<Object?>;
    return TentacleDeviceInfo(
      bIsInGreenMode: result[0]! as bool,
      bIsCharging: result[1]! as bool,
      bIsDropFrame: result[2]! as bool,
      batteryLevel: result[3]! as int,
      frameRate: result[4]! as double,
      lastSeenTimestamp: result[5]! as double,
      iconIndex: result[6]! as int,
      signalStrength: result[7]! as int,
      productId: result[8]! as TentacleProductId,
      identifier: result[9]! as String,
      name: result[10]! as String,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is TentacleProductId) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is TentacleDeviceInfo) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : TentacleProductId.values[value];
      case 130: 
        return TentacleDeviceInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// API that receives messages about Tentacle devices in the host language.
class TentacleHostApi {
  /// Constructor for [TentacleHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TentacleHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Start scanning for Tentacle devices using BLE.
  /// Bluetooth permission must be acquired before calling this.
  Future<void> startScanning() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_tentacle.TentacleHostApi.startScanning$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Stop scanning for Tentacle devices using BLE.
  Future<void> stopScanning() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_tentacle.TentacleHostApi.stopScanning$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Get the latest list of cached device information.
  Future<List<TentacleDeviceInfo>> getCachedDeviceInfo() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_tentacle.TentacleHostApi.getCachedDeviceInfo$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<TentacleDeviceInfo>();
    }
  }
}

/// API that receives messages about Tentacle devices in Flutter.
abstract class TentacleFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  static void setUp(TentacleFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  }
}
