// Copyright Epic Games, Inc. All Rights Reserved.
//
// This is an auto-generated file. Do not edit.
// See FlutterLiveLinkVCAM/README for information on how to regenerate this.
//
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// FFI bindings for the Tentacle SDK.
class TentacleLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  TentacleLibrary(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  TentacleLibrary.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// @brief
  /// Total number of seconds described by this timecode at specific timestamp.
  ///
  /// @param timecode Get total number of seconds for this timecode.
  /// @param frameRate Frame rate used to calculate number of seconds.
  /// @param dropFrame True if timecode is using drop frames.
  /// @param atTimestamp Total number of seconds of timecode at this timestamp.
  /// @return Total number of seconds.
  double TentacleTimecodeSecondsAtTimestamp(
    ffi.Pointer<TentacleTimecode> timecode,
    double frameRate,
    bool dropFrame,
    double atTimestamp,
  ) {
    return _TentacleTimecodeSecondsAtTimestamp(
      timecode,
      frameRate,
      dropFrame,
      atTimestamp,
    );
  }

  late final _TentacleTimecodeSecondsAtTimestampPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Pointer<TentacleTimecode>, ffi.Double,
              ffi.Bool, ffi.Double)>>('TentacleTimecodeSecondsAtTimestamp');
  late final _TentacleTimecodeSecondsAtTimestamp =
      _TentacleTimecodeSecondsAtTimestampPtr.asFunction<
          double Function(
              ffi.Pointer<TentacleTimecode>, double, bool, double)>();

  /// @brief
  /// Frame rate, depending on value of NTSC flag. Also see
  /// `TentacleAdvertisement.frameRateInt` for frame rate ignoring the NTSC flag.
  ///
  /// @param advertisement Advertisement to get the frame rate of.
  /// @return Frame rate depending on NTSC flag.
  double TentacleAdvertisementGetFrameRate(
    ffi.Pointer<TentacleAdvertisement> advertisement,
  ) {
    return _TentacleAdvertisementGetFrameRate(
      advertisement,
    );
  }

  late final _TentacleAdvertisementGetFrameRatePtr = _lookup<
          ffi.NativeFunction<
              ffi.Double Function(ffi.Pointer<TentacleAdvertisement>)>>(
      'TentacleAdvertisementGetFrameRate');
  late final _TentacleAdvertisementGetFrameRate =
      _TentacleAdvertisementGetFrameRatePtr.asFunction<
          double Function(ffi.Pointer<TentacleAdvertisement>)>();

  /// @brief
  /// Get cached device at specific index.
  ///
  /// @param deviceIndex Index of device to get.
  /// @return Device struct at passed index.
  TentacleDevice TentacleDeviceCacheGetDevice(
    int deviceIndex,
  ) {
    return _TentacleDeviceCacheGetDevice(
      deviceIndex,
    );
  }

  late final _TentacleDeviceCacheGetDevicePtr =
      _lookup<ffi.NativeFunction<TentacleDevice Function(ffi.Int)>>(
          'TentacleDeviceCacheGetDevice');
  late final _TentacleDeviceCacheGetDevice = _TentacleDeviceCacheGetDevicePtr
      .asFunction<TentacleDevice Function(int)>();
}

/// @brief
/// Timecode data received from a Bluetooth advertisement packet.
///
/// Also see `TentacleTimecode.c`
@ffi.Packed(1)
final class TentacleTimecode extends ffi.Struct {
  /// Hour of timecode.
  @ffi.Uint8()
  external int hour;

  /// Minute of timecode.
  @ffi.Uint8()
  external int minute;

  /// Second of timecode.
  @ffi.Uint8()
  external int second;

  /// Frame of timecode.
  @ffi.Uint8()
  external int frame;

  /// Microseconds.
  @ffi.Uint32()
  external int microsecond;

  /// @brief Timestamp of when this timecode has been received, in seconds.
  ///
  /// On Apple Darwin, [machAbsoluteTime](https://github.com/apple/darwin-xnu/blob/0a798f6738bc1db01281fc08ae024145e84df927/osfmk/arm/rtclock.c#L162) is used.
  ///
  /// On Android, [ScanResult.getTimestampNanos()](https://developer.android.com/reference/android/bluetooth/le/ScanResult.html#getTimestampNanos()) is used.
  ///
  /// Caution: Timestamps are based on the boot time of the device and invalidated on device reboot.
  @ffi.Double()
  external double receivedTimestamp;
}

/// @brief
/// Contains data of a received Bluetooth advertisement packet.
///
/// Also see `TentacleAdvertisement.c`
@ffi.Packed(1)
final class TentacleAdvertisement extends ffi.Struct {
  /// Source of advertisement
  @ffi.Int32()
  external int source;

  /// Length of identifier string, has to be less than `TENTACLE_ADVERTISEMENT_IDENTIFIER_LENGTH_MAX`.
  @ffi.Size()
  external int identifierLength;

  /// @brief
  /// Unique identifier string representing the device this advertisement was sent from.
  ///
  /// On iOS, this is the string value of a [CBUUID](https://developer.apple.com/documentation/corebluetooth/cbuuid) object.
  ///
  /// On Android, this is the hardware address as returned by [BluetoothDevice.getAddress()](https://developer.android.com/reference/android/bluetooth/BluetoothDevice.html#getAddress()),
  @ffi.Array.multi([37])
  external ffi.Array<ffi.Char> identifier;

  /// Length of name string, has to be less or equal to `TENTACLE_ADVERTISEMENT_NAME_LENGTH_MAX`.
  @ffi.Size()
  external int nameLength;

  /// Name of the device this advertisement was sent from.
  @ffi.Array.multi([17])
  external ffi.Array<ffi.Char> name;

  /// Received signal strength indication
  @ffi.Int8()
  external int rssi;

  /// Tentacle Bluetooth protocol version. Currently supported are 1 and 2.
  @ffi.Uint8()
  external int version;

  /// Icon index the device is set to.
  @ffi.Uint8()
  external int icon;

  /// Battery level of device, in percent.
  @ffi.Uint8()
  external int battery;

  /// True if device is currently charging.
  @ffi.Bool()
  external bool charging;

  /// Hardware device type.
  @ffi.Int32()
  external int productId;

  /// State the device is in, Sync E.
  @ffi.Int32()
  external int deviceStateSyncE;

  /// Audio volume when generating audio timecode, timecode output level.
  @ffi.Int32()
  external int audioLevel;

  /// @brief
  /// For internal use only, can be ignored by third party apps.
  ///
  /// True if device is old Sync E mk1 hardware but using new version 2 advertisement format.
  @ffi.Bool()
  external bool legacySyncEHardware;

  /// State the device is in, Track E.
  @ffi.Int32()
  external int deviceStateTrackE;

  /// Remaining recording time on SD card
  @ffi.Uint8()
  external int remainingRecordTime;

  /// Low cut state on/off
  @ffi.Bool()
  external bool lowCutEnabled;

  /// Limiter state on/off
  @ffi.Bool()
  external bool limiterEnabled;

  /// Level Meter float mode on/off
  @ffi.Bool()
  external bool floatAudio;

  /// Limiter engaged
  @ffi.Bool()
  external bool limiterEngaged;

  /// Analog audio input clipped
  @ffi.Bool()
  external bool clipped;

  /// Peak level of audio input during recording.
  @ffi.Int8()
  external int audioInputPeakLevel;

  /// Take number of audio recording, current recording/playback file index.
  @ffi.Uint16()
  external int audioMediaIndex;

  /// Elapsed recording or playback time,  in seconds.
  @ffi.Uint32()
  external int audioRecordingTime;

  /// Mode the timebar is in, controls what is shown on the OLED display.
  @ffi.Int32()
  external int timebarMode;

  /// Service data packet type, only used by protocol version 2
  @ffi.Int32()
  external int packetType;

  /// True if device is connectable via Bluetooth.
  @ffi.Bool()
  external bool connectable;

  /// True if a mobile device can authenticate to the device.
  @ffi.Bool()
  external bool linkMode;

  /// True if device can act as sync primary (previously called "sync master")
  @ffi.Bool()
  external bool syncPrimaryCapable;

  /// @brief
  /// True if device is in green (synced) mode.
  ///
  /// Green mode means that the timecode has been configured, the device is
  /// generating audio timecode and other devices can be synced to this device
  /// using a cable.
  @ffi.Bool()
  external bool greenMode;

  /// Wireless sync status.
  @ffi.Int32()
  external int wirelessSyncStatus;

  /// @brief
  /// Wireless sync update flag
  ///
  /// Toggles between 1 and 0 after every start of wireless synchronization.
  @ffi.Bool()
  external bool wirelessSyncUpdateFlag;

  /// @brief
  /// Current frame rate as integer value, ignoring NTSC flag.
  ///
  /// To calculate the actual frame rate, you have to take the NTSC flag into
  /// account or use `TentacleAdvertisementGetFrameRate()`.
  @ffi.Int()
  external int frameRateInt;

  /// True if device is generating NTSC timecode.
  @ffi.Bool()
  external bool ntsc;

  /// True if device is generating drop frame timecode.
  @ffi.Bool()
  external bool dropFrame;

  /// Hour, minute, second, frame, microseconds and reception timestamp
  external TentacleTimecode timecode;

  /// User bits information as defined in SMPTE-12M.
  external TentacleAdvertisementUserBits userBits;

  /// @brief
  /// True if data in this struct is considered to describe a valid advertisement packet.
  ///
  /// Value is set by `TentacleAdvertisementInitExtended()`.
  @ffi.Bool()
  external bool valid;
}

/// @brief
/// Advertisement source
abstract class TentacleAdvertisementSource {
  /// Advertisements received via Bluetooth
  static const int TentacleAdvertisementSourceBluetooth = 0;

  /// Advertisements received via MIDI
  static const int TentacleAdvertisementSourceMIDI = 1;
}

/// @brief
/// Hardware device type.
abstract class TentacleProductId {
  /// Generic
  static const int TentacleProductIdGeneric = 0;

  /// Sync E
  static const int TentacleProductIdSyncE = 1;

  /// Track E
  static const int TentacleProductIdTrackE = 2;

  /// Timebar
  static const int TentacleProductIdTimebar = 3;
}

/// @brief
/// State the Sync E device is in.
abstract class TentacleDeviceStateSyncE {
  /// Device is powered off.
  static const int TentacleDeviceStateSyncEPowerOff = 0;

  /// Device is booting.
  static const int TentacleDeviceStateSyncEStartup = 1;

  /// Device is connected to USB.
  static const int TentacleDeviceStateSyncEStandby = 2;

  /// No cable is plugged into the device, no audio timecode is generated.
  static const int TentacleDeviceStateSyncEUnplugged = 3;

  /// Cable is plugged in and device is generating timecode.
  static const int TentacleDeviceStateSyncEGeneratingTimecode = 4;

  /// Device is reading timecode.
  static const int TentacleDeviceStateSyncEReadingTimecode = 5;

  /// Device is stopped.
  static const int TentacleDeviceStateSyncEStopped = 6;

  /// Device is detecting frame rate.
  static const int TentacleDeviceStateSyncEFpsDetect = 8;

  /// Device is syncing.
  static const int TentacleDeviceStateSyncEWirelessSync = 9;

  /// Device is in sleep mode.
  static const int TentacleDeviceStateSyncESleep = 14;

  /// Device is in link mode.
  static const int TentacleDeviceStateSyncELinkMode = 15;
}

/// @brief
/// Audio output volume level.
///
/// When producing timecode to be recorded on an audio track, the timecode is
/// encoded as an audio signal using a certain volume. This volume can be
/// low (Mic), high (Line), something in between (Custom) or be automatically
/// detected (AutoMic).
abstract class TentacleAudioLevel {
  /// Audio timecode is produced at a low volume
  static const int TentacleAudioLevelMic = 0;

  /// Audio timecode is produced at a high volume
  static const int TentacleAudioLevelLine = 1;

  /// Audio timecode is produced at a medium volume
  static const int TentacleAudioLevelCustom = 2;

  /// Audio timecode is automatically set to a low volume
  static const int TentacleAudioLevelAutoMic = 3;
}

/// @brief
/// State the Track E device is in.
abstract class TentacleDeviceStateTrackE {
  /// Device is powered off.
  static const int TentacleDeviceStateTrackEPowerOff = 0;

  /// Device is starting.
  static const int TentacleDeviceStateTrackEStartup = 1;

  /// Device is in connected to USB.
  static const int TentacleDeviceStateTrackEStandby = 2;

  /// Device is ready.
  static const int TentacleDeviceStateTrackEReady = 3;

  /// Device is recording.
  static const int TentacleDeviceStateTrackERecording = 4;

  /// Device is playing audio.
  static const int TentacleDeviceStateTrackEPlayback = 5;

  /// Device is reading timecode.
  static const int TentacleDeviceStateTrackEReadTc = 6;

  /// Device is syncing.
  static const int TentacleDeviceStateTrackEWirelessSync = 7;

  /// Device is checking SD card.
  static const int TentacleDeviceStateTrackESdCardCheck = 8;

  /// Device is formatting SD card.
  static const int TentacleDeviceStateTrackESdCardFormatting = 9;

  /// Device is testing SD card speed.
  static const int TentacleDeviceStateTrackESdCardSpeedTest = 10;

  /// Device is card reader mode.
  static const int TentacleDeviceStateTrackESdCardReaderMode = 11;

  /// SD Card of device is full.
  static const int TentacleDeviceStateTrackESdCardFull = 12;

  /// Device is coping files via BLE.
  static const int TentacleDeviceStateTrackEBleFileTransfer = 13;

  /// Device is in USB audio interface mode.
  static const int TentacleDeviceStateTrackEUsbAudioInterface = 14;

  /// Device is in link mode.
  static const int TentacleDeviceStateTrackELinkMode = 15;

  /// Device is in sleep mode.
  static const int TentacleDeviceStateTrackESleep = 16;

  /// SD card is missing.
  static const int TentacleDeviceStateTrackENoSd = 128;

  /// SD card is in wrong format.
  static const int TentacleDeviceStateTrackESdWrongFormat = 129;

  /// SD card reading or writing failed.
  static const int TentacleDeviceStateTrackESdReadWriteError = 130;

  /// SD card is incompatible.
  static const int TentacleDeviceStateTrackESdIncompatibleError = 131;

  /// SD card index error.
  static const int TentacleDeviceStateTrackESdIndexError = 132;

  /// SD card unknown error.
  static const int TentacleDeviceStateTrackESdUnknownError = 133;

  /// SD card not ready.
  static const int TentacleDeviceStateTrackESdCardNotReadyError = 134;

  /// Codec communication error.
  static const int TentacleDeviceStateTrackECodecCommunicationError = 144;

  /// Recording error.
  static const int TentacleDeviceStateTrackERecordingError = 145;
}

/// @brief
/// Mode the timebar is in, controls what is shown on the OLED display.
abstract class TentacleTimebarMode {
  /// Current timecode is displayed
  static const int TentacleTimebarModeTimecode = 0;

  /// Countdown timer is displayed
  static const int TentacleTimebarModeTimer = 1;

  /// Elapsed time of stopwatch is displayed
  static const int TentacleTimebarModeStopwatch = 2;

  /// Custom message/text is displayed
  static const int TentacleTimebarModeMessage = 3;

  /// Timecode and additional information is displayed when slate is closed
  static const int TentacleTimebarModeSlate = 4;

  /// Mode while slate is calibrating, triggered by user
  static const int TentacleTimebarModeSlateCalibration = 251;

  /// Internal mode, can not be configured by the user
  static const int TentacleTimebarModeRaw = 252;

  /// Internal mode, can not be configured by the user
  static const int TentacleTimebarModeBrightness = 253;

  /// Internal mode, can not be configured by the user
  static const int TentacleTimebarModeMenu = 254;
}

/// @brief
/// Advertisement version 2 packet type.
abstract class TentaclePacketType {
  /// Packet contains status information only
  static const int TentaclePacketTypeStatusOnly = 0;

  /// Simple timestamp format, hh:mm:ss:ff (length 9 bytes)
  static const int TentaclePacketTypeSimpleTimestamp = 1;

  /// Simple timestamp including microseconds since last frame (length 11 bytes)
  static const int TentaclePacketTypeMicroseconds = 2;

  /// Microseconds since midnight (length 10 bytes)
  static const int TentaclePacketTypeMicrosecondsSinceMidnight = 3;

  /// SMPTE-12M user bits
  static const int TentaclePacketTypeUserBits = 4;
}

/// Wireless sync status.
abstract class TentacleWirelessSyncStatus {
  /// Wireless sync has not been started
  static const int TentacleWirelessSyncStatusNotStarted = 0;

  /// Wireless sync is in progress
  static const int TentacleWirelessSyncStatusStarted = 1;

  /// Wireless sync failed for this device
  static const int TentacleWirelessSyncStatusFailed = 2;

  /// Wireless sync has been successful for this device
  static const int TentacleWirelessSyncStatusSuccess = 3;
}

/// @brief
/// User bits information as defined in SMPTE-12M.
@ffi.Packed(1)
final class TentacleAdvertisementUserBits extends ffi.Struct {
  /// True if user bits data is available.
  @ffi.Bool()
  external bool available;

  /// User bits as defined in SMPTE-12M
  @ffi.Uint32()
  external int userBits;

  /// Binary group bits as defined in SMPTE-12M
  @ffi.Uint8()
  external int binaryGroup;

  /// Tentacle user bits format, see enum `TentacleUserBitsFormat`
  @ffi.Int32()
  external int format;
}

/// @brief
/// User bits format can either be fixed or created dynamically, based on the date
/// provided by the real time clock (RTC).
///
/// This is a bit field, for example 0x90 corresponds to
/// `TentacleUserBitsFormatFixed` and `TentacleUserBitsFormatFromSource`
/// being set.
abstract class TentacleUserBitsFormat {
  /// Fixed preset value was set
  static const int TentacleUserBitsFormatFixed = 16;

  /// RTC format DDMMYY
  static const int TentacleUserBitsFormatDDMMYY = 33;

  /// RTC format MMDDYY
  static const int TentacleUserBitsFormatMMDDYY = 34;

  /// RTC format DDMMYYYY
  static const int TentacleUserBitsFormatDDMMYYYY = 35;

  /// RTC format MMDDYYYY
  static const int TentacleUserBitsFormatMMDDYYYY = 36;

  /// RTC format YYMMDD
  static const int TentacleUserBitsFormatYYMMDD = 37;

  /// RTC format  YYYYMMDD
  static const int TentacleUserBitsFormatYYYYMMDD = 38;

  /// User bits originate ("taken over") from external timecode source
  static const int TentacleUserBitsFormatFromSource = 128;
}

/// @brief
/// Cached data of a discovered device.
///
/// Also see `TentacleDevice.c`
@ffi.Packed(1)
final class TentacleDevice extends ffi.Struct {
  /// Last received advertisement for this device
  external TentacleAdvertisement advertisement;

  /// Ring buffer of cached timecodes
  @ffi.Array.multi([10])
  external ffi.Array<TentacleTimecode> timecodeCache;

  /// Current index of timecode in ring buffer
  @ffi.Size()
  external int timecodeCacheIndex;

  /// Current size of timecode ring buffer
  @ffi.Size()
  external int timecodeCacheSize;

  /// Averaged timecode of all timecodes from timecode cache
  external TentacleTimecode timecode;

  /// Ring buffer of received signal strength indication (RSSI) values
  @ffi.Array.multi([5])
  external ffi.Array<ffi.Int> rssiCache;

  /// Next index in RSSI ring buffer to use
  @ffi.Size()
  external int rssiCacheNextIndex;

  /// @private Used to calculate precise timecode
  @ffi.Int()
  external int startPhaseCounter;

  /// @private Used to calculate precise timecode
  @ffi.Int()
  external int asyncCounter;

  /// @private Used to calculate precise timecode
  @ffi.Int()
  external int severeAsyncCounter;
}
