// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

// Keep in sync with MegaLights::ETileType
// Simple: default lit
// Single: cloth, subsurface, clear coat
// Complex: aniso, hair, eye
// ComplexSpecial: glints
#define TILE_MODE_SIMPLE_SHADING						0
#define TILE_MODE_COMPLEX_SHADING						1
#define TILE_MODE_SIMPLE_SHADING_RECT					2
#define TILE_MODE_COMPLEX_SHADING_RECT					3
#define TILE_MODE_SIMPLE_SHADING_RECT_TEXTURED			4
#define TILE_MODE_COMPLEX_SHADING_RECT_TEXTURED			5
#define TILE_MODE_EMPTY									6
// Substrate
#define TILE_MODE_SINGLE_SHADING						7
#define TILE_MODE_SINGLE_SHADING_RECT					8
#define TILE_MODE_SINGLE_SHADING_RECT_TEXTURED			9
// Substrate-Adaptive
#define TILE_MODE_COMPLEX_SPECIAL_SHADING				10
#define TILE_MODE_COMPLEX_SPECIAL_SHADING_RECT			11
#define TILE_MODE_COMPLEX_SPECIAL_SHADING_RECT_TEXTURED	12

#define TILE_MODE_MAX_LEGACY							7
#define TILE_MODE_MAX_SUBSTRATE_BLENDABLE				10
#define TILE_MODE_MAX_SUBSTRATE_ADAPTIVE				13

// Keep in sync with MegaLights.cpp
#define TILE_SIZE						8
#define VISIBLE_LIGHT_HASH_TILE_SIZE	8

// Limited by PackLightSample and PackCandidateLightSample
#define MAX_LOCAL_LIGHT_NUM				32768
#define MAX_LOCAL_LIGHT_INDEX			(MAX_LOCAL_LIGHT_NUM - 1)

// Keep in sync with FMegaLightsVisualizationData::EModeID
#define MEGA_LIGHTS_VISUALIZE_OVERVIEW							1
#define MEGA_LIGHTS_VISUALIZE_SHADOW_CASTERS					2
#define MEGA_LIGHTS_VISUALIZE_SHADOW_CASTER_QUALITY				3
#define MEGA_LIGHTS_VISUALIZE_DENOISER_OVERVIEW					4
#define MEGA_LIGHTS_VISUALIZE_DENOISER_OVERVIEW2				5
#define MEGA_LIGHTS_VISUALIZE_SHADING_CONFIDENCE				6
#define MEGA_LIGHTS_VISUALIZE_NUM_FRAMES_ACCUMULATED			7
#define MEGA_LIGHTS_VISUALIZE_UPSAMPLE_MASK						8
#define MEGA_LIGHTS_VISUALIZE_DIFFUSE_DEMODULATE				9
#define MEGA_LIGHTS_VISUALIZE_SPECULAR_DEMODULATE				10
#define MEGA_LIGHTS_VISUALIZE_DIFFUSE_STD_DEV					11
#define MEGA_LIGHTS_VISUALIZE_SPECULAR_STD_DEV					12
#define MEGA_LIGHTS_VISUALIZE_DIFFUSE_HISTORY_SPATIAL_STD_DEV	13
#define MEGA_LIGHTS_VISUALIZE_SPECULAR_HISTORY_SPATIAL_STD_DEV	14
#define MEGA_LIGHTS_VISUALIZE_DIFFUSE_HISTORY_CLAMP				15
#define MEGA_LIGHTS_VISUALIZE_SPECULAR_HISTORY_CLAMP			16
#define MEGA_LIGHTS_VISUALIZE_MIN								MEGA_LIGHTS_VISUALIZE_OVERVIEW
#define MEGA_LIGHTS_VISUALIZE_MAX								MEGA_LIGHTS_VISUALIZE_SPECULAR_HISTORY_CLAMP