// Copyright Epic Games, Inc. All Rights Reserved.

import 'package:pigeon/pigeon.dart';

@ConfigurePigeon(PigeonOptions(
  copyrightHeader: 'pigeons/copyright.txt',
  dartOut: 'lib/src/platform/tentacle_api.g.dart',
  kotlinOut: 'android/src/main/kotlin/com/epicgames/flutter_tentacle/api/TentacleApi.g.kt',
  kotlinOptions: KotlinOptions(errorClassName: 'FlutterTentacleError'),
  swiftOut: 'IOS/Classes/API/TentacleApi.g.swift',
))

/// Types of Tentacle products.
enum TentacleProductId {
  generic,
  syncE,
  trackE,
  timebar,
}

/// Information about a Tentacle device. This only includes data which is expected to be requested infrequently, so it
/// excludes the time code, last seen time, etc.
class TentacleDeviceInfo {
  const TentacleDeviceInfo({
    required this.bIsInGreenMode,
    required this.bIsCharging,
    required this.bIsDropFrame,
    required this.batteryLevel,
    required this.frameRate,
    required this.lastSeenTimestamp,
    required this.iconIndex,
    required this.signalStrength,
    required this.productId,
    required this.identifier,
    required this.name,
  });

  /// True if the device is generating timecodes.
  final bool bIsInGreenMode;

  /// Whether the battery is charging.
  final bool bIsCharging;

  /// Whether the device is generating drop-frame timecodes.
  final bool bIsDropFrame;

  /// Current battery level in percent.
  final int batteryLevel;

  /// Frame rate of the timecodes generated by this device in frames per second.
  final double frameRate;

  /// Device timestamp (seconds since boot) when the device was last detected.
  final double lastSeenTimestamp;

  /// Index of the icon used to represent this device.
  final int iconIndex;

  /// Received signal strength in decibel-milliwatts.
  final int signalStrength;

  /// The type of Tentacle product.
  final TentacleProductId productId;

  /// Unique identifier string for the device.
  final String identifier;

  /// User-assigned name for the device.
  final String name;
}

/// API that receives messages about Tentacle devices in the host language.
@HostApi()
abstract class TentacleHostApi {
  /// Start scanning for Tentacle devices using BLE.
  /// Bluetooth permission must be acquired before calling this.
  void startScanning();

  /// Stop scanning for Tentacle devices using BLE.
  void stopScanning();

  /// Get the latest list of cached device information.
  List<TentacleDeviceInfo> getCachedDeviceInfo();
}

/// API that receives messages about Tentacle devices in Flutter.
@FlutterApi()
abstract class TentacleFlutterApi {}
