// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "MetaHumanCharacterPipeline.h"

#include "MetaHumanInstanceParameterCollection.h"
#include "MetaHumanPipelineBuiltDataCollection.h"

#include "MetaHumanItemPipeline.generated.h"

#define UE_API METAHUMANCHARACTERPALETTE_API

struct FMetaHumanPaletteBuiltData;
class UMetaHumanItemEditorPipeline;

/** The Wardrobe Item-specific subclass of Character Pipeline */
UCLASS(Abstract, MinimalAPI)
class UMetaHumanItemPipeline : public UMetaHumanCharacterPipeline
{
	GENERATED_BODY()

public:
#if WITH_EDITOR
	virtual const UMetaHumanItemEditorPipeline* GetEditorPipeline() const
		PURE_VIRTUAL(UMetaHumanItemPipeline::GetEditorPipeline,return nullptr;);

	/**
	 * Mutable accessor for the editor pipeline. 
	 * 
	 * The default implementation calls GetEditorPipeline and removes const from the result. 
	 */
	UE_API virtual UMetaHumanItemEditorPipeline* GetMutableEditorPipeline();
#endif

	/**
	 * Assembles the item using the build output that was generated by the corresponding 
	 * editor pipeline.
	 * 
	 * Can only be called from a Collection pipeline. Items can't be assembled without a Collection.
	 * 
	 * ItemBuiltData is a filtered view of the built data that only allows access to data belonging
	 * to this item and its sub-items.
	 */
	struct FAssembleItemParams
	{
		FMetaHumanPaletteItemPath BaseItemPath;
		TNotNull<UObject*> OuterForGeneratedObjects;
		FMetaHumanPipelineBuiltDataCollectionView ItemBuiltData;
		EMetaHumanCharacterPaletteBuildQuality Quality = EMetaHumanCharacterPaletteBuildQuality::Production;
		TConstArrayView<FMetaHumanPipelineSlotSelectionData> SortedSlotSelections;
		FInstancedStruct AssemblyInput;
		FMetaHumanInstanceParameterCollectionView AssemblyParameters;
	};

	virtual void AssembleItem(const FAssembleItemParams& Params, const FOnAssemblyComplete& OnComplete) const
		PURE_VIRTUAL(UMetaHumanItemPipeline::AssembleItem,);

	UE_API void AssembleItemSynchronous(const FAssembleItemParams& Params, FMetaHumanAssemblyOutput& OutAssemblyOutput) const;

	UE_DEPRECATED(5.8, "This overload of AssembleItem is deprecated")
	UE_API void AssembleItem(
		const FMetaHumanPaletteItemPath& BaseItemPath,
		const TArray<FMetaHumanPipelineSlotSelectionData>& SlotSelections,
		const FMetaHumanPaletteBuiltData& ItemBuiltData,
		const FInstancedStruct& AssemblyInput,
		TNotNull<UObject*> OuterForGeneratedObjects,
		const FOnAssemblyComplete& OnComplete) const;

	UE_DEPRECATED(5.8, "This overload of AssembleItemSynchronous is deprecated")
	UE_API void AssembleItemSynchronous(
		const FMetaHumanPaletteItemPath& BaseItemPath,
		const TArray<FMetaHumanPipelineSlotSelectionData>& SlotSelections,
		const FMetaHumanPaletteBuiltData& ItemBuiltData,
		const FInstancedStruct& AssemblyInput,
		TNotNull<UObject*> OuterForGeneratedObjects,
		FMetaHumanAssemblyOutput& OutAssemblyOutput) const;

	/**
	 * Item version of UMetaHumanCollectionPipeline::SetPostAssemblyParameters. See comments there
	 * for more information.
	 * 
	 * Should only be called from SetPostAssemblyParameters on the collection pipeline or the 
	 * owning item's pipeline.
	 * 
	 * Note that the InOutItemAssemblyOutput is *not* guaranteed to be identical to the assembly 
	 * output produced by AssembleItem.
	 * 
	 * For example, if the assembly output from this item included a mesh and a set of materials, 
	 * and the owning collection pipeline has merged that mesh with other meshes during assembly, 
	 * and then the user wants to set a Post-Assembly Parameter that would affect a material 
	 * parameter:
	 * 
	 * 	a) 	The original mesh may no longer exist (e.g. if it was generated by this pipeline during 
	 * 		assembly and discarded), so it may not be feasible to pass it in here, and
	 * 
	 * 	b) 	The mesh is not actually needed to set a material parameter, so it doesn't make sense 
	 * 		to require it.
	 * 
	 * The item pipeline's requirements for setting a specific Post-Assembly Parameter are part of
	 * its API and it's the caller's responsibility to manage this. In simple "passthrough" cases, 
	 * where the item pipeline's assembly output is passed through to the collection pipeline's
	 * assembly output without being modified, the collection pipeline can easily provide the 
	 * item's original assembly output to this function. It's only when the collection pipeline 
	 * modifies the item's assembly output in some way that this API becomes important and the 
	 * collection pipeline must accept the maintenance burden for that.
	 */
	struct FSetPostAssemblyParametersParams
	{
		EMetaHumanCharacterPaletteBuildQuality Quality = EMetaHumanCharacterPaletteBuildQuality::Production;
		FMetaHumanPaletteItemPath BaseItemPath;
		FMetaHumanPipelineBuiltDataCollectionView ItemBuiltData;
		FMetaHumanPostAssemblyParameterOutputCollectionView AllPostAssemblyParameters;
		FMetaHumanPaletteItemPath TargetItemPath;
		const FInstancedPropertyBag& ModifiedPostAssemblyParameters;
	};

	UE_API virtual void SetPostAssemblyParameters(const FSetPostAssemblyParametersParams& Params, FInstancedStruct& InOutItemAssemblyOutput) const;

	/**
	 * Returns true if the given slot selections are a permitted combination.
	 * 
	 * This allows the pipeline to restrict Instances to selecting items that are compatible with
	 * each other using any arbitary logic.
	 * 
	 * As with AssembleItem, SlotSelections and ItemBuiltData will only contain entries relating to
	 * this item and its sub-items.
	 * 
	 * If AreSlotSelectionsAllowed returns false, the text assigned to OutDisallowedReason may be 
	 * shown to the user to explain why this combination is not allowed.
	 * 
	 * The order of elements in SlotSelections must not affect the return value of this function.
	 * It may affect OutDisallowedReason, for example if there are multiple reasons why the 
	 * selection is not allowed.
	 */
	UE_API virtual bool AreSlotSelectionsAllowed(
		const FMetaHumanPaletteItemPath& BaseItemPath,
		TArrayView<const FMetaHumanPipelineSlotSelection> SlotSelections,
		const FMetaHumanPaletteBuiltData& ItemBuiltData,
		FText& OutDisallowedReason) const;
};

#undef UE_API
