// Copyright Epic Games, Inc. All Rights Reserved.
//
// This is an auto-generated file. See FlutterLiveLinkVCAM/pigeons/README for information on how to
// modify the original source and generate a new file.
//
// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterTentacleError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterTentacleError {
  return FlutterTentacleError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterTentacleError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Types of Tentacle products. */
enum class TentacleProductId(val raw: Int) {
  GENERIC(0),
  SYNC_E(1),
  TRACK_E(2),
  TIMEBAR(3);

  companion object {
    fun ofRaw(raw: Int): TentacleProductId? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Information about a Tentacle device. This only includes data which is expected to be requested infrequently, so it
 * excludes the time code, last seen time, etc.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TentacleDeviceInfo (
  /** True if the device is generating timecodes. */
  val bIsInGreenMode: Boolean,
  /** Whether the battery is charging. */
  val bIsCharging: Boolean,
  /** Whether the device is generating drop-frame timecodes. */
  val bIsDropFrame: Boolean,
  /** Current battery level in percent. */
  val batteryLevel: Long,
  /** Frame rate of the timecodes generated by this device in frames per second. */
  val frameRate: Double,
  /** Device timestamp (seconds since boot) when the device was last detected. */
  val lastSeenTimestamp: Double,
  /** Index of the icon used to represent this device. */
  val iconIndex: Long,
  /** Received signal strength in decibel-milliwatts. */
  val signalStrength: Long,
  /** The type of Tentacle product. */
  val productId: TentacleProductId,
  /** Unique identifier string for the device. */
  val identifier: String,
  /** User-assigned name for the device. */
  val name: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TentacleDeviceInfo {
      val bIsInGreenMode = pigeonVar_list[0] as Boolean
      val bIsCharging = pigeonVar_list[1] as Boolean
      val bIsDropFrame = pigeonVar_list[2] as Boolean
      val batteryLevel = pigeonVar_list[3] as Long
      val frameRate = pigeonVar_list[4] as Double
      val lastSeenTimestamp = pigeonVar_list[5] as Double
      val iconIndex = pigeonVar_list[6] as Long
      val signalStrength = pigeonVar_list[7] as Long
      val productId = pigeonVar_list[8] as TentacleProductId
      val identifier = pigeonVar_list[9] as String
      val name = pigeonVar_list[10] as String
      return TentacleDeviceInfo(bIsInGreenMode, bIsCharging, bIsDropFrame, batteryLevel, frameRate, lastSeenTimestamp, iconIndex, signalStrength, productId, identifier, name)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      bIsInGreenMode,
      bIsCharging,
      bIsDropFrame,
      batteryLevel,
      frameRate,
      lastSeenTimestamp,
      iconIndex,
      signalStrength,
      productId,
      identifier,
      name,
    )
  }
}
private open class TentacleApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TentacleProductId.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TentacleDeviceInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TentacleProductId -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is TentacleDeviceInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * API that receives messages about Tentacle devices in the host language.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface TentacleHostApi {
  /**
   * Start scanning for Tentacle devices using BLE.
   * Bluetooth permission must be acquired before calling this.
   */
  fun startScanning()
  /** Stop scanning for Tentacle devices using BLE. */
  fun stopScanning()
  /** Get the latest list of cached device information. */
  fun getCachedDeviceInfo(): List<TentacleDeviceInfo>

  companion object {
    /** The codec used by TentacleHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      TentacleApiPigeonCodec()
    }
    /** Sets up an instance of `TentacleHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TentacleHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_tentacle.TentacleHostApi.startScanning$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startScanning()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_tentacle.TentacleHostApi.stopScanning$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopScanning()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_tentacle.TentacleHostApi.getCachedDeviceInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCachedDeviceInfo())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * API that receives messages about Tentacle devices in Flutter.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class TentacleFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by TentacleFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      TentacleApiPigeonCodec()
    }
  }
}
