// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: horde/log_rpc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Horde.Common.Rpc {

  /// <summary>Holder for reflection information generated from horde/log_rpc.proto</summary>
  public static partial class LogRpcReflection {

    #region Descriptor
    /// <summary>File descriptor for horde/log_rpc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LogRpcReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNob3JkZS9sb2dfcnBjLnByb3RvEgVIb3JkZRobZ29vZ2xlL3Byb3RvYnVm",
            "L2VtcHR5LnByb3RvGhxob3JkZS9sb2dfcnBjX21lc3NhZ2VzLnByb3RvMvEB",
            "CgZMb2dScGMSRAoJVXBkYXRlTG9nEhouSG9yZGUuUnBjVXBkYXRlTG9nUmVx",
            "dWVzdBobLkhvcmRlLlJwY1VwZGF0ZUxvZ1Jlc3BvbnNlElQKDVVwZGF0ZUxv",
            "Z1RhaWwSHi5Ib3JkZS5ScGNVcGRhdGVMb2dUYWlsUmVxdWVzdBofLkhvcmRl",
            "LlJwY1VwZGF0ZUxvZ1RhaWxSZXNwb25zZSgBMAESSwoPQ3JlYXRlTG9nRXZl",
            "bnRzEiAuSG9yZGUuUnBjQ3JlYXRlTG9nRXZlbnRzUmVxdWVzdBoWLmdvb2ds",
            "ZS5wcm90b2J1Zi5FbXB0eUITqgIQSG9yZGUuQ29tbW9uLlJwY2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Horde.Common.Rpc.LogRpcMessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
