// Copyright Epic Games, Inc. All Rights Reserved.
// 
// This is an auto-generated file. See FlutterLiveLinkVCAM/pigeons/README for information on how to
// modify the original source and generate a new file.
// 
// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterArError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterArError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Possible tracking states for an AR session's camera. */
enum class ArTrackingState(val raw: Int) {
  /** Tracking data is available. */
  NORMAL(0),
  /** Tracking data may not be accurate. */
  LIMITED(1),
  /** Tracking data is unavailable. */
  UNAVAILABLE(2);

  companion object {
    fun ofRaw(raw: Int): ArTrackingState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Availability of AR features on the device. */
enum class ArAvailability(val raw: Int) {
  /** The feature is not available on the user's device. */
  NOTSUPPORTED(0),
  /**
   * The feature may be available on the user's device, but the user declined to install or encountered an error while
   * doing so.
   */
  NOTINSTALLED(1),
  /** The feature may be available on the user's device, but the user declined camera permission. */
  CAMERANOTPERMITTED(2),
  /** The feature is ready to use. */
  AVAILABLE(3);

  companion object {
    fun ofRaw(raw: Int): ArAvailability? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Data produced during a single frame in an AR session.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ArFrame (
  /** Data for the camera's 4x4 transform matrix. */
  val cameraTransformData: ByteArray

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): ArFrame {
      val cameraTransformData = list[0] as ByteArray
      return ArFrame(cameraTransformData)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      cameraTransformData,
    )
  }
}

/**
 * API that receives messages about ArSession instances in the host language.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ArSessionHostApi {
  /**
   * Request all necessary permissions and/or installation steps for AR functionality.
   * Must be called before [create].
   * Completes with the new availability after user agreement completes or fails.
   * If the platform doesn't require this step, the future completes immediately.
   */
  fun initialize(callback: (Result<ArAvailability>) -> Unit)
  /**
   * Create an AR session.
   * Returns an ID which can be used to refer to the native object in future calls.
   */
  fun create(callback: (Result<Long>) -> Unit)
  /** Dispose of the AR session with the given [sessionId]. */
  fun dispose(sessionId: Long)
  /**
   * Run the AR session with the given [sessionId].
   * It will begin firing delegate events every frame.
   */
  fun run(sessionId: Long)
  /**
   * Pause the AR session with the given [sessionId].
   * It will stop processing until [run] is called again.
   */
  fun pause(sessionId: Long)

  companion object {
    /** The codec used by ArSessionHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      StandardMessageCodec()
    }
    /** Sets up an instance of `ArSessionHostApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: ArSessionHostApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.live_link_vcam.ArSessionHostApi.initialize", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.initialize() { result: Result<ArAvailability> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data!!.raw))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.live_link_vcam.ArSessionHostApi.create", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.create() { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.live_link_vcam.ArSessionHostApi.dispose", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            var wrapped: List<Any?>
            try {
              api.dispose(sessionIdArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.live_link_vcam.ArSessionHostApi.run", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            var wrapped: List<Any?>
            try {
              api.run(sessionIdArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.live_link_vcam.ArSessionHostApi.pause", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            var wrapped: List<Any?>
            try {
              api.pause(sessionIdArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
@Suppress("UNCHECKED_CAST")
private object ArSessionFlutterApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ArFrame.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ArFrame -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * API that receives messages about ArSession instances in Flutter.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
@Suppress("UNCHECKED_CAST")
class ArSessionFlutterApi(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by ArSessionFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      ArSessionFlutterApiCodec
    }
  }
  /** Called when the AR session with the given [sessionId] produces data for a new [frame]. */
  fun onFrame(sessionIdArg: Long, frameArg: ArFrame, callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.live_link_vcam.ArSessionFlutterApi.onFrame", codec)
    channel.send(listOf(sessionIdArg, frameArg)) {
      callback()
    }
  }
  /** Called when the camera tracking [state] for AR session with the given [sessionId] changes. */
  fun onTrackingStateChanged(sessionIdArg: Long, stateArg: ArTrackingState, callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.live_link_vcam.ArSessionFlutterApi.onTrackingStateChanged", codec)
    channel.send(listOf(sessionIdArg, stateArg.raw)) {
      callback()
    }
  }
}
