;
; Base Driver Deny List
; =====================
;
; Hardware checks are controlled by the console variable "r.WarnOfBadDrivers". The the console variable options for more information.
;
; What to do when a certain driver or hardware shows problems:
;  - If the driver exhibiting the problem is old, add it to the DriverDenyList with "<=". In general it's better to ask users to upgrade.
;  - If the driver exhibiting the problem is the latest, add it to the DriverDenyList with ">=". We should not assume the next driver version fixes the problem.
;
; Expectations on QA:
;  - QA always tests the latest driver version.
;  - When a new driver is released, QA should test it and if it does not introduce bugs the SuggestedDriverVersion should be updated to the latest driver.
;  - If the latest driver is denied, it is not removed until QA verifies it is fixed.
;  - If driver specific bugs are found, enter them in JIRA so that they can be tracked.
;
; Expectations on Engineering:
;  - Bugs on older drivers are added to the DriverDenyList and otherwise ignored.
;  - Bugs on the latest driver are added to the DriverDenyList but treated as critical bugs for which we must try to find a workaround. We must also notify the IHV to help if we cannot find the problem.
;
; INI sections:
;    [Vendor OS] where
;    Vendor: GPU_NVIDIA, GPU_AMD, GPU_Intel
;    OS: Windows, Linux
;
; Explanation of the INI entries:
;  - "SuggestedDriverVersion": string used to communicate to the user which driver version is appropriate (not used by any code), empty if unknown.
;		Can use multiple so we can add per RHI appending ";D3D12" for instance for a specific RHI; having no ';RHI' will return that one if the RHI is not found
;  - "DriverDenyList": array of tests that can be made to mark a driver or a range of them as problematic
;    "DriverVersion": to compare against the "unified driver" (see log) version e.g. "123.45.2" "==123.45" "<123.45", comparison operators: == != > < >= <=
;    "Reason": string used to document the reason for denying the driver, could be shown to the user
;    comment above each deny list entry: more details about the problem, potential workarounds
;    "AdapterGeneration": to compare against the vendor-specific hardware adapter version. Same comparison operators allowed as "DriverVersion".
;  - "SuggestedDriverList": array of tests that can be made to specialize suggested drivers for specific adapters. Useful for pinning adapters that are out of
;    support to their latest support driver version, or to pin problematic adapters to known good driver versions. The "DriverVersion" parameter is the user-facing
;    driver version, similar to "SuggestedDriverVersion".
;
;-----------------------------------------------------------------------------------------------------------------

[GPU_NVIDIA Windows]

; Turing and newer - Suggest 591.86 (January 2026) or later. Require 552.44 (May 2024) for D3D12, 570 series for Vulkan
SuggestedDriverVersion="591.86"
+DriverDenyList=(DriverVersion="<552.44", AdapterGeneration=">=352" Reason="These driver versions have known stability issues and missing features", RHI="D3D12")
+DriverDenyList=(DriverVersion="<570.00", Reason="These driver versions have known stability issues and missing features", RHI="Vulkan")

; Kepler (Out of support) - Latest available driver version is 475.14 (July 2024).
+SuggestedDriverList=(DriverVersion="475.14", AdapterGeneration="<=256")
+DriverDenyList=(DriverVersion="<475.14", AdapterGeneration="<=256", Reason="These driver versions have known security issues")

; Maxwell/Pascal/Volta (Out of support) - Latest available driver version is 582.28 (January 2026). This was a security update, so deny older drivers for these adapters.
+SuggestedDriverList=(DriverVersion="582.28", AdapterGeneration="272")
+SuggestedDriverList=(DriverVersion="582.28", AdapterGeneration="288")
+SuggestedDriverList=(DriverVersion="582.28", AdapterGeneration="304")
+SuggestedDriverList=(DriverVersion="582.28", AdapterGeneration="320")
+SuggestedDriverList=(DriverVersion="582.28", AdapterGeneration="336")
+DriverDenyList=(DriverVersion="<582.28", AdapterGeneration="272", Reason="These driver versions have known security issues")
+DriverDenyList=(DriverVersion="<582.28", AdapterGeneration="288", Reason="These driver versions have known security issues")
+DriverDenyList=(DriverVersion="<582.28", AdapterGeneration="304", Reason="These driver versions have known security issues")
+DriverDenyList=(DriverVersion="<582.28", AdapterGeneration="320", Reason="These driver versions have known security issues")
+DriverDenyList=(DriverVersion="<582.28", AdapterGeneration="336", Reason="These driver versions have known security issues")


;-----------------------------------------------------------------------------------------------------------------

[GPU_NVIDIA Linux]

; Turing and newer - Require recent drivers across the board
SuggestedDriverVersion="595.71"
+DriverDenyList=(DriverVersion="<580.00", Reason="These driver versions have known stability issues and missing features")

; Maxwell/Pascal/Volta (Out of support) - Latest available driver is 580.159.03.
;+SuggestedDriverList=(DriverVersion="580.159", AdapterGeneration="272")
;+SuggestedDriverList=(DriverVersion="580.159", AdapterGeneration="288")
;+SuggestedDriverList=(DriverVersion="580.159", AdapterGeneration="304")
;+SuggestedDriverList=(DriverVersion="580.159", AdapterGeneration="320")
;+SuggestedDriverList=(DriverVersion="580.159", AdapterGeneration="336")


;-----------------------------------------------------------------------------------------------------------------

[GPU_AMD Windows]

; RDNA1 and newer - Suggest 26.2.2 (February 2026) - RDNA1 and RDNA2 are supported by this driver in "maintenance mode".
; Deny drivers before 26.1.1 (January 2026) as previous versions would crash the editor with RT enabled
SuggestedDriverVersion="26.2.2"
+DriverDenyList=(DriverDate="<1-21-2026", AdapterGeneration=">=7", Reason="These driver versions have known stability issues and missing features")

; GCN1 to GCN3 (Out of support) - Latest driver is 22.6.1 (AKA 27.20.20912.1002) (2022).
+SuggestedDriverList=(DriverVersion="22.6.1", AdapterGeneration="<=6")
+DriverDenyList=(DriverVersion="<27.20.20912.1002", AdapterGeneration="<=6", Reason="These driver versions have known stability issues and missing features")

;-----------------------------------------------------------------------------------------------------------------

[GPU_AMD Linux]
SuggestedDriverVersion="26.0.0"

; For SM6 and ray tracing, version 25.0.0+ of RADV is required. Suggesting 26.0+ to conform with the version in Ubuntu 26.04 LTS
; Note that it's also possible to use the AMD proprietary driver (discontinued as of Sept 2025) on Linux, and we don't distinguish between driver vendors.
+DriverDenyList=(DriverVersion="<25.0.0", Reason="These driver versions have known stability issues and missing features")

;-----------------------------------------------------------------------------------------------------------------

[GPU_Intel Windows]

; 6th Gen
+SuggestedDriverList=(DriverVersion="31.0.101.2115", AdapterGeneration="6")
+DriverDenyList=(DriverVersion="<101.2115", RHI="D3D12", AdapterGeneration="6", Reason="These driver versions have known stability and performance issues")

; 7th-10th Gen
+SuggestedDriverList=(DriverVersion="31.0.101.2140", AdapterGeneration="7")
+DriverDenyList=(DriverVersion="<101.2140", RHI="D3D12", AdapterGeneration="7", Reason="These driver versions have known stability and performance issues")

; Gen 11-14, Arc Pro, Arc - Suggest 32.0.101.8509 (February 2026). Deny anything older than 101.5989 (September 2024) for D3D12 and Vulkan
SuggestedDriverVersion="32.0.101.8509"
+DriverDenyList=(DriverVersion="<101.5989", RHI="D3D12", AdapterGeneration=">=11", Reason="These driver versions have known stability and performance issues")
+DriverDenyList=(DriverVersion="<101.5989", RHI="Vulkan", Reason="These driver versions have known stability and performance issues")

; Legacy integrated GPUs are supported by several driver packages (depending on CPU generation) and they all have different version numbers, so
; we will check the date instead. The latest driver for Ivy Bridge chips is 105.161, dated Aug 6th 2020, so we will allow that for D3D11.
+DriverDenyList=(DriverDate="<8-6-2020", Reason="These driver versions have known stability issues and missing features", RHI="D3D11")

;-----------------------------------------------------------------------------------------------------------------

[GPU_Intel Linux]
SuggestedDriverVersion="26.0.0"

; Mesa builds older than 25.0.0 have issues running UE5, so we'll use this as the minimum version.
+DriverDenyList=(DriverVersion="<25.0.0", Reason="These driver versions have known stability issues and missing features")
