// Copyright Epic Games, Inc. All Rights Reserved.

#include "uLang/Semantics/SemanticClass.h"

#include "uLang/Common/Algo/FindIf.h"
#include "uLang/Semantics/MemberOrigin.h"
#include "uLang/Semantics/SemanticInterface.h"
#include "uLang/Semantics/SemanticProgram.h"
#include "uLang/Semantics/SmallDefinitionArray.h"
#include "uLang/Semantics/TypeVariable.h"
#include "uLang/Semantics/VisitSet.h"
#include "uLang/SourceProject/VerseVersion.h"

#include "uLang/Semantics/Expression.h"

namespace uLang
{
/**
 * Represents how @import_as is being used by a verse type.  Once UHT conversion is complete,
 *      @import_as will no longer be used and this can be replaced by a simple call to HasAttributeFunctionHack.
 */
enum class EImportAsMode : uint8_t
{
    NA,             // Definition doesn't have the @import_as attribute
    Opaque,         // Definition uses @import_as where verse can not access elements in the type (i.e. blueprints)
    Transparent,    // Definition uses @import_as for native types generated by UHT verse types.  
                    // Properties can be accessed.
};

/**
 * Get the mode in which @import_as is being used
 */
EImportAsMode GetImportAsMode(const CDefinition& Definition, const CSemanticProgram& Program)
{
    TOptional<CUTF8String> ImportAsPath = Definition.GetAttributes().GetAttributeTextValue(Program._import_as_attribute.Get(), Program);
    if (!ImportAsPath.IsSet())
    {
        return EImportAsMode::NA;
    }
    return ImportAsPath->ToStringView().StartsWith("/*") ? EImportAsMode::Transparent : EImportAsMode::Opaque;
}

CClass::CClass(
    CClassDefinition* Definition,
    CScope& EnclosingScope,
    CClass* Superclass /*= nullptr*/,
    TArray<CInterface*>&& SuperInterfaces /*= {}*/,
    EStructOrClass StructOrClass /*= EStructOrClass::Class*/,
    SEffectSet ConstructorEffects /*= EffectSets::ClassAndInterfaceDefault*/)
    : CClass(&EnclosingScope, Definition, StructOrClass, Superclass, Move(SuperInterfaces), ConstructorEffects, this, {})
{
}

CClass::CClass(
    CScope* ParentScope,
    CClassDefinition* Definition,
    EStructOrClass StructOrClass,
    CClass* Superclass,
    TArray<CInterface*>&& SuperInterfaces,
    SEffectSet ConstructorEffects,
    CClass* GeneralizedClass,
    TArray<STypeVariableSubstitution> TypeVariableSubstitutions)
    : CNominalType(StaticTypeKind, ParentScope->GetProgram())
    , CLogicalScope(CScope::EKind::Class, ParentScope, ParentScope->GetProgram())
    , _Definition(Definition)
    , _StructOrClass(StructOrClass)
    , _Superclass(Superclass)
    , _SuperInterfaces(Move(SuperInterfaces))
    , _ConstructorEffects(ConstructorEffects)
    , _GeneralizedClass(GeneralizedClass)
    , _TypeVariableSubstitutions(Move(TypeVariableSubstitutions))
    , _OwnedNegativeClass(TUPtr<CClass>::New(this))
    , _NegativeClass(_OwnedNegativeClass.Get())
{
    _bHasCyclesBroken = Definition->_bHasCyclesBroken;
}

CClass::CClass(CClass* PositiveClass)
    : CNominalType(StaticTypeKind, PositiveClass->GetProgram())
    , CLogicalScope(CScope::EKind::Class, PositiveClass->GetParentScope(), PositiveClass->GetProgram())
    , _Definition(PositiveClass->_Definition)
    , _StructOrClass(PositiveClass->_StructOrClass)
    , _Superclass(PositiveClass->_Superclass? PositiveClass->_Superclass->_NegativeClass : nullptr)
    , _SuperInterfaces(GetNegativeInterfaces(PositiveClass->_SuperInterfaces))
    , _ConstructorEffects(PositiveClass->_ConstructorEffects)
    , _GeneralizedClass(PositiveClass->_GeneralizedClass)
    , _NegativeClass(PositiveClass)
{
}

bool CClass::IsClassSlowPath(const CClass& Class) const
{
    TArrayG<const CClass*, TInlineElementAllocator<16>> SeenClasses;
    const CClass* RelatedClass = this;

    do
    {
        if (SeenClasses.Contains(RelatedClass))
        {
            return false;
        }
        SeenClasses.Push(RelatedClass);

        if (RelatedClass == &Class)
        {
            return true;
        }

        RelatedClass = RelatedClass->_Superclass;
    } while (RelatedClass);

    return false;
}

const CTypeType* CClass::GetTypeType() const
{
    return &GetProgram().GetOrCreateTypeType(this->_NegativeClass, this);
}

// Only callable Phase > Deferred_Attributes
bool CClass::IsNativeRepresentation() const
{
    if (IsNative())
    {
        return true;
    }

    if (_Superclass && _Superclass->IsNativeRepresentation())
    {
        return true;
    }

    return false;
}

bool CClass::IsAbstract() const
{
    return _Definition->_EffectAttributable.HasAttributeClass(GetProgram()._abstractClass, GetProgram());
}

bool CClass::IsPersistent() const
{
    return _Definition->_EffectAttributable.HasAttributeClass(GetProgram()._persistentClass, GetProgram());
}

bool CClass::IsModuleScopedVarWeakMapKey() const
{
    return _Definition->_EffectAttributable.HasAttributeClass(GetProgram()._moduleScopedVarWeakMapKeyClass, GetProgram());
}

// Only callable Phase > Deferred_Attributes
bool CClass::IsUnique() const
{
    if (_Definition->_EffectAttributable.HasAttributeClass(GetProgram()._uniqueClass, GetProgram()))
    {
        return true;
    }

    // The <unique> effect is heritable
    if (_Superclass && _Superclass->IsUnique())
    {
        return true;
    }

    for (const CInterface* Interface : _SuperInterfaces)
    {
        if (Interface->IsUnique())
        {
            return true;
        }
    }

    return false;
}

bool CClass::HasOrInheritsVar(CVisitSet& VisitSet) const
{
    if (!TryMarkVisited(VisitSet))
    {
        return false;
    }
    if (CLogicalScope::HasVar())
    {
        return true;
    }
    if (_Superclass && _Superclass->HasOrInheritsVar(VisitSet))
    {
        return true;
    }
    for (CInterface* SuperInterface : _SuperInterfaces)
    {
        if (SuperInterface->HasOrInheritsVar(VisitSet))
        {
            return true;
        }
    }
    return false;
}

bool CClass::HasConcreteAttribute() const
{
    return _Definition->_EffectAttributable.HasAttributeClass(GetProgram()._concreteClass, GetProgram());
}

const CClass* CClass::FindConcreteBase() const
{
    for (const CClass* Class = this; Class != nullptr; Class = Class->_Superclass)
    {
        if (Class->HasConcreteAttribute())
        {
            return Class;
        }
    }

    return nullptr;
}

const CClass* CClass::FindInitialConcreteBase() const
{
    const CClass* Result = nullptr;
    for (const CClass* Class = this; Class != nullptr; Class = Class->_Superclass)
    {
        if (Class->HasConcreteAttribute())
        {
            Result = Class;
        }
    }
    return Result;
}

bool CClass::HasCastableAttribute() const
{
    return _Definition->_EffectAttributable.HasAttributeClassHack(GetProgram()._castableClass, GetProgram());
}

const CNominalType* CClass::FindExplicitlyCastableBase() const
{
    for (const CClass* Class = this; Class != nullptr; Class = Class->_Superclass)
    {
        if (Class->HasCastableAttribute())
        {
            return Class;
        }

        for (const CInterface* Interface : Class->_SuperInterfaces)
        {
            if (const CNominalType* Result = Interface->FindExplicitlyCastableBase())
            {
                return Result;
            }
        }
    }

    return nullptr;
}

bool CClass::HasFinalSuperBaseAttribute() const
{
    return _Definition->_EffectAttributable.HasAttributeClass(GetProgram()._finalSuperBaseClass, GetProgram());
}

bool CClass::HasFinalSuperAttribute() const
{
    return _Definition->_EffectAttributable.HasAttributeClass(GetProgram()._finalSuperClass, GetProgram());
}

SAccessLevel CClass::GetDefaultDefinitionAccessLevel() const
{
    const CAstPackage* Package = GetPackage();
    return IsStruct() && (!Package || Package->_EffectiveVerseVersion >= Verse::Version::StructFieldsMustBePublic)
        ? SAccessLevel::EKind::Public
        : CLogicalScope::GetDefaultDefinitionAccessLevel();
}

CUTF8String CClass::AsCodeRecursive(ETypeSyntaxPrecedence OuterPrecedence, TArray<const CFlowType*>& VisitedFlowTypes, bool bLinkable, ETypeStringFlag Flag) const
{
    if (GetParentScope()->GetKind() != CScope::EKind::Function)
    {
        return CNominalType::AsCodeRecursive(OuterPrecedence, VisitedFlowTypes, bLinkable, Flag);
    }
    CUTF8StringBuilder Builder;
    if (Flag == ETypeStringFlag::Qualified)
    {
        CUTF8String Name = GetQualifiedNameString(*GetParentScope()->ScopeAsDefinition());
        Builder.Append(Name.AsCString());
    } 
    else
    {
        CSymbol Name = GetParentScope()->GetScopeName();
        Builder.Append(Name.AsStringView());
    }
    Builder.Append('(');

    const TArray<STypeVariableSubstitution>* InstTypeVariables;
    if (_OwnedNegativeClass)
    {
        InstTypeVariables = &_TypeVariableSubstitutions;
    }
    else
    {
        InstTypeVariables = &_NegativeClass->_TypeVariableSubstitutions;
    }
    const char* Separator = "";
    for (const STypeVariableSubstitution& InstTypeVariable : *InstTypeVariables)
    {
        if (!InstTypeVariable._TypeVariable->_ExplicitParam || !InstTypeVariable._TypeVariable->_NegativeTypeVariable)
        {
            continue;
        }
        Builder.Append(Separator);
        Separator = ",";
        const CTypeBase* Type;
        if (_OwnedNegativeClass)
        {
            Type = InstTypeVariable._PositiveType;
        }
        else
        {
            Type = InstTypeVariable._NegativeType;
        }
        Builder.Append(Type->AsCodeRecursive(ETypeSyntaxPrecedence::List, VisitedFlowTypes, bLinkable, Flag));
    }

    Builder.Append(')');

    return Builder.MoveToString();
}

SmallDefinitionArray CClass::FindDefinitions(const CSymbol& Name, EMemberOrigin Origin, const SQualifier& Qualifier, const CAstPackage* ContextPackage, CVisitSet& VisitSet) const
{
    SmallDefinitionArray Result = CLogicalScope::FindDefinitions(Name, Origin, Qualifier, ContextPackage, VisitSet);
    if (Origin != EMemberOrigin::Original)
    {
        Result.Append(FindInstanceMember(Name, EMemberOrigin::Inherited, Qualifier, ContextPackage, VisitSet));
    }
    return Result;
}

void CClass::ForAllDefinitions(
    EMemberOrigin Origin,
    const TFunction<void(const CDefinition&)>& Functor,
    CVisitSet& VisitSet) const
{
    if (TryMarkVisited(VisitSet))
    {
        CLogicalScope::ForAllDefinitions(Origin, Functor, VisitSet);
        if (Origin != EMemberOrigin::Original)
        {
            if (_Superclass)
            {
                _Superclass->ForAllDefinitions(EMemberOrigin::InheritedOrOriginal, Functor, VisitSet);
            }
            for (CInterface* SuperInterface : _SuperInterfaces)
            {
                SuperInterface->ForAllDefinitions(EMemberOrigin::InheritedOrOriginal, Functor, VisitSet);
            }
        }
    }
}

SmallDefinitionArray CClass::FindInstanceMember(const CSymbol& Name, EMemberOrigin Origin, const SQualifier& Qualifier, const CAstPackage* ContextPackage, CVisitSet& VisitSet) const
{
    SmallDefinitionArray Result;
    // Diamond inheritance (of interfaces) makes it necessary to 
    // first do class inheritance ...
    const CClass* OriginClass = Origin == EMemberOrigin::Inherited ? this->_Superclass : this;
    while (OriginClass && OriginClass->TryMarkVisited(VisitSet))
    {
        // FindDefinition will filter on Qualifier
        Result.Append(OriginClass->FindDefinitions(Name, EMemberOrigin::Original, Qualifier, ContextPackage, VisitSet));
        OriginClass = Origin == EMemberOrigin::Original ? nullptr : OriginClass->_Superclass;
    }

    // .. and then all interfaces.
    if (Origin != EMemberOrigin::Original)
    {
        CVisitSet InterfaceVisitSet;
        OriginClass = this;
        while (OriginClass && OriginClass->TryMarkVisited(InterfaceVisitSet))
        {
            for (CInterface* SuperInterface : OriginClass->_SuperInterfaces)
            {
                Result.Append(SuperInterface->FindInstanceMember(Name, EMemberOrigin::InheritedOrOriginal, Qualifier, ContextPackage, VisitSet));
            }

            OriginClass = OriginClass->_Superclass;
        }
    }
    return Result;
}

EComparability CClass::GetComparability() const
{
    CVisitSet VisitSet;
    return GetComparability(VisitSet);
}

EComparability CClass::GetComparability(CVisitSet& VisitSet) const
{
    const CSemanticProgram& Program = GetProgram();

    if (IsStruct())
    {
        // Structs are only comparable following the versioned change to require struct fields to be public.
        if (GetPackage()->_EffectiveVerseVersion < Verse::Version::StructFieldsMustBePublic)
        {
            return EComparability::Incomparable;
        }

        // Opaque UHT defined UE types are always incomparable.
        // Transparent UHT defined UE verse types are comparable if and only if the <uht_comparable> attribute is specified and all fields are comparable.
        // Verse struct types are comparable if all their fields are comparable.
        switch (GetImportAsMode(*Definition(), Program))
        {
        case EImportAsMode::Opaque:
            return EComparability::Incomparable;
        case EImportAsMode::Transparent:
            if (!_Definition->_EffectAttributable.HasAttributeClassHack(Program._uhtComparableClass, Program))
            {
                return EComparability::Incomparable;
            }
            break;
        case EImportAsMode::NA:
            break;
        }

        // Otherwise, if a struct has only comparable fields, it is considered to be comparable.
        bool bAllDataMembersAreHashable = true;
        for (const CDataDefinition* DataMember : GetDefinitionsOfKind<CDataDefinition>())
        {
            const EComparability DataMemberComparability = DataMember->GetType() ? DataMember->GetType()->GetNormalType().GetComparability() : EComparability::Incomparable;
            switch (DataMemberComparability)
            {
            case EComparability::Comparable:
                bAllDataMembersAreHashable = false;
                break;
            case EComparability::ComparableAndHashable:
                break;
            case EComparability::Incomparable:
                return EComparability::Incomparable;
            default:
                ULANG_UNREACHABLE();
            }
        }

        // The struct is only hashable if all data members are hashable.
        return bAllDataMembersAreHashable ? EComparability::ComparableAndHashable : EComparability::Comparable;
    }

    // The class is only `comparable` if it has the `unique` attribute in its class inheritance chain
    // or its interface inheritance chain.
    for (const CClass* DefinitionClass = this; DefinitionClass; DefinitionClass = DefinitionClass->_Superclass)
    {
        if (!DefinitionClass->TryMarkVisited(VisitSet))
        {
            break;
        }

        // Should perhaps use DefinitionClass->IsUnique(), but that isn't resolved
        // until the semantic analyzer is past the Deferred_Attributes phase
        if (DefinitionClass->_Definition->_EffectAttributable.HasAttributeClassHack(Program._uniqueClass, Program))
        {
            return EComparability::ComparableAndHashable;
        }

        for (CInterface* Interface : DefinitionClass->_SuperInterfaces)
        {
            if (Interface->GetComparability(VisitSet) == EComparability::ComparableAndHashable)
            {
                return EComparability::ComparableAndHashable;
            }
        }
    }

    return EComparability::Incomparable;
}

bool CClass::IsPersistable() const
{
    return _Definition->_EffectAttributable.HasAttributeClassHack(GetProgram()._persistableClass, GetProgram());
}

bool CClass::IsPersonaConstructible() const
{
    if (IsAbstract())
    {
        return false;
    }
    if (_Definition->DerivedConstructorAccessLevel() != uLang::SAccessLevel::EKind::Public)
    {
        return false;
    }
    if (IsParametric())
    {
        return false;
    }
    if (!IsStruct() && !IsExplicitlyConcrete())
    {
        return false;
    }
    for (auto&& DataDefinition : GetDefinitionsOfKind<uLang::CDataDefinition>())
    {
        if (DataDefinition->DerivedAccessLevel() != uLang::SAccessLevel::EKind::Public)
        {
            return false;
        }
    }
    return true;
}

bool CClass::ImplementsInterface(const CInterface& Interface) const
{
    for (const CInterface* SuperInterface : _SuperInterfaces)
    {
        if (SuperInterface->IsInterface(Interface))
        {
            return true;
        }
    }
    if (_Superclass)
    {
        return _Superclass->ImplementsInterface(Interface);
    }
    return false;
}

void CClassDefinition::SetAstNode(CExprClassDefinition* AstNode)
{
    CDefinition::SetAstNode(AstNode);
}
CExprClassDefinition* CClassDefinition::GetAstNode() const
{
    return static_cast<CExprClassDefinition*>(CDefinition::GetAstNode());
}

TArray<TSRef<CExpressionBase>> CClassDefinition::FindMembersWithPredictsAttribute(bool bIncludeSupers) const
{
    TArray<TSRef<CExpressionBase>> Result;

    const CClassDefinition* Def = this;
    for (;;)
    {
        CExprClassDefinition* AstNode = Def->GetAstNode();
        if (AstNode)
        {
            for (const TSRef<CExpressionBase>& Member : AstNode->Members())
            {
                if (const auto& SourceFieldAst = uLang::AsNullable<CExprDataDefinition>(Member);
                    SourceFieldAst && SourceFieldAst->_DataMember->HasPredictsAttribute())
                {
                    Result.Add(Member);
                }
                else if (const auto& SourceFuncAst = uLang::AsNullable<CExprFunctionDefinition>(Member);
                         SourceFuncAst && SourceFuncAst->HasUserAddedPredictsEffect(GetProgram()))
                {
                    Result.Add(Member);
                }
            }
        }

        if (!(bIncludeSupers && Def->_Superclass))
        {
            break;
        }

        Def = Def->_Superclass->_Definition;
    }

    return Result;
}

void CClassDefinition::SetIrNode(CExprClassDefinition* AstNode)
{
    CDefinition::SetIrNode(AstNode);
}

CExprClassDefinition* CClassDefinition::GetIrNode(bool bForce) const
{
    return static_cast<CExprClassDefinition*>(CDefinition::GetIrNode(bForce));
}

void CClassDefinition::MarkPersistenceCompatConstraint() const
{
    if (IsPersistenceCompatConstraint())
    {
        return;
    }
    _bPersistenceCompatConstraint = true;
    if (const CModule* EnclosingModule = _EnclosingScope.GetModule())
    {
        EnclosingModule->MarkPersistenceCompatConstraint();
    }
}

void CClassDefinition::MarkEntitlementCompatConstraint() const
{
    if (IsEntitlementCompatConstraint())
    {
        return;
    }
    _bEntitlementCompatConstraint = true;
    if (const CModule* EnclosingModule = _EnclosingScope.GetModule())
    {
        EnclosingModule->MarkEntitlementCompatConstraint();
    }
}

const CNormalType& CInstantiatedClass::CreateNormalType() const
{
    if (CClass* InstClass = InstantiateClass(*_Class, GetPolarity(), GetSubstitutions()))
    {
        return *InstClass;
    }
    return *_Class;
}

CClass* InstantiatePositiveClass(const CClass& Class, const TArray<STypeVariableSubstitution>& Substitutions)
{
    if (Class.Definition()->_EnclosingScope.GetKind() != CScope::EKind::Function)
    {
        return nullptr;
    }

    TArray<STypeVariableSubstitution> InstTypeVariables = InstantiateTypeVariableSubstitutions(
        Class._TypeVariableSubstitutions,
        Substitutions);

    CClass* const GeneralizedClass = Class._GeneralizedClass;
    if (CClass* const InstClass = GeneralizedClass->_InstantiatedClasses.Find(CClass::Key{ InstTypeVariables }))
    {
        return InstClass;
    }

    CClass* Superclass = Class._Superclass;
    if (Superclass)
    {
        if (CClass* InstSuperclass = InstantiatePositiveClass(*Superclass, Substitutions))
        {
            Superclass = InstSuperclass;
        }
    }

    int32_t I = GeneralizedClass->_InstantiatedClasses.AddNew(
        Class.GetParentScope(),
        Class._Definition,
        Class._StructOrClass,
        Superclass,
        InstantiatePositiveInterfaces(Class._SuperInterfaces, Substitutions),
        Class._ConstructorEffects,
        GeneralizedClass,
        Move(InstTypeVariables));
    CClass* InstClass = GeneralizedClass->_InstantiatedClasses[I];

    Class.InstantiateMembers(*InstClass, *InstClass->_NegativeClass, *InstClass, Substitutions);

    return InstClass;
}

CClass* InstantiateClass(const CClass& Class, ETypePolarity Polarity, const TArray<STypeVariableSubstitution>& Substitutions)
{
    switch (Polarity)
    {
    case ETypePolarity::Negative:
        if (CClass* InstClass = InstantiatePositiveClass(*Class._NegativeClass, Substitutions))
        {
            return InstClass->_NegativeClass;
        }
        return nullptr;
    case ETypePolarity::Positive: return InstantiatePositiveClass(Class, Substitutions);
    default: ULANG_UNREACHABLE();
    }
}
}
