// Copyright Epic Games, Inc. All Rights Reserved.
//
// UbaStaticStubCore.cpp — freestanding C++ core for the static-detour
// stub. Called from uba_detour_init (asm) after caller register state
// is saved.
//
// PHASE 2b scope: walk envp for UBA_COMID, parse as "<uid>+<offset>"
// (decimal uid, decimal offset), build /dev/shm/uba_<hex> path, open +
// mmap the UBA session's shared memory. Store fd / pointer in stub
// globals. Emit marker lines describing what happened.
//
// Later phases: SharedEvent futex protocol + Go syscall.Syscall6 hook.
//
// Constraints:
//   - Freestanding. No libc. Raw SYSCALL only.
//   - String literals forced into .text via STUB_STR so a single
//     `objcopy -O binary --only-section=.text` captures everything.
//   - Hex formatting exactly matches uba::ValueToString (byte-swapped,
//     two chars per non-zero byte). The shm name UBA generates via
//     GetMappingHandleName depends on that format — deviating breaks
//     the attach.

#include <stddef.h>

// First attempt at reusing UBA code in the stub. UbaBase.h is the smallest
// shared header — primitive typedefs, platform macros, Guid. No TLS, no
// allocations. If this compiles in freestanding context, we can layer in
// heavier headers (UbaBinaryReaderWriter.h etc.) behind UBA_STUB_BUILD guards.
#include "UbaBase.h"
#include "UbaBinaryReaderWriter.h"
#include "UbaDirectoryTable.h"
#include "UbaEvent.h"
#include "UbaMemory.h"
#include "UbaProcessStats.h"
#include "UbaProtocol.h"
// UbaDetoursFileMappingTable.h declares MappedFileTable + Rpc_CreateFileW and
// friends. We compile its impl .cpp into the stub and call Rpc_CreateFileW
// from the openat hook — the LD_PRELOAD and stub paths run the same code.
#include "UbaDetoursFileMappingTable.h"
using uba::u8;
using uba::u16;
using uba::u32;
using uba::u64;
using uba::s64;

// Placement-new — pulled in via libstdc++'s <new>. Required for the
// VariableMem<T> pattern that lets us construct non-trivially-constructible
// globals (MemoryBlock, DirectoryTable) at a specific point in
// uba_detour_core rather than via C++ static initialisers (we have no
// _init / no dynamic linker).
#include <new>


typedef unsigned long       uintptr_t;

// Syscall numbers (SYS_openat = 257 etc.), open/mmap flags, FUTEX_WAIT,
// PROT_*, MAP_FAILED and AT_FDCWD come from the real libc headers pulled
// in via UbaBase.h -> UbaPlatform.h under UBA_STUB_BUILD.

// Non-private futex ops — the system header only defines FUTEX_WAIT_PRIVATE
// when linux/futex.h isn't present. UBA crosses process boundaries on these
// words (server + stubbed child share the shm mapping), so we always use the
// non-private (0/1) variants regardless of header availability.
#ifndef FUTEX_WAIT
#define FUTEX_WAIT 0
#endif
#ifndef FUTEX_WAKE
#define FUTEX_WAKE 1
#endif

#define PAGE_SIZE   0x1000

// UBA communication mapping size (Linux). Must match
// uba::CommunicationMemSize in UbaProtocol.h — 64*1024*2 on Linux.
#define UBA_COMM_MEM_SIZE   (64u * 1024u * 2u)

// --- text-section string literals (keeps .rodata empty) --------------------
#define STUB_STR(name, lit) \
    static const char name[] __attribute__((section(".text"), used)) = lit

STUB_STR(s_envPrefix,    "UBA_COMID=");
STUB_STR(s_envLogPrefix, "UBA_LOGFILE=");
STUB_STR(s_envCwdPrefix, "UBA_CWD=");
STUB_STR(s_shmPrefix,    "/dev/shm/uba_");
STUB_STR(s_msgNoEnv,    "[uba_stub] no UBA_COMID; pass-through\n");
STUB_STR(s_msgBadVal,   "[uba_stub] UBA_COMID malformed (expected <uid>+<offset>)\n");
STUB_STR(s_msgOpenFail, "[uba_stub] shm openat failed\n");
STUB_STR(s_msgMapFail,  "[uba_stub] mmap failed\n");
STUB_STR(s_msgAttached,  "[uba_stub] attached to ");
STUB_STR(s_msgNoSyscall, "[uba_stub] Syscall6 address not baked; passing through\n");
STUB_STR(s_msgSyscall,   "[uba_stub] Syscall6 @ 0x");
STUB_STR(s_msgTrampFail, "[uba_stub] trampoline mmap failed\n");
STUB_STR(s_msgMprotFail, "[uba_stub] mprotect failed\n");
STUB_STR(s_msgHooked,    "[uba_stub] Syscall6 hook installed\n");
STUB_STR(s_msgEventTags, "[uba_stub] shm event tags: cancel=");
STUB_STR(s_msgShmPtr,    "[uba_stub] shm ptr=0x");
STUB_STR(s_msgSyscallN,  "[syscall ");
STUB_STR(s_msgInitSent,  "[uba_stub] Init RPC sent\n");
STUB_STR(s_msgInitResp,  "[uba_stub] Init resp: ");
STUB_STR(s_msgInitTimeout, "[uba_stub] Init response timeout\n");
STUB_STR(s_logPayload,     "Hello from UbaStaticStub");
STUB_STR(s_nl,           "\n");

// --- Syscall6 address baked by UbaStaticPatcher ---------------------------
//
// The patcher locates internal/runtime/syscall.Syscall6 in the target's
// symbol table and rewrites the first word here with its absolute virtual
// address. The second word is a magic guard that disambiguates the real
// variable from incidental occurrences of the sentinel in compiled code
// (e.g. comparison immediates generated by `if (g_syscall6Addr == ...)`).
//
// Layout at this symbol:
//   +0  u64 addr      (init to 0xDEADBEEFC0FFEE00, patched to real VA)
//   +8  u64 guard     (constant 0xFEEDFACE12345678, never rewritten)
//
// Patcher search pattern: both bytes together (16 bytes). That pattern
// is unique in the blob.
//
// Volatile so the compiler doesn't constant-fold references into loads.
struct UbaStubSyscall6Slot {
    volatile u64 addr;
    volatile u64 guard;
};
static UbaStubSyscall6Slot g_syscall6 = { 0xDEADBEEFC0FFEE00ULL, 0xFEEDFACE12345678ULL };
#define g_syscall6Addr (g_syscall6.addr)

// Second bake slot — runtime.exit.abi0. Go's runtime issues the final
// SYS_exit_group via an inline `syscall` in this function, bypassing
// internal/runtime/syscall.Syscall6. Hooking it gives the stub a choke
// point to send MessageType_Exit before the kernel terminates us.
// Same sentinel+guard pattern as Syscall6 so the patcher's unique search
// works. Untouched if the target has no runtime.exit.abi0 symbol.
struct UbaStubExitSlot {
    volatile u64 addr;
    volatile u64 guard;
};
static UbaStubExitSlot g_runtimeExit = { 0xDEADBEEFEEEEE500ULL, 0xCAFEBABE87654321ULL };
#define g_runtimeExitAddr (g_runtimeExit.addr)

// --- raw syscall wrappers --------------------------------------------------
static inline s64 raw_syscall0(s64 num)
{
    s64 r;
    __asm__ volatile("syscall" : "=a"(r) : "0"(num) : "rcx", "r11", "memory");
    return r;
}

static inline s64 raw_syscall1(s64 num, s64 a)
{
    s64 r;
    __asm__ volatile("syscall" : "=a"(r) : "0"(num), "D"(a) : "rcx", "r11", "memory");
    return r;
}

static inline s64 raw_syscall3(s64 num, s64 a, s64 b, s64 c)
{
    s64 r;
    __asm__ volatile("syscall" : "=a"(r) : "0"(num), "D"(a), "S"(b), "d"(c) : "rcx", "r11", "memory");
    return r;
}

static inline s64 raw_syscall6(s64 num, s64 a, s64 b, s64 c, s64 d, s64 e, s64 f)
{
    s64 r;
    register s64 r10 __asm__("r10") = d;
    register s64 r8  __asm__("r8")  = e;
    register s64 r9  __asm__("r9")  = f;
    __asm__ volatile(
        "syscall"
        : "=a"(r)
        : "0"(num), "D"(a), "S"(b), "d"(c), "r"(r10), "r"(r8), "r"(r9)
        : "rcx", "r11", "memory"
    );
    return r;
}

static void stub_write(int fd, const char* s, size_t n)
{
    raw_syscall3(SYS_write, (s64)fd, (s64)s, (s64)n);
}

// Freestanding replacements for the libc primitives clang may lower
// to, even in -ffreestanding mode. Marked extern "C" so the compiler
// can emit a call to `memcpy`/`memset`/`memmove` directly. Naive byte
// loops are fine for the stub's small buffer sizes; correctness wins
// over speed.
extern "C" void* memcpy(void* dst, const void* src, size_t n)
{
    u8* d = (u8*)dst; const u8* s = (const u8*)src;
    for (size_t i = 0; i < n; ++i) d[i] = s[i];
    return dst;
}
extern "C" void* memset(void* dst, int c, size_t n)
{
    u8* d = (u8*)dst;
    for (size_t i = 0; i < n; ++i) d[i] = (u8)c;
    return dst;
}
extern "C" void* memmove(void* dst, const void* src, size_t n)
{
    u8* d = (u8*)dst; const u8* s = (const u8*)src;
    if (d < s)
        for (size_t i = 0; i < n; ++i) d[i] = s[i];
    else
        for (size_t i = n; i-- > 0; ) d[i] = s[i];
    return dst;
}
extern "C" int memcmp(const void* a, const void* b, size_t n)
{
    const u8* x = (const u8*)a; const u8* y = (const u8*)b;
    for (size_t i = 0; i < n; ++i) { if (x[i] != y[i]) return x[i] - y[i]; }
    return 0;
}
extern "C" size_t strlen(const char* s)
{
    const char* p = s;
    while (*p) ++p;
    return (size_t)(p - s);
}
// Freestanding str* helpers. Signatures match the symbol table entries glibc
// emits (char* variants), not the const char* C++-overload inlines in
// <string.h>. We skip the <string.h> declarations by defining our own with
// __asm__ name mapping to bypass the overload set.
extern "C" char* __stub_strchr(const char* s, int c) __asm__("strchr");
extern "C" char* __stub_strchr(const char* s, int c)
{
    for (; *s; ++s) if (*s == (char)c) return (char*)s;
    return (c == 0) ? (char*)s : nullptr;
}
extern "C" char* __stub_strrchr(const char* s, int c) __asm__("strrchr");
extern "C" char* __stub_strrchr(const char* s, int c)
{
    const char* last = nullptr;
    for (; *s; ++s) if (*s == (char)c) last = s;
    if (c == 0) return (char*)s;
    return (char*)last;
}
extern "C" int strcmp(const char* a, const char* b)
{
    while (*a && *a == *b) { ++a; ++b; }
    return (unsigned char)*a - (unsigned char)*b;
}
extern "C" char* __stub_strstr(const char* h, const char* n) __asm__("strstr");
extern "C" char* __stub_strstr(const char* h, const char* n)
{
    if (!*n) return (char*)h;
    for (; *h; ++h)
    {
        const char* hh = h; const char* nn = n;
        while (*hh && *nn && *hh == *nn) { ++hh; ++nn; }
        if (!*nn) return (char*)h;
    }
    return nullptr;
}

// Stubs for the UbaMemory.cpp fallback path that would fire if MemoryBlock
// were ever used without Init() (reserveSize == 0 → Allocate bounces to
// aligned_alloc, Free bounces to aligned_free). The stub always constructs
// MemoryBlock with a reserve size, so these should never be reached — but
// they must resolve at link time. If they ever fire at runtime we abort.
//
// stub_not_reached: shared "dead-path" abort helper. Library/CRT stubs that
// resolve link-time references on dead paths route through here so that
// unexpected runtime entry produces a visible error (and a non-zero exit
// code) instead of silent malfunction. Inline-attribute makes the call
// site cheap; the body deliberately doesn't return.
__attribute__((noreturn, noinline))
static void stub_not_reached(const char* what, size_t whatLen)
{
    static const char pre[] __attribute__((section(".text"))) = "[uba_stub] not-reached: ";
    static const char nl[]  __attribute__((section(".text"))) = "\n";
    stub_write(2, pre, sizeof(pre) - 1);
    stub_write(2, what, whatLen);
    stub_write(2, nl, 1);
    raw_syscall1(231 /* SYS_exit_group */, 1);
    __builtin_unreachable();
}
#define STUB_NOT_REACHED(label) do {                                         \
    static const char _stub_msg[] __attribute__((section(".text"))) = label; \
    stub_not_reached(_stub_msg, sizeof(_stub_msg) - 1);                      \
} while (0)

extern "C" void* aligned_alloc(size_t, size_t)
{
    STUB_NOT_REACHED("aligned_alloc");
}
extern "C" void free(void*)
{
    STUB_NOT_REACHED("free");
}

// Freestanding libc-like wrappers around Linux syscalls. Required because
// we build with -nostdlib and shared UBA core code (UbaMemory.cpp,
// UbaParkingLot.cpp) calls these by their POSIX names. Using raw SYSCALL
// means we also don't rely on libc's TLS-based errno — callers inside
// UBA core use return values, not errno, for our purposes.
extern "C" void* mmap(void* addr, size_t len, int prot, int flags, int fd, long off)
{
    // raw mmap returns -errno in -4096..-1 for errors, a page-aligned
    // positive address on success. POSIX callers expect MAP_FAILED (-1)
    // on error, so collapse the error range.
    s64 r = raw_syscall6(SYS_mmap, (s64)addr, (s64)len, (s64)prot, (s64)flags, (s64)fd, (s64)off);
    if (r < 0 && r >= -4096)
        return MAP_FAILED;
    return (void*)r;
}
extern "C" int munmap(void* addr, size_t len)
{
    return (int)raw_syscall6(11 /* SYS_munmap */, (s64)addr, (s64)len, 0, 0, 0, 0);
}
extern "C" int close(int fd)
{
    return (int)raw_syscall1(SYS_close, fd);
}
// Stubs for libc-provided helpers that shared UBA core references. Most of
// these are either on dead paths (GetHugePageCount's fopen/fscanf) or used
// on the uncontended fast path that we want to work without libc. Where a
// function would actually fire, we implement it with raw syscalls so the
// behavior matches libc's semantics.
extern "C" long syscall(long num, ...)
{
    // UBA core's only callers pass up to 4 args (SYS_futex wake/wait path)
    // plus clock_gettime (2 args). Forward via va_list.
    va_list ap; va_start(ap, num);
    s64 a1 = va_arg(ap, s64);
    s64 a2 = va_arg(ap, s64);
    s64 a3 = va_arg(ap, s64);
    s64 a4 = va_arg(ap, s64);
    s64 a5 = va_arg(ap, s64);
    s64 a6 = va_arg(ap, s64);
    va_end(ap);
    return (long)raw_syscall6(num, a1, a2, a3, a4, a5, a6);
}
extern "C" int clock_gettime(int clk_id, struct timespec* tp)
{
    return (int)raw_syscall3(228 /* SYS_clock_gettime */, (s64)clk_id, (s64)tp, 0);
}
// When the stub blob is injected into a glibc-static target (qemu-system-* etc.)
// the target's GLIBC has its own per-thread `__errno_location` returning a TLS
// int.  Our glibc handlers (UbaGlibcHandlers.cpp) need to set that SAME int so
// the target's user-code reads the errno we wrote.  But the stub blob can't
// directly call into the target's libc — symbol resolution happened at the
// stub's link time, and the target's `__errno_location` address is unknown
// then.
//
// Solution: a writable function-pointer slot the patcher fills in.  The
// patcher locates the slot via an entry in the GlibcHandlerTable (kind =
// ImportSlot, name = "__errno_location") whose `offset` Build.sh stamps to
// the blob-relative VA of g_glibc_errno_hook_fn.  At injection time the
// patcher looks up the target's `__errno_location` in its `.symtab` and
// writes the address into the slot.  Our stub's `__errno_location` then
// defers to the target's per-thread errno when set, or falls back to a
// shared int (used by stub-only callers in pre-init paths or when injecting
// into a Go-static target that has no glibc errno).
//
// Not const so the slot is in .data (the linker script folds .data into
// the extracted .text blob).  The patcher updates it at injection time.
extern "C" int* (*g_glibc_errno_hook_fn)(void) __attribute__((used)) = nullptr;

extern "C" int* __errno_location()
{
    if (auto fn = __atomic_load_n(&g_glibc_errno_hook_fn, __ATOMIC_ACQUIRE))
        return fn();
    static int errval = 0;
    return &errval;
}
// __tls_get_addr — per-thread TLS for the tiny .tbss the stub really uses
// (ParkingLot::parkingLotExecutingFunction, ThreadLocalData + its guard,
// getCurrentThreadId::threadId + its guard — total 0x25 bytes per thread).
//
// Why we need a real implementation instead of a shared scratch buffer:
//   getCurrentThreadId() caches its tid in TLS. With shared scratch, the
//   first thread's tid leaks to every other thread, and CriticalSection /
//   ParkingLot reentrance checks fire incorrectly. ParkingLot's slow path
//   would also corrupt across threads. The "we never reach the slow
//   path" claim only held for trivial single-threaded targets like
//   `qemu --help`; a real workload reaches it.
//
// Implementation: a tiny tid-keyed hash table with linear probing. 64
// slots × 64 bytes = 4 KB total. The .tbss is 0x25 bytes so 64 is more
// than enough; if the table ever fills we fall back to a shared buffer
// (degenerate but no worse than the old behaviour). Slot ownership is
// claimed via a single atomic CAS on `ownerTid`. After ownership the
// thread reads/writes its 64-byte block without further synchronization.
namespace
{
    constexpr int kTlsSlots   = 64;
    constexpr int kTlsBufSize = 64;   // total .tbss is 0x25; 64 leaves headroom

    struct alignas(64) StubTlsSlot
    {
        // 0 = unowned. Set once via CAS to the syscall-returned tid.
        u32  ownerTid;
        // 64-byte per-thread block; offsets handed out match .tbss layout
        // (parkingLotExecutingFunction at 0x0, threadLocalData at 0x8, ...).
        char data[kTlsBufSize];
    };

    static StubTlsSlot g_tlsSlots[kTlsSlots] = {};

    // Last-resort fallback when all slots are owned by other threads.
    // Used only if tens of threads churn through the stub — shared, so
    // hitting it is observably wrong, but better than crashing.
    static char g_tlsFallback[kTlsBufSize];
}

extern "C" void* __tls_get_addr(void* arg)
{
    struct TlsIndex { unsigned long mod; unsigned long off; };
    auto*     idx = (TlsIndex*)arg;
    const u64 off = idx ? idx->off : 0;
    if (off >= kTlsBufSize)
        return &g_tlsFallback[0]; // unexpected oversize TLS — degrade safely

    const u32 tid = (u32)raw_syscall0(186 /* SYS_gettid */);
    const u32 hash = tid % kTlsSlots;

    for (int probe = 0; probe < kTlsSlots; ++probe)
    {
        const int slot = (hash + probe) % kTlsSlots;
        u32 cur = __atomic_load_n(&g_tlsSlots[slot].ownerTid, __ATOMIC_ACQUIRE);
        if (cur == tid)
            return &g_tlsSlots[slot].data[off];
        if (cur == 0)
        {
            u32 expected = 0;
            if (__atomic_compare_exchange_n(&g_tlsSlots[slot].ownerTid,
                    &expected, tid, false,
                    __ATOMIC_ACQ_REL, __ATOMIC_ACQUIRE))
            {
                // Fresh slot — already zero-initialized via BSS, no work.
                return &g_tlsSlots[slot].data[off];
            }
            // Lost the CAS race. Re-read this slot below.
            cur = expected;
            if (cur == tid) return &g_tlsSlots[slot].data[off];
        }
        // owned by someone else — keep probing
    }

    // Table saturated. Old shared-scratch behaviour.
    return &g_tlsFallback[off];
}
// __cxa_thread_atexit is emitted for thread_local destructors. We never
// exit threads cleanly (the process just dies), so make it a no-op.
extern "C" int __cxa_thread_atexit(void(*)(void*), void*, void*) { return 0; }
// __assert_fail is referenced by libc's <assert.h>, by libstdc++ debug
// modes, and by BLAKE3's `assert()` calls.  Without a strong definition
// in the blob, the compiler emits the assert path as `callq *(GOT slot)`
// — and the stub linker script does NOT capture .got/.dynamic into the
// extracted blob, so the slot reads zero at runtime and the call jumps
// to address 0 (segfault).  Provide a strong definition so the call
// resolves at link time to a direct RIP-relative call.  The body just
// writes a one-line diagnostic and exit_group(2)s — invariants tripping
// inside the stub are not recoverable.
__attribute__((noreturn))
extern "C" void __assert_fail(const char* expr, const char* file,
                              unsigned int line, const char* fn)
{
    static const char pre[] __attribute__((section(".text"))) = "[uba_stub] assert: ";
    static const char nl[]  __attribute__((section(".text"))) = "\n";
    auto slen = [](const char* s){ if(!s) return 0; int n=0; while(s[n]) ++n; return n; };
    raw_syscall3(1 /* SYS_write */, 2, (s64)pre,  sizeof(pre)-1);
    if (expr) raw_syscall3(1, 2, (s64)expr, slen(expr));
    raw_syscall3(1, 2, (s64)" at ", 4);
    if (file) raw_syscall3(1, 2, (s64)file, slen(file));
    if (fn)   { raw_syscall3(1, 2, (s64)" in ", 4); raw_syscall3(1, 2, (s64)fn, slen(fn)); }
    raw_syscall3(1, 2, (s64)nl,   sizeof(nl)-1);
    (void)line;
    raw_syscall1(231 /* SYS_exit_group */, 134);  // SIGABRT-ish
    __builtin_unreachable();
}
// Minimal strerror — shared UBA core uses it only inside FatalError format
// strings. Return a fixed string so the output doesn't dereference null.
extern "C" char* strerror(int) { return (char*)"(stub: strerror not linked)"; }
// GetHugePageCount (UbaMemory.cpp) path uses these — but only on the huge-
// pages branch, which we never trigger. Abort if hit so we notice rather
// than silently returning fake values that callers might treat as success.
extern "C" FILE* fopen(const char*, const char*) { STUB_NOT_REACHED("fopen"); }
extern "C" int   fclose(FILE*)                   { STUB_NOT_REACHED("fclose"); }
// __isoc23_fscanf is what glibc 2.38+ picks for fscanf when -std=c++20;
// GetHugePageCount is dead code in the stub.
extern "C" int __isoc23_fscanf(...)              { STUB_NOT_REACHED("__isoc23_fscanf"); }
// Minimal vsnprintf for shared DEBUG_LOG_* macros. Covers the format
// specifiers UbaDetoursShared.cpp:WriteDebugLogWithPrefix + the detour's
// DEBUG_LOG call sites actually use: %s %d %u %x %llu %lld %p %c %% plus
// width (%5d), zero-pad (%04x), precision (%.*s), and the ll/z length
// modifiers. Not a full printf — drops flags/modifiers we haven't seen.
static int stub_itoa_u(unsigned long long v, char* buf, int base)
{
    static const char* d = "0123456789abcdef";
    char tmp[32]; int n = 0;
    if (v == 0) { buf[0] = '0'; return 1; }
    while (v) { tmp[n++] = d[v % base]; v /= base; }
    for (int i = 0; i < n; ++i) buf[i] = tmp[n-1-i];
    return n;
}
extern "C" int vsnprintf(char* out, size_t cap, const char* fmt, va_list ap)
{
    size_t o = 0;
    auto put = [&](char c){ if (o + 1 < cap) out[o] = c; ++o; };
    auto puts_n = [&](const char* s, size_t n){ for (size_t i = 0; i < n; ++i) put(s[i]); };
    while (*fmt)
    {
        if (*fmt != '%') { put(*fmt++); continue; }
        ++fmt;
        int pad = 0; bool zero = false; int prec = -1;
        bool left = false;
        if (*fmt == '-') { left = true; ++fmt; }
        if (*fmt == '0') { zero = true; ++fmt; }
        while (*fmt >= '0' && *fmt <= '9') { pad = pad * 10 + (*fmt - '0'); ++fmt; }
        if (*fmt == '.') { ++fmt; prec = 0; if (*fmt == '*') { prec = va_arg(ap, int); ++fmt; }
                           else while (*fmt >= '0' && *fmt <= '9') { prec = prec * 10 + (*fmt - '0'); ++fmt; } }
        int longs = 0;
        if (*fmt == 'l') { ++longs; ++fmt; if (*fmt == 'l') { ++longs; ++fmt; } }
        else if (*fmt == 'z') { longs = 2; ++fmt; }
        char spec = *fmt++;
        char nbuf[32]; int nlen = 0;
        const char* str = nullptr; size_t slen = 0;
        switch (spec)
        {
        case 's': str = va_arg(ap, const char*);
                  if (!str) str = "(null)";
                  slen = 0; while (str[slen] && (prec < 0 || slen < (size_t)prec)) ++slen;
                  if (pad > (int)slen && !left) for (int i = 0; i < pad - (int)slen; ++i) put(' ');
                  puts_n(str, slen);
                  if (pad > (int)slen && left) for (int i = 0; i < pad - (int)slen; ++i) put(' ');
                  break;
        case 'c': put((char)va_arg(ap, int)); break;
        case '%': put('%'); break;
        case 'd': case 'i': {
            long long v = (longs == 2) ? va_arg(ap, long long)
                        : (longs == 1) ? va_arg(ap, long)
                                       : va_arg(ap, int);
            bool neg = v < 0; unsigned long long u = neg ? (unsigned long long)-v : (unsigned long long)v;
            nlen = stub_itoa_u(u, nbuf, 10);
            int total = nlen + (neg ? 1 : 0);
            if (pad > total && !zero && !left) for (int i = 0; i < pad - total; ++i) put(' ');
            if (neg) put('-');
            if (pad > total && zero) for (int i = 0; i < pad - total; ++i) put('0');
            puts_n(nbuf, nlen);
            if (pad > total && left) for (int i = 0; i < pad - total; ++i) put(' ');
            break;
        }
        case 'o': case 'u': case 'x': case 'X': case 'p': {
            unsigned long long u;
            if (spec == 'p') { u = (unsigned long long)va_arg(ap, void*); put('0'); put('x'); }
            else if (longs == 2) u = va_arg(ap, unsigned long long);
            else if (longs == 1) u = va_arg(ap, unsigned long);
            else u = va_arg(ap, unsigned int);
            int base = (spec == 'u') ? 10 : (spec == 'o') ? 8 : 16;
            nlen = stub_itoa_u(u, nbuf, base);
            if (pad > nlen && !left) for (int i = 0; i < pad - nlen; ++i) put(zero ? '0' : ' ');
            puts_n(nbuf, nlen);
            if (pad > nlen && left) for (int i = 0; i < pad - nlen; ++i) put(' ');
            break;
        }
        default: put('%'); put(spec); break; // unknown — passthrough
        }
    }
    if (cap > 0) out[o < cap ? o : cap - 1] = 0;
    return (int)o;
}
extern "C" int snprintf(char* out, size_t cap, const char* fmt, ...)
{
    va_list ap; va_start(ap, fmt);
    int r = vsnprintf(out, cap, fmt, ap);
    va_end(ap);
    return r;
}
// Placement-new works purely from <new>. The throwing + array + aligned
// variants are routed through StubAllocatorAllocate (a fresh-mmap bump
// allocator; see its definition below). We never free — all stub-lifetime
// nodes are reclaimed implicitly when the process exits. This makes
// PopulateDirectoryRecursive's `new u32[1024*1024]` fallback and
// std::unordered_map's Node/Bucket allocations usable in the stub.
extern "C" void* _Znam(size_t n)                     // operator new[](size_t)
{
    return uba::StubAllocatorAllocate(n, 16);
}
extern "C" void _ZdaPv(void*) {}                     // operator delete[](void*) — leak
extern "C" void* _ZnwmSt11align_val_t(size_t n, size_t a) // new(size, align)
{
    return uba::StubAllocatorAllocate(n, a);
}
extern "C" void _ZdlPvmSt11align_val_t(void*, size_t, size_t) {} // leak
// IsMemoryHandle — defined in UbaSharedMemoryView.cpp (which we don't link).
// The only caller in the stub is MappedFileTable::ParseNoLock's re-mapping
// branch (an existing entry is being updated). For files static-detoured Go
// tools open, this branch is essentially dead — but it must resolve at link.
namespace uba {
// Mirror the definition in UbaSharedMemoryView.cpp:163-167 verbatim so runtime
// behavior matches if that branch is ever hit.
bool IsMemoryHandle(const tchar* name)
{
    return *name == MemoryHandleChar || *name == FreeableMemoryHandleChar;
}

// Called from UbaMemory.cpp's mmap-failure FatalError (dead path for us — the
// stub's 1 GiB reservation always succeeds on Linux over-commit). If we ever
// hit this, the mmap failure path is being exercised and we want to know.
u32 GetLastError()
{
    STUB_NOT_REACHED("uba::GetLastError");
}
}

// uba::GetTime — TimerScope's entry/leave both call this. We back it with
// CLOCK_MONOTONIC via clock_gettime syscall. Returns nanoseconds since an
// arbitrary epoch (the stub's TimerScope only uses the delta).
namespace uba {
u64 GetTime()
{
    struct { s64 sec; s64 nsec; } ts = {0,0};
    raw_syscall3(228 /* SYS_clock_gettime */, 1 /* CLOCK_MONOTONIC */, (s64)&ts, 0);
    return (u64)ts.sec * 1'000'000'000ull + (u64)ts.nsec;
}

// WriteDebug / FlushDebugLog — normally in UbaDetoursFunctionsPosix.cpp, not
// linked by the stub. These route the shared-code DEBUG_LOG_* macros (via
// WriteDebugLogWithPrefix → WriteDebug) to the same fd g_logFd uses. Raw
// SYS_write keeps us freestanding.
void WriteDebug(const void* data, u32 dataLen)
{
    if ((int)g_debugFile < 0) return;
    raw_syscall3(1 /* SYS_write */, (s64)g_debugFile, (s64)data, (s64)dataLen);
}
void FlushDebugLog()
{
    if ((int)g_debugFile < 0) return;
    raw_syscall1(74 /* SYS_fsync */, (s64)g_debugFile);
}

// MessageType_Exit sender. Called from uba_syscall_log when the target hits
// SYS_exit / SYS_exit_group. Wire format matches the LD_PRELOAD Deinit send
// in UbaDetoursFunctionsPosix.cpp:4496 — exit code, log name, ProcessStats,
// KernelStats, fire-and-forget. After this the session's HandleExit sets
// m_gotExitMessage = true and the process dies cleanly.
void SendExitRpc(u32 exitCode)
{
    g_stats.detoursMemory = g_memoryBlock.writtenSize;
    RPC_MESSAGE(Exit, log)
    writer.WriteU32(exitCode);
    writer.WriteString(TC(""));
    g_stats.Write(writer);
    g_kernelStats.Write(writer);
    writer.Flush(false);
    pcs.Leave();
}
}

// FatalError stub. UbaDetoursShared.cpp's FatalError pulls Rpc_WriteLog +
// exit() which don't exist in freestanding context; we gate out shared's
// body with `#if !UBA_STUB_BUILD` and keep ours here.
namespace uba {
ANALYSIS_NORETURN void FatalError(u32 code, const tchar* format, ...)
{
    (void)code;
    const char prefix[] = "[uba_stub] FatalError: ";
    stub_write(2, prefix, sizeof(prefix) - 1);
    size_t fl = 0; while (format[fl] && fl < 512) ++fl;
    stub_write(2, format, fl);
    stub_write(2, "\n", 1);
    raw_syscall1(231 /* SYS_exit_group */, 1);
}

// Backing for Allocator<T>::allocate in stub builds. UnorderedMap allocates
// node and bucket storage through this. Simple bump arena: carve from a
// shared 16 MB mmap'd region, grow with another mmap if exhausted. Never
// deallocates — fine because the detour runs for one process lifetime.
struct StubArena
{
    u8* base = 0;
    u64 used = 0;
    u64 size = 0;
};
static StubArena g_stubArena;

void* StubAllocatorAllocate(u64 bytes, u64 alignment)
{
    if (!g_stubArena.base)
    {
        constexpr u64 kArenaBytes = 16ull * 1024 * 1024;
        void* m = mmap(nullptr, kArenaBytes, PROT_READ | PROT_WRITE,
                       MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
        if (m == MAP_FAILED)
        {
            const char msg[] = "[uba_stub] StubArena mmap failed\n";
            stub_write(2, msg, sizeof(msg) - 1);
            raw_syscall1(231, 1);
        }
        g_stubArena.base = (u8*)m;
        g_stubArena.size = kArenaBytes;
    }
    u64 mask = alignment - 1;
    u64 pos = (g_stubArena.used + mask) & ~mask;
    if (pos + bytes > g_stubArena.size)
    {
        const char msg[] = "[uba_stub] StubArena exhausted\n";
        stub_write(2, msg, sizeof(msg) - 1);
        raw_syscall1(231, 1);
    }
    void* p = g_stubArena.base + pos;
    g_stubArena.used = pos + bytes;
    return p;
}
}

// futex(word, op, val, ...). Returns the raw kernel return value.
// Non-private so it works across processes sharing the event memory.
// `__attribute__((unused))` because the first consumer is Phase 2e.4b
// (SharedEvent wait/wake); kept here so -Werror=unused-function doesn't
// trip the build in the interim.
__attribute__((unused))
static inline s64 futex_wait(volatile u32* word, u32 expected)
{
    // FUTEX_WAIT sleeps only if *word == expected at the moment of the
    // syscall. Spurious wakes + the usual EAGAIN-on-race contract apply;
    // callers should loop on their own condition.
    return raw_syscall6(SYS_futex, (s64)word, FUTEX_WAIT, (s64)expected, 0, 0, 0);
}

__attribute__((unused))
static inline s64 futex_wake(volatile u32* word, int count)
{
    // FUTEX_WAKE with `count` == INT_MAX wakes every waiter; 1 wakes one.
    return raw_syscall6(SYS_futex, (s64)word, FUTEX_WAKE, (s64)count, 0, 0, 0);
}

// ------------------------------------------------------------------
// EventFutex view (matches UbaEventFutex.inl in UBA core).
//
// Layout of one SharedEvent storage slot (13 u64s = 104 bytes):
//   offset 0..7   EventHeader (byte 0 = tag; byte 1 = EventResetType)
//   offset 8      m_initialized (bool, 1 byte)
//   offset 9..11  compiler padding
//   offset 12     m_state      (atomic u32: 0=Reset, 2=Signaled, 3=Destroyed)
//   offset 16     m_autoCount  (atomic u32: auto-reset token counter)
//
// Tag values at offset 0: 1 = EventPThread, 2 = SharedEventSemaphore,
// 3 = EventFutex. For static-detoured children, UBA session creates
// tag 3 so we can speak the protocol via futex syscalls alone.
#define UBA_EVENT_TAG_FUTEX   3u
#define UBA_RESET_AUTO        0u
#define UBA_RESET_MANUAL      1u
#define UBA_EVENT_STATE_RESET     0u
#define UBA_EVENT_STATE_SIGNALED  2u
#define UBA_EVENT_STATE_DESTROYED 3u

#define UBA_EVENT_OFFSET_STATE     12
#define UBA_EVENT_OFFSET_AUTOCOUNT 16
#define UBA_EVENT_SIZE             104

// Auto-reset Set: bump m_autoCount + wake one waiter. Mirrors
// EventFutex::Set() for EventResetType_Auto.
__attribute__((unused))
static void event_wake_auto(u8* ev)
{
    volatile u32* ac = (volatile u32*)(ev + UBA_EVENT_OFFSET_AUTOCOUNT);
    __atomic_add_fetch(ac, 1, __ATOMIC_RELEASE);
    futex_wake(ac, 1);
}

// Auto-reset IsSet with optional timeout. Returns 1 on signal, 0 if
// the event was destroyed or `timeoutMs` elapsed. 0xffffffff = infinite.
// Mirrors EventFutex::WaitAuto() semantics closely enough for stub use.
__attribute__((unused))
static int event_wait_auto(u8* ev, u32 timeoutMs = 0xffffffffu)
{
    volatile u32* st = (volatile u32*)(ev + UBA_EVENT_OFFSET_STATE);
    volatile u32* ac = (volatile u32*)(ev + UBA_EVENT_OFFSET_AUTOCOUNT);
    for (;;)
    {
        if (__atomic_load_n(st, __ATOMIC_ACQUIRE) == UBA_EVENT_STATE_DESTROYED)
            return 0;
        u32 c = __atomic_load_n(ac, __ATOMIC_ACQUIRE);
        if (c != 0)
        {
            u32 expected = c;
            if (__atomic_compare_exchange_n(ac, &expected, c - 1, 0,
                __ATOMIC_ACQUIRE, __ATOMIC_RELAXED))
                return 1;
            continue;
        }
        if (timeoutMs == 0)
            return 0;
        struct timespec ts = { 0, 0 };
        const struct timespec* tsPtr = 0;
        if (timeoutMs != 0xffffffffu)
        {
            ts.tv_sec  = (long)(timeoutMs / 1000u);
            ts.tv_nsec = (long)((timeoutMs % 1000u) * 1000000u);
            tsPtr = &ts;
        }
        raw_syscall6(SYS_futex, (s64)ac, FUTEX_WAIT, 0, (s64)tsPtr, 0, 0);
        // Even on timeout we loop once to re-check the counter (the
        // server may have signalled right before the kernel returned).
        if (tsPtr && timeoutMs != 0xffffffffu)
        {
            // After one full timed wait, give up if still no signal.
            // Approximation: re-check once, then exit if still 0.
            if (__atomic_load_n(ac, __ATOMIC_ACQUIRE) == 0 &&
                __atomic_load_n(st, __ATOMIC_ACQUIRE) != UBA_EVENT_STATE_DESTROYED)
                return 0;
        }
    }
}

static int stub_startswith(const char* s, const char* prefix)
{
    while (*prefix)
    {
        if (*s == 0 || *s != *prefix) return 0;
        ++s; ++prefix;
    }
    return 1;
}

// Parse a sequence of ASCII decimal digits at *p into out_val and
// advance *p to the first non-digit. Returns 1 if at least one digit
// was consumed, 0 otherwise.
static int parse_u64_dec(const char** p, u64* out_val)
{
    const char* s = *p;
    u64 v = 0;
    int any = 0;
    while (*s >= '0' && *s <= '9')
    {
        v = v * 10u + (u64)(*s - '0');
        ++s; ++any;
    }
    *p = s;
    if (!any) return 0;
    *out_val = v;
    return 1;
}

// Exactly matches uba::ValueToString. Writes pairs of hex chars per byte
// (high-nibble first within each byte, little-endian across bytes),
// skipping any whole high-order zero bytes. Returns the number of chars
// written. Caller must ensure `out` has room for up to 16 chars + NUL.
static u32 stub_hex_uba(char* out, u64 v)
{
    static const char hex[] __attribute__((section(".text"), used)) = "0123456789abcdef";
    char* it = out;
    for (int i = 0; i != 8; ++i)
    {
        *it++ = hex[(v >> 4) & 0xf];
        *it++ = hex[ v       & 0xf];
        v >>= 8;
        if (!v) break;
    }
    *it = 0;
    return (u32)(it - out);
}

// Writes 16 hex digits (0-padded, MSB first) for the given 64-bit value.
// Used for dumping diagnostic addresses — deterministic layout regardless
// of the value. Does NOT match uba::ValueToString's byte-swapped format.
static void stub_hex16(char* out, u64 v)
{
    static const char hex[] __attribute__((section(".text"), used)) = "0123456789abcdef";
    for (int i = 15; i >= 0; --i)
    {
        out[i] = hex[v & 0xf];
        v >>= 4;
    }
}

// --- stub state (populated during init) ------------------------------------
//
// Lives in ordinary .bss. The stub's linker script (UbaStaticStub.ld)
// collapses .text / .rodata / .data / .bss into one output section and
// materialises .bss as zero bytes so the blob is a self-contained glob.
// The injected PT_LOAD is mapped RWX so these remain writable at runtime.
static int   g_shmFd  = -1;
static void* g_shmMem = 0;

// Trampoline address is read by the bridge in UbaStaticStub.S via a
// rip-relative indirect JMP. Declared non-static so the .S can reach it
// via the standard symbol.
void* g_syscall6Trampoline __attribute__((used)) = 0;

// Alt-stack for the Go syscall hook. Go goroutines enter syscall.Syscall6
// with small per-goroutine stacks — during early goroutine-1 init (Go's
// telemetry sync.Once in `compile`) only ~2 KB may remain to the guard
// page, and the hook's C++ path (ToStringKeyNoCheck alone is a 1952-byte
// frame) overflows it. uba_syscall_bridge switches to g_altStackTop
// before any pushes via rip-relative memory moves — no scratch register
// needed, so Go's register-ABI args survive untouched.
//
// TODO(multi-M): a single alt-stack is only safe while exactly one M is
// routing syscalls through the hook. AOSP Go compile/link are single-M
// during telemetry init (the only codepath we care about today). Multi-
// threaded callers need per-M alt-stacks keyed off Go's g→m pointer, or
// a spinlock-gated pool.
// Alt-stack is mmap'd at uba_detour_core startup (see kAltStackBytes below)
// instead of living in .bss — keeps the blob small even for a 256 KB stack,
// and avoids hitting the linker script's .bss→.text packing limit. Only
// g_altStackTop is exposed to the asm bridge; the actual buffer base isn't
// needed at runtime.
extern "C" u8* g_altStackTop __attribute__((used)) = 0;

// Spinlock serializing bridge entries across OS threads (Go Ms). Held from
// just after the first sigprocmask (signals blocked) to just before the
// second sigprocmask (signals about to be unblocked), covering the alt-stack
// use and the uba_syscall_log call. Without it, two Go Ms calling
// syscall.Syscall6 concurrently race on the single shared alt-stack buffer,
// corrupting each other's saved frames and eventually crashing Go with
// "rip == r14 == <heap addr>" — a dispatched jump through a smashed
// register. The saved-mask and saved-Go-rsp slots are per-call (Go-stack
// and alt-stack locals respectively) so they don't need the lock, but the
// alt-stack buffer itself is genuinely shared, hence the lock. Signals are
// blocked BEFORE the spin-acquire so a nested bridge entry (from a signal
// handler that invokes syscall.Syscall6) can't self-deadlock.
extern "C" u32 g_bridgeLock  __attribute__((used)) = 0;
// 256 KB: PopulateDirectoryRecursive (invoked via Rpc_GetEntryInformation
// when the directory cache misses) declares a 192 KB u32 array on the stack,
// plus the usual bridge-push + C-frame descent. 64 KB was enough for
// openat/CheckRemapping but would immediately overflow on a stat miss.
static constexpr u64 kAltStackBytes = 256 * 1024;

// BLAKE3 forward decls for direct bisect calls from uba_detour_core.
extern "C" void blake3_hasher_init(void*);
extern "C" void blake3_hasher_update(void*, const void*, size_t);
extern "C" void blake3_hasher_finalize(const void*, void*, size_t);

// Full signal mask used by uba_syscall_bridge (in UbaStaticStub.S) to block
// all signals around the hook. Reason: Go's runtime sends itself SIGURG
// for preemption and installs its handler with SA_ONSTACK. If SIGURG is
// delivered while we're executing on the alt-stack, Go's handler inspects
// the interrupted rsp, finds it outside any known goroutine stack, and
// panics with a synthetic "SIGSEGV" trace. Blocking signals for the
// duration of the hook closes that window.
//
// This is a read-only constant; the per-call old-mask that rt_sigprocmask
// writes back is stored in a Go-stack slot inside the bridge, not in a
// global — so concurrent Ms don't overwrite each other's saved masks.
extern "C" u64 g_fullMask __attribute__((used)) = ~0ull;

// Per-process debug log fd. Opened from UBA_LOGFILE env var when
// uba_detour_core runs; -1 means "not configured, log to stderr only".
static int g_logFd = -1;

// Set after the Init RPC succeeds. Once non-zero, the RPC plumbing (events,
// message region) is live and ready for additional messages like CreateFile.
// Consulted by the syscall bridge so it doesn't try to RPC before attach.
//
// Linkage: extern "C" so the glibc-static handlers in UbaGlibcHandlers.cpp can
// gate their RPC paths on the same flag without pulling the variable through
// a wrapper function (Phase 1 — F1.B/C/D handlers all consult this).
extern "C" u32 g_initDone __attribute__((used)) = 0;

// Serialization of concurrent openat RPC requests is now provided by
// uba::g_communicationLock + SCOPED_FUTEX inside the RPC_MESSAGE macro —
// the same path LD_PRELOAD uses. No stub-local lock needed.

// Fields pulled from the MessageType_Init response. The LD_PRELOAD version
// stashes most of these in globals too (see UbaDetoursFunctionsPosix.cpp
// Init() around line 4346). We keep them here so later steps can hand
// directoryTableHandle / mappedFileTableHandle off to FileMapping_MapFromHost.
// Strings get copied into fixed stub-owned buffers because the server writes
// them into the shm message region, which is overwritten on the next RPC.
// Init-response scratch values. After parse, these are copied into the
// uba:: namespace globals (defined below) that the shared detour code
// reaches via the extern declarations in UbaDetoursShared.h.
static u32  g_processId             = 0;
static u8   g_isChild               = 0;
static u8   g_trackInputs           = 0;
// Renamed off the canonical `g_virtualApplication` / `g_virtualWorkingDir`
// because UbaDetoursShared.h (stub build) defines those as macros that expand
// to inline accessor calls. They're still just the Init-response scratch
// buffers here — nothing populates the shared uba::g_virtual*Mem yet.
static char g_initVirtualApp[512];
static u64  g_initVirtualAppLen = 0;
static char g_initVirtualWorkDir[512];
static u64  g_initVirtualWorkDirLen  = 0;
static u64  g_sharedMemoryAllocator = 0;
static u64  g_permanentFilesHandle  = 0;
static u64  g_directoryTableHandle  = 0;
static u32  g_directoryTableSizeMain = 0;
static u32  g_directoryTableSizeOverlay = 0;
static u32  g_directoryTableCount   = 0;
static u64  g_mappedFileTableHandle = 0;
static u32  g_mappedFileTableSize   = 0;
static u32  g_mappedFileTableCount  = 0;
static u64  g_overlayTableHandle    = 0;

// Mmap addresses of the three session-owned shm tables. Opened right after
// Init parses the handles. Size is the UBA hardcoded max (Linux over-commits
// virtual memory, so mapping 128 MB that only has ~180 bytes used is fine).
static u8* g_directoryTableMem  = 0;
static u8* g_mappedFileTableMem = 0;
static u8* g_overlayTableMem    = 0;

// MemoryBlock / DirectoryTable / MappedFileTable / ProcessStats /
// g_communicationLock storage is provided by UbaDetoursShared.cpp via the
// VARIABLE_MEM macro — which gives us both the underlying u64 storage
// (g_memoryBlockMem etc.) and the corresponding references (g_memoryBlock
// etc.). We keep that definition in exactly one place so the shared detour
// code resolves to the same storage the stub's table-init code populates.
//
// The session-bound globals below (g_messageMappingMem, g_writeEvent ...)
// are also not defined here anymore — UbaDetoursShared.cpp owns them for
// LD_PRELOAD. For the stub build they are provided by the ProcessCommunication
// BinaryWriter/Flush plumbing and populated by the Init handshake.
namespace uba {
// Session-bound state populated in uba_detour_core after we attach to shm.
// Matches the LD_PRELOAD globals defined in UbaDetoursMainPosix.cpp; the
// stub's BinaryWriter(ProcessCommunication)/Flush consult these to drive
// the RPC wire. We define them here because we don't link the main-posix TU.
u8*          g_messageMappingMem = nullptr;
SharedEvent* g_writeEvent  = nullptr;
SharedEvent* g_readEvent   = nullptr;
SharedEvent* g_cancelEvent = nullptr;
int          g_sessionPid  = 0;
bool         g_isCancelled = false;

// g_processId is defined in UbaDetoursFunctionsPosix.cpp for the LD_PRELOAD
// build; we don't link that TU, so we provide it here.
u32          g_processId   = 0;
}


// --- Go-syscall hook --------------------------------------------------------
//
// Two 14-byte JMPs are written, one at Syscall6 (redirecting to our bridge)
// and one at the end of the trampoline (jumping back to Syscall6+14 after
// executing the displaced bytes). Both use the same non-register-clobbering
// pattern:
//     FF 25 00 00 00 00              jmpq *0(%rip)
//     <8-byte absolute target>
// Total 14 bytes.
//
// The bridge is hand-written in UbaStaticStub.S. Must not be
// C++-mangled: the .S references it by plain name and so does our
// hook-install code below.
extern "C" void uba_syscall_bridge(void);

static void write_jmp14(u8* dst, u64 target)
{
    dst[0]  = 0xFF;
    dst[1]  = 0x25;
    dst[2]  = 0x00;
    dst[3]  = 0x00;
    dst[4]  = 0x00;
    dst[5]  = 0x00;
    // 8-byte target, little-endian
    for (int i = 0; i < 8; ++i)
        dst[6 + i] = (u8)(target >> (i * 8));
}

// Syscall numbers we decode arguments for. See sys/syscall.h; we only
// pull in the ones file-I/O heavy Go tools actually hit.
#define SYS_nr_read         0
#define SYS_nr_write        1
#define SYS_nr_close        3
#define SYS_nr_fstat        5
#define SYS_nr_lseek        8
#define SYS_nr_mmap         9
#define SYS_nr_pread64      17
#define SYS_nr_pwrite64     18
#define SYS_nr_dup          32
#define SYS_nr_openat       257
#define SYS_nr_mkdirat      258
#define SYS_nr_newfstatat   262
#define SYS_nr_unlinkat     263
#define SYS_nr_renameat     264
#define SYS_nr_readlinkat   267
#define SYS_nr_faccessat    269
#define SYS_nr_renameat2    316
#define SYS_nr_statx        332
#define SYS_nr_faccessat2   439
#define SYS_nr_exit         60
#define SYS_nr_exit_group   231

// Writes one byte; advances *out. Caller ensures capacity.
static void b_push(char** out, char c) { *(*out)++ = c; }

static void b_append(char** out, const char* s, size_t n)
{
    for (size_t i = 0; i < n; ++i) *(*out)++ = s[i];
}

// Append decimal representation of v (unsigned).
static void b_dec(char** out, u64 v)
{
    char tmp[24];
    int n = 0;
    if (v == 0) { b_push(out, '0'); return; }
    while (v)
    {
        tmp[n++] = (char)('0' + (v % 10));
        v /= 10;
    }
    while (n--) b_push(out, tmp[n]);
}

// Append signed decimal. Small negative values (like AT_FDCWD = -100)
// come through as huge unsigned bit patterns; render them as "-N".
static void b_sdec(char** out, u64 v)
{
    s64 s = (s64)v;
    if (s < 0) { b_push(out, '-'); b_dec(out, (u64)(-s)); }
    else        { b_dec(out, (u64)s); }
}

// Append a C-string (reading from the target's memory). Stops at NUL
// or `max` bytes. Caller caps the total emitted count.
static void b_cstr(char** out, const char* s, size_t max)
{
    if (!s) { b_append(out, "(null)", 6); return; }
    b_push(out, '"');
    for (size_t i = 0; i < max; ++i)
    {
        char c = s[i];
        if (!c) break;
        if (c == '\\' || c == '"') { b_push(out, '\\'); b_push(out, c); }
        else if (c == '\n')         { b_push(out, '\\'); b_push(out, 'n'); }
        else if (c < 32 || c > 126) { b_push(out, '.'); }
        else                        { b_push(out, c); }
    }
    b_push(out, '"');
}

// ────────────────────────────────────────────────────────────────────────────
// Close tracking
// ────────────────────────────────────────────────────────────────────────────
//
// openat hooks run BEFORE the real syscall, so we see (path, closeId) but not
// the resulting fd. The bridge was changed to `call` the trampoline instead
// of `jmp`; uba_syscall_post then runs after the real syscall with the fd in
// rax, and correlates it with the pending openat.
//
// The fd→entry map is a fixed-size open-addressed table keyed by fd.
// Concurrent multi-M Go programs would race (same caveat as g_altStackTop);
// AOSP's single-M-during-init workload fits comfortably. If we ever grow a
// per-M alt-stack, this table becomes per-M too.
struct StubFdEntry
{
    u32         fd;        // 0xFFFFFFFF = slot empty
    u32         closeId;
    const char* path;      // borrowed — points into StubAllocator-owned dup
};
static constexpr u32 kFdTableSize = 256;      // linear-probe, ~75% fill OK
alignas(64) static StubFdEntry g_fdTable[kFdTableSize];

// Pending-openat state: written by uba_syscall_log's openat case,
// consumed by uba_syscall_post once the fd comes back.
static const char* g_pendingOpenatPath    = 0;
static u32         g_pendingOpenatCloseId = 0;
static bool        g_pendingOpenatValid   = false;

static inline u32 fd_table_hash(int fd)
{
    u32 x = (u32)fd;
    x ^= x >> 13; x *= 0x5bd1e995u; x ^= x >> 15;
    return x & (kFdTableSize - 1);
}
static void fd_table_insert(int fd, u32 closeId, const char* path)
{
    if (fd < 0) return;
    u32 h = fd_table_hash(fd);
    for (u32 i = 0; i < kFdTableSize; ++i)
    {
        u32 slot = (h + i) & (kFdTableSize - 1);
        StubFdEntry& e = g_fdTable[slot];
        if (e.fd == 0xFFFFFFFFu || e.fd == (u32)fd)
        {
            e.fd = (u32)fd; e.closeId = closeId; e.path = path;
            return;
        }
    }
    // table full — silently drop (observation-only; close RPC just won't fire)
}
static bool fd_table_take(int fd, u32& outCloseId, const char*& outPath)
{
    if (fd < 0) return false;
    u32 h = fd_table_hash(fd);
    for (u32 i = 0; i < kFdTableSize; ++i)
    {
        u32 slot = (h + i) & (kFdTableSize - 1);
        StubFdEntry& e = g_fdTable[slot];
        if (e.fd == 0xFFFFFFFFu) return false;
        if (e.fd == (u32)fd)
        {
            outCloseId = e.closeId;
            outPath    = e.path;
            e.fd = 0xFFFFFFFFu;
            return true;
        }
    }
    return false;
}
static void fd_table_init()
{
    for (u32 i = 0; i < kFdTableSize; ++i) g_fdTable[i].fd = 0xFFFFFFFFu;
}

// Called from uba_syscall_bridge AFTER the real syscall ran via the
// trampoline (the bridge does `call *trampoline` now, not `jmp`). At
// this point rax holds Go's r1 (the syscall result / fd on openat) and
// we can correlate it with the pending-openat state written by the
// pre-hook. Intentionally minimal and runs on Go's real goroutine
// stack (not the alt-stack): we only touch a small table and a few
// globals, no RPC, no BLAKE3, no locks — so the descent fits even on
// a cramped goroutine stack without the alt-stack gymnastics the
// pre-hook needs.
extern "C" __attribute__((used, visibility("hidden")))
void uba_syscall_post(s64 r1)
{
    if (!__atomic_load_n(&g_initDone, __ATOMIC_ACQUIRE)) return;
    if (!g_pendingOpenatValid) return;
    g_pendingOpenatValid = false;
    if (r1 < 0) return;                     // openat failed; nothing to track
    fd_table_insert((int)r1, g_pendingOpenatCloseId, g_pendingOpenatPath);
}

// Called from the assembly bridge on every intercepted Go syscall. `saved`
// points at the 16 saved GPRs (layout documented in UbaStaticStub.S).
// extern "C" so the .S can call by plain name; otherwise C++ mangles it.
//
// Runs with all signals blocked (the bridge calls rt_sigprocmask before
// entering C). Signal blocking is required because we switched to the
// alt-stack, which puts rsp outside any goroutine's known bounds — and
// Go's SIGURG handler (installed SA_ONSTACK) panics when it inspects an
// interrupted rsp that isn't inside a goroutine stack.
extern "C" __attribute__((used, visibility("hidden")))
u64 uba_syscall_log(u64* saved)
{
    // Handled flag: the bridge stashes this return value into a dedicated
    // slot on the alt-stack and recovers it into %r8 after the pop-15-regs
    // sequence. Non-zero = pre-hook synthesized a return via saved[] and
    // the bridge must ret without calling the trampoline; zero = run the
    // real syscall. r8 is caller-saved in Go's internal ABI, so clobbering
    // it across syscall.Syscall6 is safe. (r15 would NOT be safe — it is
    // callee-saved as the closure-context register.)
    u64 handled = 0;

    // saved[] layout matches the asm bridge's push order in UbaStaticStub.S
    // step 7: pushq rax,rbx,rcx,rdx,rdi,rsi,rbp,r8,r9,r10,r11,r12,r13,r14,r15
    // followed by `subq $8` for the alignment pad. rsp at the call points
    // at the pad (saved[0]); the saved registers are at saved[1..15] with
    // r15 closest to rsp (last pushed) and rax furthest (first pushed).
    //
    // Go's syscall.Syscall6 internal ABI: AX=trap, BX=a1, CX=a2, DI=a3,
    // SI=a4, R8=a5, R9=a6. Map those onto the slot layout below.
    u64 trap = saved[15];            // rax = Go trap
    u64 a1   = saved[14];            // rbx = Go a1
    u64 a2   = saved[13];            // rcx = Go a2
    u64 a3   = saved[11];            // rdi = Go a3
    u64 a4   = saved[10];            // rsi = Go a4
    u64 a5   = saved[ 8];            // r8  = Go a5
    u64 a6   = saved[ 7];            // r9  = Go a6

    char buf[512];
    char* p = buf;

    b_append(&p, "[uba] ", 6);
    switch (trap)
    {
        case SYS_nr_openat:
            b_append(&p, "openat(", 7);
            b_sdec(&p, a1); b_append(&p, ", ", 2);
            b_cstr(&p, (const char*)a2, 256); b_append(&p, ", 0x", 4);
            { char h[16]; stub_hex16(h, a3); for (int i = 0; i < 16; ++i) b_push(&p, h[i]); }
            b_append(&p, ")\n", 2);
            // Fire the CreateFile RPC while we have the path. O_RDONLY=0,
            // O_WRONLY=1, O_RDWR=2 map onto UBA's access bits: Read=1,
            // Write=2. Now uses the shared uba::Rpc_CreateFileW (defined in
            // UbaDetoursFileMappingTable.cpp:87-107) over the same shm/event
            // wire protocol as the LD_PRELOAD detour — no ad-hoc code path.
            if (a2 && __atomic_load_n(&g_initDone, __ATOMIC_ACQUIRE))
            {
                const char* path = (const char*)a2;
                u64 plen = 0; while (path[plen] && plen < 4096) ++plen;
                u64 flags = a3 & 0x3;
                u8 access = (flags == 0) ? 1             /* Read */
                          : (flags == 1) ? 2             /* Write */
                                         : (1 | 2)       /* Read|Write */;
                uba::StringView view(path, (uba::u32)plen);
                uba::StringKey  key = uba::ToStringKeyNoCheck(path, plen);
                char    newName[256] = {0};
                uba::u64 outSize = 0;
                uba::u32 outCloseId = 0;
                DEBUG_LOG(TC("openat: %s (%s)"), path, (flags == 0) ? "O_RDONLY" : (flags == 1) ? "O_WRONLY" : "O_RDWR");
                uba::Rpc_CreateFileW(view, key, access, newName, sizeof(newName), outSize, outCloseId, /*lock=*/true);

                // Stash the (path, closeId) pair for uba_syscall_post to
                // pick up once the real openat returns the fd. Dup the
                // path into StubAllocator-owned memory because Go may
                // reuse its string buffer after the syscall completes.
                if (outCloseId)
                {
                    char* dup = (char*)uba::StubAllocatorAllocate(plen + 1, 1);
                    for (u64 i = 0; i < plen; ++i) dup[i] = path[i];
                    dup[plen] = 0;
                    g_pendingOpenatPath    = dup;
                    g_pendingOpenatCloseId = outCloseId;
                    g_pendingOpenatValid   = true;
                }

                // Path substitution: if UBA remapped the path (e.g. remote
                // worker staging, VFS redirect) the server returned a
                // different newName. The trampoline's real openat must
                // use newName — not the caller's original path — or
                // UBA's bookkeeping and the kernel's file state diverge.
                // We dup newName into StubAllocator-owned memory and
                // overwrite saved[13] (the slot that holds rcx = Go ABI
                // a2 = path). The bridge's register-restore pops this
                // back into %rcx before jumping to the trampoline, so
                // Go's Syscall6 sees the substituted pointer.
                //
                // For local sessions newName == path and differs==false,
                // in which case we keep Go's original string untouched.
                u64 nlen = 0; while (nlen < sizeof(newName) && newName[nlen]) ++nlen;
                bool differs = (nlen != plen);
                if (!differs)
                {
                    for (u64 i = 0; i < nlen; ++i)
                        if (newName[i] != path[i]) { differs = true; break; }
                }
                if (differs && nlen > 0)
                {
                    char* subPath = (char*)uba::StubAllocatorAllocate(nlen + 1, 1);
                    for (u64 i = 0; i < nlen; ++i) subPath[i] = newName[i];
                    subPath[nlen] = 0;
                    saved[13] = (u64)subPath;
                }

                // Emit the CreateFile marker as separate stub_write syscalls
                // rather than building a single `char lbuf[512]` and copying
                // the pieces into it. Reason: at -O2, clang vectorizes the
                // inner copy loops using SSE moves that in some target
                // memory layouts (specifically Go `compile` at stub_base
                // 0x15d4000) fault with SIGSEGV/SI_KERNEL at the stack-to-
                // stack memcpy. A few extra syscalls per openat is cheap
                // (this only fires during session init for a handful of
                // files) and sidesteps the class of bug entirely.
                static const char s_pre[] __attribute__((section(".text"))) = "[uba_stub] CreateFile(";
                static const char s_arr[] __attribute__((section(".text"))) = ") -> ";
                static const char s_nl[]  __attribute__((section(".text"))) = "\n";
                stub_write(2, s_pre, sizeof(s_pre) - 1);
                stub_write(2, path, plen);
                stub_write(2, s_arr, sizeof(s_arr) - 1);
                stub_write(2, newName, nlen);
                stub_write(2, s_nl, 1);
                (void)access; (void)outSize; (void)outCloseId;
            }
            break;
        case SYS_nr_newfstatat:
            b_append(&p, "newfstatat(", 11);
            b_sdec(&p, a1); b_append(&p, ", ", 2);
            b_cstr(&p, (const char*)a2, 256);
            b_append(&p, ")\n", 2);
            if (a2 && a3 && __atomic_load_n(&g_initDone, __ATOMIC_ACQUIRE))
            {
                const char* path = (const char*)a2;
                u64 plen = 0; while (path[plen] && plen < 4096) ++plen;
                uba::StringView view(path, (uba::u32)plen);
                uba::StringKey  key = uba::ToStringKeyNoCheck(path, plen);
                uba::DirectoryTable::EntryInformation info;
                if (uba::Rpc_GetEntryInformation(info, key, view, /*checkIfDir=*/false))
                {
                    DEBUG_LOG(TC("newfstatat: %s (size: %llu attr: %x) -> 0 (synthesized)"), path, (u64)info.size, (u32)info.attributes);
                    // Linux x86-64 `struct stat` layout (uapi asm/stat.h).
                    u8* sb = (u8*)a3;
                    for (u64 i = 0; i < 144; ++i) sb[i] = 0;
                    *(u64*)(sb +   0) = info.volumeSerial;   // st_dev
                    *(u64*)(sb +   8) = info.fileIndex;      // st_ino
                    *(u64*)(sb +  16) = 1;                   // st_nlink
                    *(u32*)(sb +  24) = info.attributes;     // st_mode
                    *(u64*)(sb +  48) = info.size;           // st_size
                    *(u64*)(sb +  56) = 4096;                // st_blksize
                    *(u64*)(sb +  64) = (info.size + 511) / 512; // st_blocks
                    // lastWrite is 100-ns ticks since epoch (FromTimeSpec fmt).
                    u64 sec  = info.lastWrite / 10000000ull;
                    u64 nsec = (info.lastWrite % 10000000ull) * 100;
                    *(u64*)(sb +  72) = sec;  *(u64*)(sb +  80) = nsec;  // atime
                    *(u64*)(sb +  88) = sec;  *(u64*)(sb +  96) = nsec;  // mtime
                    *(u64*)(sb + 104) = sec;  *(u64*)(sb + 112) = nsec;  // ctime
                    // Synthesize the return: Go ABI r1=0 (success), r2=0, errno=0.
                    saved[15] = 0;   // rax = r1
                    saved[14] = 0;   // rbx = r2
                    saved[13] = 0;   // rcx = errno
                    handled = 1;
                }
            }
            break;
        // Read-only metadata queries — passthrough to the real syscall.
        // The kernel's answer is authoritative for these; we just log the
        // call so the trace shows what the target asked for.
        case SYS_nr_statx:
            DEBUG_LOG(TC("statx: %s"), (const char*)a2);
            break;
        case SYS_nr_faccessat:
        case SYS_nr_faccessat2:
            DEBUG_LOG(TC("faccessat: %s"), (const char*)a2);
            break;
        case SYS_nr_readlinkat:
            // readlinkat(dirfd, path, buf, bufsize). If UBA's directory
            // table knows the path AND it's a regular file (not a symlink),
            // synthesize -1 / errno=EINVAL — that's the "exists but not a
            // symlink" semantic LD_PRELOAD's readlinkat enforces (see
            // UbaDetoursFunctionsPosix.cpp:1755). Without this, callers
            // probing CAS-staged inputs via readlink fall through to the
            // kernel and get ENOENT (because the CAS path differs from the
            // original) or a path with unresolved .. components, breaking
            // tools like rustc and Go's `os.Stat` symlink probes.
            if (a2 && __atomic_load_n(&g_initDone, __ATOMIC_ACQUIRE))
            {
                const char* path = (const char*)a2;
                u64 plen = 0; while (path[plen] && plen < 4096) ++plen;
                uba::StringView view(path, (uba::u32)plen);
                uba::StringKey  key = uba::ToStringKeyNoCheck(path, plen);
                uba::DirectoryTable::EntryInformation info;
                if (uba::Rpc_GetEntryInformation(info, key, view, /*checkIfDir=*/false))
                {
                    // S_IFMT = 0xF000, S_IFLNK = 0xA000.
                    bool isSymlink = (info.attributes & 0xF000) == 0xA000;
                    if (!isSymlink)
                    {
                        saved[15] = (u64)(-1);   // rax = r1 = -1
                        saved[14] = 0;           // rbx = r2
                        saved[13] = 22;          // rcx = errno = EINVAL
                        handled = 1;
                        DEBUG_LOG(TC("readlinkat: %s -> -1 EINVAL (UBA: regular file)"), path);
                        break;
                    }
                }
            }
            DEBUG_LOG(TC("readlinkat: %s (passthrough)"), (const char*)a2);
            break;
        // Filesystem mutations — UBA's directory/CAS state needs to track
        // these or it will diverge from the kernel's view. We currently
        // don't fire any RPCs for them, so a target that invokes them
        // would silently misbehave (e.g. CloseFile RPCs would emit wrong
        // sizes after a rename, output files would land outside the CAS
        // store after a mkdir). Assert until proper handling lands.
        case SYS_nr_mkdirat:
            DEBUG_LOG(TC("mkdirat: %s — NOT IMPLEMENTED"), (const char*)a2);
            STUB_NOT_REACHED("mkdirat");
        case SYS_nr_renameat:
        case SYS_nr_renameat2:
            DEBUG_LOG(TC("renameat: %s -> %s — NOT IMPLEMENTED"), (const char*)a2, (const char*)a4);
            STUB_NOT_REACHED("renameat");
        case SYS_nr_read:
            b_append(&p, "read(", 5);
            b_dec(&p, a1); b_append(&p, ", ..., ", 7);
            b_dec(&p, a3); b_append(&p, ")\n", 2);
            break;
        case SYS_nr_write:
            b_append(&p, "write(", 6);
            b_dec(&p, a1); b_append(&p, ", ..., ", 7);
            b_dec(&p, a3); b_append(&p, ")\n", 2);
            break;
        case SYS_nr_pread64:
            b_append(&p, "pread64(", 8);
            b_dec(&p, a1); b_append(&p, ", ..., ", 7);
            b_dec(&p, a3); b_append(&p, ", ", 2);
            b_dec(&p, a4); b_append(&p, ")\n", 2);
            break;
        case SYS_nr_close:
            b_append(&p, "close(", 6);
            b_dec(&p, a1); b_append(&p, ")\n", 2);
            // If this fd was tracked through openat, capture its final
            // metadata (size / mtime / mode) via dup+fstat BEFORE the real
            // close runs, then notify UBA. Mirrors Shared_close's flow in
            // the LD_PRELOAD detour: dup(fd), fstat(dup), close(dup) (then
            // the real close of fd happens via the trampoline after the
            // hook returns). The dup ensures fstat sees stdio-flushed
            // contents even when the caller wrapped fd in fdopen, matching
            // the rationale in UbaDetoursFunctionsPosix.cpp:994-1007.
            if (__atomic_load_n(&g_initDone, __ATOMIC_ACQUIRE))
            {
                u32 closeId = 0; const char* path = 0;
                if (fd_table_take((int)a1, closeId, path) && closeId)
                {
                    u64 fileSize      = 0;
                    u64 lastWriteTime = 0;
                    u32 attributes    = 0x8000; // S_IFREG fallback on fstat failure
                    s64 dupFd = raw_syscall6(SYS_nr_dup, (s64)a1, 0, 0, 0, 0, 0);
                    if (dupFd >= 0)
                    {
                        // Linux x86-64 `struct stat` layout (uapi asm/stat.h).
                        alignas(8) u8 sb[144] = {0};
                        s64 r = raw_syscall6(SYS_nr_fstat, dupFd, (s64)sb, 0, 0, 0, 0);
                        if (r == 0)
                        {
                            attributes        = *(const u32*)(sb + 24);  // st_mode
                            fileSize          = *(const u64*)(sb + 48);  // st_size
                            u64 mtimeSec      = *(const u64*)(sb + 88);  // st_mtime
                            u64 mtimeNsec     = *(const u64*)(sb + 96);  // st_mtime_nsec
                            // FromTimeSpec-equivalent: 100-ns ticks since epoch.
                            lastWriteTime = mtimeSec * 10000000ull + mtimeNsec / 100;
                        }
                        (void)raw_syscall6(SYS_nr_close, dupFd, 0, 0, 0, 0, 0);
                    }
                    DEBUG_LOG(TC("close: %s (fd: %llu size: %llu attr: %x)"), path ? path : "(null)", (u64)a1, (u64)fileSize, (u32)attributes);
                    uba::Rpc_UpdateCloseHandle(path, closeId, /*deleteOnClose=*/false,
                        /*newName=*/"", uba::SharedMemoryHandle{},
                        fileSize, lastWriteTime, attributes, /*success=*/true);
                    static const char s_pre[] __attribute__((section(".text"))) = "[uba_stub] CloseFile(";
                    static const char s_mid[] __attribute__((section(".text"))) = ") size=";
                    static const char s_nl[]  __attribute__((section(".text"))) = "\n";
                    stub_write(2, s_pre, sizeof(s_pre) - 1);
                    if (path) { u64 n=0; while (path[n] && n<256) ++n; stub_write(2, path, n); }
                    stub_write(2, s_mid, sizeof(s_mid) - 1);
                    { char h[16]; stub_hex16(h, fileSize); stub_write(2, h, 16); }
                    stub_write(2, s_nl, 1);
                }
            }
            break;
        case SYS_nr_fstat:
            b_append(&p, "fstat(", 6);
            b_dec(&p, a1); b_append(&p, ", ...)\n", 7);
            break;
        case SYS_nr_lseek:
            b_append(&p, "lseek(", 6);
            b_dec(&p, a1); b_append(&p, ", ", 2);
            b_dec(&p, a2); b_append(&p, ", ", 2);
            b_dec(&p, a3); b_append(&p, ")\n", 2);
            break;
        case SYS_nr_unlinkat:
            DEBUG_LOG(TC("unlinkat: %s — NOT IMPLEMENTED"), (const char*)a2);
            STUB_NOT_REACHED("unlinkat");
        default:
        {
            char h[16];
            b_append(&p, "syscall(", 8);
            stub_hex16(h, trap);
            for (int i = 0; i < 16; ++i) b_push(&p, h[i]);
            b_append(&p, ")\n", 2);
            break;
        }
    }
    (void)a5; (void)a6;

    // Primitive per-syscall trace — goes ONLY to stderr now that the shared
    // DEBUG_LOG_* macros emit pretty entries to the UBA_LOGFILE via
    // uba::WriteDebug. Duplicating raw [uba] lines into the logfile would
    // defeat the point of matching the LD_PRELOAD log format.
    size_t len = (size_t)(p - buf);
    stub_write(2, buf, len);
    // Signal mask is restored by uba_syscall_bridge after we return
    // (after the stack is switched back to Go's goroutine stack).
    return handled;
}

// Install a 14-byte JMP hook at g_syscall6Addr. On success stores the
// trampoline address in g_syscall6Trampoline; on failure emits a marker
// and returns without installing.
// SharedEvent::Set / IsSet. Normally provided by UbaEvent.cpp which we don't
// link (it drags in pthread). Our session creates EventFutex (tag 3) for
// static-detoured children — the only tag we'll see in the shm slots — so
// we forward directly to the stub's raw-futex wake/wait helpers.
namespace uba {
void SharedEvent::Set()
{
    event_wake_auto((u8*)m_data);
}
bool SharedEvent::IsSet(u32 timeOutMs)
{
    return event_wait_auto((u8*)m_data, timeOutMs) != 0;
}

// BinaryWriter(ProcessCommunication_Write) ctor + Flush. Mirrors the
// LD_PRELOAD definitions in UbaDetoursMainPosix.cpp but uses the stub's own
// globals — matches wire behavior exactly (UBA_PROTOCOL_GUARD=0 on Linux).
BinaryWriter::BinaryWriter(ProcessCommunication)
{
    constexpr u32 writable = CommunicationMemSize - sizeof(u64) * 13 * 3;
    m_begin = g_messageMappingMem;
    m_pos   = m_begin;
    m_end   = m_begin + writable;
}
BinaryReader BinaryWriter::Flush(bool waitOnResponse)
{
    constexpr u32 writable = CommunicationMemSize - sizeof(u64) * 13 * 3;
    g_writeEvent->Set();
    if (!waitOnResponse)
        return BinaryReader(nullptr, 0, 0);

    // Wait for response. Poll cancel + session-liveness at 1 Hz. Matches the
    // LD_PRELOAD Flush loop in UbaDetoursMainPosix.cpp:230.
    while (true)
    {
        if (g_readEvent->IsSet(1000))
            break;
        if (g_sessionPid)
        {
            // kill(pid, 0) — probe session liveness without actually sending
            // a signal. -ESRCH (=-3) means the process is gone.
            s64 r = raw_syscall3(62 /* SYS_kill */, (s64)g_sessionPid, 0, 0);
            if (r == -3)
            {
                g_isCancelled = true;
                raw_syscall1(231, 1337);
            }
        }
        if (g_cancelEvent && g_cancelEvent->IsSet(0))
        {
            g_isCancelled = true;
            raw_syscall1(231, 1339);
        }
    }

    BinaryReader reader(g_messageMappingMem, 0, writable);
    m_begin = nullptr;
    m_pos   = 0;
    m_end   = nullptr;
    return reader;
}
} // namespace uba

static void install_syscall6_hook(void)
{
    u64 sc6 = g_syscall6Addr;

    // Allocate a trampoline page (RWX). Contains the 14 displaced bytes
    // plus a 14-byte JMP back to the original site at sc6+14. Enough
    // headroom for a future multi-slot trampoline.
    s64 mmapRet = raw_syscall6(SYS_mmap,
        0, PAGE_SIZE, PROT_READ | PROT_WRITE | PROT_EXEC,
        MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if ((void*)mmapRet == MAP_FAILED)
    {
        stub_write(2, s_msgTrampFail, sizeof(s_msgTrampFail) - 1);
        return;
    }
    u8* tramp = (u8*)mmapRet;

    // Make the target's Syscall6 page writable. Page-align down.
    u64 page = sc6 & ~((u64)(PAGE_SIZE - 1));
    // The JMP may span two pages (14 bytes starting near a page boundary),
    // so grant RWX to two pages to be safe.
    s64 mp = raw_syscall3(SYS_mprotect, (s64)page, (s64)(PAGE_SIZE * 2),
                          PROT_READ | PROT_WRITE | PROT_EXEC);
    if (mp < 0)
    {
        stub_write(2, s_msgMprotFail, sizeof(s_msgMprotFail) - 1);
        return;
    }

    u8* sc6p = (u8*)sc6;

    // Copy displaced 14 bytes to trampoline[0..14]. Syscall.Syscall6's
    // prologue on Linux x86-64 is just register MOVs — no RIP-relative
    // operands — so the bytes can be safely relocated verbatim.
    for (int i = 0; i < 14; ++i) tramp[i] = sc6p[i];

    // trampoline[14..28]: JMP back to sc6+14 to resume the original
    // function at its post-prologue instruction.
    write_jmp14(tramp + 14, sc6 + 14);

    // Now overwrite Syscall6's prologue with a JMP to our bridge.
    write_jmp14(sc6p, (u64)(void*)uba_syscall_bridge);

    // Publish the trampoline address so the bridge can jump through it
    // after the log call.
    g_syscall6Trampoline = tramp;

    // Restore R|X on the target page. RWX is a red flag for anyone
    // inspecting the process later, and the bridge doesn't need write
    // access from this point onward.
    (void)raw_syscall3(SYS_mprotect, (s64)page, (s64)(PAGE_SIZE * 2),
                       PROT_READ | PROT_EXEC);

    stub_write(2, s_msgHooked, sizeof(s_msgHooked) - 1);
}

// Declared in UbaStaticStub.S.
extern "C" void uba_exit_bridge(void);

// Core of the exit bridge — receives the exit code, sends MessageType_Exit
// via shared-code RPC_MESSAGE, then issues SYS_exit_group itself. Never
// returns; annotated as noreturn so the asm bridge can tail into it.
extern "C" __attribute__((used, visibility("hidden"), noreturn))
void uba_exit_core(int exitCode)
{
    if (__atomic_load_n(&g_initDone, __ATOMIC_ACQUIRE))
        uba::SendExitRpc((u32)exitCode);

    // No stderr trace here — we may be called with minimal stub state
    // (compile/link skip send_init_rpc on some paths). Keep the exit path
    // tiny so nothing can fault between the hook firing and SYS_exit_group
    // terminating the process.

    // Infinite loop around the exit syscall so the compiler can't emit a
    // fall-through into the next function in the translation unit
    // (observed previously on Go `compile`: exit_group returned and we
    // fell into uba_detour_core's envp-parse loop, which SEGV'd on a
    // zeroed g_shmMem pointer).
    for (;;)
        raw_syscall1(231 /* SYS_exit_group */, (s64)exitCode);
}

// Overwrite runtime.exit.abi0's prologue with a 14-byte JMP to
// uba_exit_bridge. Unlike the syscall6 hook, we don't build a trampoline
// back to the original — the target function terminates the process, so
// resuming it after our RPC is unnecessary. We issue the exit ourselves.
static void install_exit_hook(void)
{
    u64 ex = g_runtimeExitAddr;
    if (ex == 0xDEADBEEFEEEEE500ULL) return; // sentinel not patched

    u64 page = ex & ~((u64)(PAGE_SIZE - 1));
    s64 mp = raw_syscall3(SYS_mprotect, (s64)page, (s64)(PAGE_SIZE * 2),
                          PROT_READ | PROT_WRITE | PROT_EXEC);
    if (mp < 0)
    {
        static const char m[] __attribute__((section(".text"))) = "[uba_stub] exit-hook mprotect failed\n";
        stub_write(2, m, sizeof(m) - 1);
        return;
    }

    write_jmp14((u8*)ex, (u64)(void*)uba_exit_bridge);

    (void)raw_syscall3(SYS_mprotect, (s64)page, (s64)(PAGE_SIZE * 2),
                       PROT_READ | PROT_EXEC);

    static const char m[] __attribute__((section(".text"))) = "[uba_stub] exit hook installed\n";
    stub_write(2, m, sizeof(m) - 1);
}

// Open a session-owned shm region by its FileMappingHandle uid (e.g. 2, 3, 6)
// and mmap `size` bytes of it read-only. Mirrors FileMapping_MapFromHost in
// UbaFileMapping.inl:598. Returns the mapped address on success, nullptr on
// failure (fd or mmap error).
static u8* open_table_shm(u64 uid, u64 size, const char* hint)
{
    char path[64];
    size_t pathLen = sizeof(s_shmPrefix) - 1;
    for (size_t i = 0; i < pathLen; ++i) path[i] = s_shmPrefix[i];
    pathLen += stub_hex_uba(path + pathLen, uid);
    path[pathLen] = 0;

    s64 fd = raw_syscall3(SYS_openat, (s64)AT_FDCWD, (s64)path, (s64)O_RDONLY);
    if (fd < 0)
    {
        char line[96]; char* p = line;
        const char pre[] = "[uba_stub] table open failed (";
        for (size_t i = 0; i < sizeof(pre) - 1; ++i) *p++ = pre[i];
        for (; *hint; ++hint) *p++ = *hint;
        const char mid[] = ") path=";
        for (size_t i = 0; i < sizeof(mid) - 1; ++i) *p++ = mid[i];
        for (size_t i = 0; i < pathLen; ++i) *p++ = path[i];
        *p++ = ' '; *p++ = 'e'; *p++ = '=';
        b_sdec(&p, (u64)fd);
        *p++ = '\n';
        stub_write(2, line, (size_t)(p - line));
        return 0;
    }

    s64 mmapRet = raw_syscall6(SYS_mmap,
        0, (s64)size, (s64)PROT_READ, (s64)MAP_SHARED, fd, 0);
    raw_syscall1(SYS_close, fd); // mmap keeps a vma reference; fd not needed.
    if ((void*)mmapRet == MAP_FAILED)
        return 0;
    return (u8*)mmapRet;
}

// Open the directory / mapped-file / overlay tables using handles supplied
// by the Init response. Sizes match UBA's hard-coded maxima from
// UbaProtocol.h (Linux over-commits virtual memory, so mapping 128 MB that
// is mostly unused is fine).
static void open_table_shms(void)
{
    constexpr u64 kDirTableMaxSize    = 128ull * 1024 * 1024;
    constexpr u64 kMappedTableMaxSize =  16ull * 1024 * 1024;
    constexpr u64 kOverlayTableMaxSize = 16ull * 1024 * 1024;

    g_directoryTableMem  = open_table_shm(g_directoryTableHandle,  kDirTableMaxSize,    "DirTable");
    g_mappedFileTableMem = open_table_shm(g_mappedFileTableHandle, kMappedTableMaxSize, "FileTable");
    g_overlayTableMem    = open_table_shm(g_overlayTableHandle,    kOverlayTableMaxSize,"OverlayTable");
    // "tables mapped" diagnostic elided: the `char line[160]` stack buffer
    // triggered a SIGSEGV on Go `compile` even though earlier probes printed
    // the same pointers via per-character writes. Kept removed until we
    // understand why this specific local allocation poisons that binary.
}

// Sends MessageType_Init to UBA via the session's shm-backed RPC.
// Frame layout (matches UBA's existing wire format):
//   [u32 0xdeadbeef guard][u8 MessageType_Init]
// Then wakes write event, waits briefly on read event.
//
// Even though we don't do anything with the response, sending this message
// lets the UBA session log it and tell us our comm plumbing works.
static void send_init_rpc(void)
{
    if (!g_shmMem) return;

    // SharedEvent offsets, matching what UbaDetoursMainPosix.cpp's
    // shm-attach code assigns:
    //   shm + 0   : cancel event
    //   shm + 104 : server-to-client signal (we wait here)
    //   shm + 208 : client-to-server signal (we wake here)
    u8* ev_cancel    = (u8*)g_shmMem + 0 * UBA_EVENT_SIZE;
    u8* ev_srv2cli   = (u8*)g_shmMem + 1 * UBA_EVENT_SIZE;
    u8* ev_cli2srv   = (u8*)g_shmMem + 2 * UBA_EVENT_SIZE;
    (void)ev_cancel;

    // Message region starts after the three SharedEvent slots.
    u8* msgRegion = (u8*)g_shmMem + 3 * UBA_EVENT_SIZE;

    // Use UBA's BinaryWriter — its inline methods are available now.
    // Note: the normal LD_PRELOAD detour writes a 0xdeadbeef guard
    // before the message type, but only when `UBA_PROTOCOL_GUARD` is
    // enabled (it's off by default). The server reads `messageType`
    // from offset 0, so we skip the guard.
    uba::BinaryWriter writer(msgRegion, 0, uba::CommunicationMemSize - 3 * UBA_EVENT_SIZE);
    writer.WriteByte(uba::MessageType_Init);

    // Hand off: wake the server's message thread.
    event_wake_auto(ev_cli2srv);
    stub_write(2, s_msgInitSent, sizeof(s_msgInitSent) - 1);

    // Wait up to 500 ms for the server's response. If UBA doesn't
    // understand our message (protocol mismatch) the read event never
    // fires, and we don't want to hang the target process.
    int r = event_wait_auto(ev_srv2cli, 500);
    if (!r)
    {
        stub_write(2, s_msgInitTimeout, sizeof(s_msgInitTimeout) - 1);
        return;
    }

    // Parse the full Init response. Mirror of HandleInit() in UbaProcess.cpp
    // — any mismatch here desynchronises the stream and every later RPC
    // lands on corrupt data. Fields we don't yet consume are still read so
    // the reader ends up at the end-of-message boundary (required for any
    // follow-up Init-style handshake, and pedagogically useful for logging).
    {
        uba::BinaryReader reader(msgRegion, 0, uba::CommunicationMemSize - 3 * UBA_EVENT_SIZE);
        g_processId   = reader.ReadU32();
        g_isChild     = reader.ReadByte();       // bool
        g_trackInputs = reader.ReadByte();       // bool
        g_initVirtualAppLen = reader.ReadString(g_initVirtualApp, sizeof(g_initVirtualApp));
        g_initVirtualWorkDirLen  = reader.ReadString(g_initVirtualWorkDir, sizeof(g_initVirtualWorkDir));
        g_sharedMemoryAllocator = reader.ReadU64();
        g_permanentFilesHandle  = reader.ReadU64();
        g_directoryTableHandle  = reader.ReadU64();
        u64 packedDirSize       = reader.ReadU64();
        g_directoryTableSizeMain    = (u32)(packedDirSize & 0xffffffffu);
        g_directoryTableSizeOverlay = (u32)(packedDirSize >> 32);
        g_directoryTableCount   = reader.ReadU32();
        g_mappedFileTableHandle = reader.ReadU64();
        g_mappedFileTableSize   = reader.ReadU32();
        g_mappedFileTableCount  = reader.ReadU32();
        g_overlayTableHandle    = reader.ReadU64();
        // Trailing u16 vfsSize + bytes. We read the length so a future Log
        // RPC writer starts at the correct offset; the blob itself is
        // skipped for now.
        u16 vfsSize = reader.ReadU16();
        (void)vfsSize;

        stub_write(2, s_msgInitResp, sizeof(s_msgInitResp) - 1);
        char buf[384]; char* p = buf;
        const char pi[] = "pid=";
        for (size_t i = 0; i < sizeof(pi) - 1; ++i) *p++ = pi[i];
        b_dec(&p, g_processId);
        const char ic[] = " isChild="; for (size_t i = 0; i < sizeof(ic) - 1; ++i) *p++ = ic[i];
        *p++ = (char)('0' + (g_isChild ? 1 : 0));
        const char ti[] = " track="; for (size_t i = 0; i < sizeof(ti) - 1; ++i) *p++ = ti[i];
        *p++ = (char)('0' + (g_trackInputs ? 1 : 0));
        const char dt[] = " dir(h=0x"; for (size_t i = 0; i < sizeof(dt) - 1; ++i) *p++ = dt[i];
        stub_hex16(p, g_directoryTableHandle); p += 16;
        const char dm[] = " m="; for (size_t i = 0; i < sizeof(dm) - 1; ++i) *p++ = dm[i];
        b_dec(&p, g_directoryTableSizeMain);
        const char dov[] = " ov="; for (size_t i = 0; i < sizeof(dov) - 1; ++i) *p++ = dov[i];
        b_dec(&p, g_directoryTableSizeOverlay);
        const char dc[] = " cnt="; for (size_t i = 0; i < sizeof(dc) - 1; ++i) *p++ = dc[i];
        b_dec(&p, g_directoryTableCount);
        const char mp[] = ") map(h=0x"; for (size_t i = 0; i < sizeof(mp) - 1; ++i) *p++ = mp[i];
        stub_hex16(p, g_mappedFileTableHandle); p += 16;
        const char ms[] = " s="; for (size_t i = 0; i < sizeof(ms) - 1; ++i) *p++ = ms[i];
        b_dec(&p, g_mappedFileTableSize);
        const char mc[] = " cnt="; for (size_t i = 0; i < sizeof(mc) - 1; ++i) *p++ = mc[i];
        b_dec(&p, g_mappedFileTableCount);
        const char ovh[] = ") ov(h=0x"; for (size_t i = 0; i < sizeof(ovh) - 1; ++i) *p++ = ovh[i];
        stub_hex16(p, g_overlayTableHandle); p += 16;
        *p++ = ')';
        *p++ = '\n';
        stub_write(2, buf, (size_t)(p - buf));
    }

    // Second RPC (MessageType_Log) disabled — diagnostic "Hello from
    // UbaStaticStub" message. Triggered a SEGV on Go `compile`/`link`
    // immediately after Init RPC completed. The real per-syscall communication
    // path (CreateFile / Close / etc. via Rpc_*) does not depend on this probe.

    __atomic_store_n(&g_initDone, 1, __ATOMIC_RELEASE);
}

// Split out of uba_detour_core to keep that function's stack frame small.
// Go's `compile` tool (and `link`) run with a tight initial stack region and
// crashed when this ran inline inside the parent frame.
static __attribute__((noinline, unused)) void log_event_tags(void)
{
    const u8* ev = (const u8*)g_shmMem;
    u8 tC = ev[0];
    u8 tW = ev[104];
    u8 tR = ev[208];
    char line[64];
    char* p = line;
    for (size_t i = 0; i < sizeof(s_msgEventTags) - 1; ++i)
        *p++ = s_msgEventTags[i];
    *p++ = (char)('0' + tC);
    *p++ = ' '; *p++ = 'w'; *p++ = '='; *p++ = (char)('0' + tW);
    *p++ = ' '; *p++ = 'r'; *p++ = '='; *p++ = (char)('0' + tR);
    *p++ = '\n';
    stub_write(2, line, (size_t)(p - line));
}

// --- main entry ------------------------------------------------------------
// extern "C" so the .S can call it by its plain symbol name.
extern "C" __attribute__((used, visibility("default")))
void uba_detour_core(char** envp)
{
    // Initialize the fd tracking table (all slots empty). Safe to do
    // here for the same reason as the alt-stack init below.
    fd_table_init();

    // Initialize the alt-stack. Safe to do here because uba_detour_core
    // runs strictly before the Syscall6 hook is installed below (in
    // InstallGoSyscall6Hook), which is the only producer of
    // uba_syscall_bridge invocations. We mmap a fresh anonymous region
    // rather than use a .bss array — 256 KB of zero-filled .bss would
    // bloat the blob by that much (our linker script packs .bss into
    // .text for the objcopy extraction), whereas an mmap costs nothing
    // blob-wise.
    {
        void* m = mmap(nullptr, (u64)kAltStackBytes, PROT_READ | PROT_WRITE,
                       MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
        if (m == MAP_FAILED)
        {
            static const char msg[] __attribute__((section(".text"))) =
                "[uba_stub] alt-stack mmap failed; aborting\n";
            stub_write(2, msg, sizeof(msg) - 1);
            raw_syscall1(231 /*exit_group*/, 1);
        }
        g_altStackTop = (u8*)m + kAltStackBytes;
    }

    // Single envp pass that locates UBA_COMID, UBA_LOGFILE, and UBA_CWD.
    const char* value = 0;
    const char* logPath = 0;
    const char* cwdPath = 0;
    for (char** p = envp; *p; ++p)
    {
        if (!value && stub_startswith(*p, s_envPrefix))
            value = *p + sizeof(s_envPrefix) - 1;
        else if (!logPath && stub_startswith(*p, s_envLogPrefix))
            logPath = *p + sizeof(s_envLogPrefix) - 1;
        else if (!cwdPath && stub_startswith(*p, s_envCwdPrefix))
            cwdPath = *p + sizeof(s_envCwdPrefix) - 1;
    }

    // Match the LD_PRELOAD detour (UbaDetoursMainPosix.cpp:170-173): chdir
    // into UBA_CWD so AT_FDCWD-relative paths (e.g. `@out/soong/...`) resolve
    // against the session's intended working directory, not whatever the
    // parent (UbaCli) happened to spawn us from. SYS_chdir = 80.
    if (cwdPath && *cwdPath)
        (void)raw_syscall1(80 /* SYS_chdir */, (s64)cwdPath);

    // Open UBA_LOGFILE. Truncate so each run starts with a clean log (matches
    // the LD_PRELOAD detour's PreInit behavior). The fd is stashed into both
    // g_logFd (stub's own primitive per-syscall log) AND uba::g_debugFile so
    // the shared-code DEBUG_LOG_DETOURED / DEBUG_LOG_TRUE / DEBUG_LOG_PIPE
    // macros write pretty entries to the same file.
    if (logPath && *logPath)
    {
        s64 fd = raw_syscall6(SYS_openat,
            (s64)AT_FDCWD, (s64)logPath,
            (s64)(O_WRONLY | O_CREAT | O_TRUNC),
            (s64)0644, 0, 0);
        if (fd >= 0)
        {
            g_logFd = (int)fd;
            uba::g_debugFile = (uba::FileHandle)fd;
        }
    }

    if (!value)
    {
        stub_write(2, s_msgNoEnv, sizeof(s_msgNoEnv) - 1);
        return;
    }

    // Parse "<uid>+<offset>".
    u64 uid = 0;
    u64 offset = 0;
    const char* cursor = value;
    if (!parse_u64_dec(&cursor, &uid) || *cursor != '+')
    {
        stub_write(2, s_msgBadVal, sizeof(s_msgBadVal) - 1);
        return;
    }
    ++cursor; // past '+'
    if (!parse_u64_dec(&cursor, &offset))
    {
        stub_write(2, s_msgBadVal, sizeof(s_msgBadVal) - 1);
        return;
    }

    // Build "/dev/shm/uba_<hex uid>"
    char path[64];
    size_t pathLen = sizeof(s_shmPrefix) - 1;
    for (size_t i = 0; i < pathLen; ++i) path[i] = s_shmPrefix[i];
    pathLen += stub_hex_uba(path + pathLen, uid);
    path[pathLen] = 0;

    // openat(AT_FDCWD, path, O_RDWR)
    s64 fd = raw_syscall3(SYS_openat, (s64)AT_FDCWD, (s64)path, (s64)O_RDWR);
    if (fd < 0)
    {
        stub_write(2, s_msgOpenFail, sizeof(s_msgOpenFail) - 1);
        return;
    }

    // mmap(NULL, size, PROT_RW, MAP_SHARED, fd, offset)
    s64 mmapRet = raw_syscall6(SYS_mmap,
        0, (s64)UBA_COMM_MEM_SIZE, (s64)(PROT_READ | PROT_WRITE),
        (s64)MAP_SHARED, fd, (s64)offset);
    if ((void*)mmapRet == MAP_FAILED)
    {
        raw_syscall1(SYS_close, fd);
        stub_write(2, s_msgMapFail, sizeof(s_msgMapFail) - 1);
        return;
    }

    g_shmFd  = (int)fd;
    g_shmMem = (void*)mmapRet;

    // Report success: "attached to /dev/shm/uba_<hex>"
    stub_write(2, s_msgAttached, sizeof(s_msgAttached) - 1);
    stub_write(2, path, pathLen);
    stub_write(2, s_nl, 1);

    // log_event_tags() disabled — triggered SEGV on Go `compile` and `link`
    // during stub init. The tag check was diagnostic only; the session creates
    // tag-3 (EventFutex) slots and our own SharedEvent::Set/IsSet dispatch
    // handles the rest regardless.
    //log_event_tags();

    // Report the Go syscall.Syscall6 address the patcher baked, then
    // install the hook.
    if (g_syscall6Addr == 0xDEADBEEFC0FFEE00ULL)
    {
        stub_write(2, s_msgNoSyscall, sizeof(s_msgNoSyscall) - 1);
    }
    else
    {
        char addr[16];
        stub_hex16(addr, g_syscall6Addr);
        stub_write(2, s_msgSyscall, sizeof(s_msgSyscall) - 1);
        stub_write(2, addr, 16);
        stub_write(2, s_nl, 1);
        install_syscall6_hook();
    }

    // Install the second hook: runtime.exit.abi0. Go's runtime issues the
    // final SYS_exit_group via this function's inline `syscall`, bypassing
    // Syscall6. Hooking it gives us a choke point to send MessageType_Exit.
    install_exit_hook();

    // BLAKE3 sanity probe: compute a StringKey over a fixed path and
    // hex-dump to stderr. A regression in how libBLAKE3.a is pulled into
    // the blob, or in the StringKey byte-order cast, will show up as a
    // mismatched hash here. Reference (blake3, 16-byte output):
    //   "/tmp/static-detour/hello.txt"
    //     bytes    = eb 96 44 ac aa a4 2e fb c9 87 df 96 6e e7 00 c0
    //     a (u64)  = 0xfb2ea4aaac4496eb
    //     b (u64)  = 0xc000e76e96df87c9
    // BLAKE3 sanity probe disabled — it SEGVs on Go `compile` / `link` inside
    // blake3_hasher_init, even though the same build works on merge_zips and
    // build_license_metadata (all are Go 1.23.4 static binaries). The probe is
    // diagnostic only; the real hashing path flows through Rpc_CreateFileW and
    // is exercised in practice. TODO: figure out why compile/link poison the
    // BLAKE3 call. Adding `[dbg] pre/post-blake` probes showed the crash is
    // specifically between the "before ToStringKeyNoCheck" and "after" markers.

    // Attempt the Init RPC. UBA's session message thread should wake,
    // log the message, and signal the read event. If the protocol is
    // correctly matched, we'll see "Init response received".
    send_init_rpc();

    // Mmap the three session-owned tables identified by the Init response
    // handles. Equivalent of FileMapping_MapFromHost(handle, Size, 0, false, ...)
    // in UbaFileMapping.inl:598. The path pattern `/dev/shm/uba_<hex>` is
    // produced by GetMappingHandleName — same 16-char hex layout we already
    // use for the comm region (stub_hex_uba).
    if (g_initDone)
    {
        open_table_shms();

        // Run the same shared-code init the LD_PRELOAD detour runs. Placement-
        // news MemoryBlock, DirectoryTable, MappedFileTable, g_stats,
        // g_communicationLock etc. into the VARIABLE_MEM storage defined in
        // UbaDetoursShared.cpp. Linux over-commits virtual memory so
        // MemoryBlock's 1 GiB reservation is fine even though only a few KiB
        // are written.
        //
        // Previously blocked on R_X86_64_RELATIVE relocations that the
        // objcopy'd blob couldn't apply (no dynamic linker). Resolved by
        // changing VARIABLE_MEM under UBA_STUB_BUILD=1 to emit only storage
        // (no `type& name = ...` reference slot) and redirecting `g_xxx`
        // references through non-inline `g_xxxStorage()` accessors —
        // everything lowers to RIP-relative lea, zero relocations needed.
        // See UbaDetoursShared.h for the details.
        uba::InitSharedVariables();

        // `g_directoryTable` etc. are macros in stub builds (see
        // UbaDetoursShared.h) that expand to
        //   (*static_cast<T*>(uba::g_XStorage()))
        // where g_XStorage() is a non-inline function returning &g_XMem. The
        // storage sits in the stub's .text blob; the compiler emits RIP-rel
        // leas for both the call and the cast, so no R_X86_64_RELATIVE is
        // needed.
        if (g_directoryTableMem)
            g_directoryTable.Init(g_directoryTableMem, g_directoryTableCount, g_directoryTableSizeMain);
        if (g_overlayTableMem && g_directoryTableSizeOverlay)
            g_directoryTable.InitOverlay(g_overlayTableMem, g_directoryTableSizeOverlay);

        if (g_mappedFileTableMem)
            g_mappedFileTable.Init(g_mappedFileTableMem, g_mappedFileTableCount, g_mappedFileTableSize);

        // Wire the LD_PRELOAD-shared globals to our shm layout. The event
        // slots and message region are identical to what UbaDetoursMainPosix.cpp's
        // OpenCom sets up; using the same names lets UbaDetoursFileMappingTable.cpp's
        // Rpc_* helpers reach them via ordinary extern.
        uba::g_messageMappingMem = (u8*)g_shmMem + 3 * UBA_EVENT_SIZE;
        uba::g_cancelEvent       = (uba::SharedEvent*)((u8*)g_shmMem + 0 * UBA_EVENT_SIZE);
        uba::g_readEvent         = (uba::SharedEvent*)((u8*)g_shmMem + 1 * UBA_EVENT_SIZE);
        uba::g_writeEvent        = (uba::SharedEvent*)((u8*)g_shmMem + 2 * UBA_EVENT_SIZE);
        uba::g_processId         = g_processId;
        // Session pid — pid of the process that created the shm. UbaCli sets
        // UBA_SESSION_PROCESS in the LD_PRELOAD path; we don't set it yet for
        // static detours, so Flush()'s liveness poll is skipped when zero.
        uba::g_sessionPid        = 0;

        // "DirectoryTable init" diagnostic elided for the same reason as
        // "tables mapped" above.
    }
}
