// Copyright Epic Games, Inc. All Rights Reserved.
// 
// This is an auto-generated file. See FlutterLiveLinkVCAM/pigeons/README for information on how to
// modify the original source and generate a new file.
// 
// Autogenerated from Pigeon (v14.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterGamepadError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterGamepadError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Inputs that can be reported in a [GamepadInputEvent]. */
enum class GamepadInput(val raw: Int) {
  DPADUP(0),
  DPADDOWN(1),
  DPADLEFT(2),
  DPADRIGHT(3),
  FACEBUTTONBOTTOM(4),
  FACEBUTTONRIGHT(5),
  FACEBUTTONLEFT(6),
  FACEBUTTONTOP(7),
  SHOULDERBUTTONLEFT(8),
  SHOULDERBUTTONRIGHT(9),
  TRIGGERBUTTONLEFT(10),
  TRIGGERBUTTONRIGHT(11),
  THUMBSTICKLEFTBUTTON(12),
  THUMBSTICKRIGHTBUTTON(13),
  SPECIALBUTTONLEFT(14),
  SPECIALBUTTONRIGHT(15),
  TRIGGERAXISLEFT(16),
  TRIGGERAXISRIGHT(17),
  THUMBSTICKLEFTX(18),
  THUMBSTICKLEFTY(19),
  THUMBSTICKRIGHTX(20),
  THUMBSTICKRIGHTY(21);

  companion object {
    fun ofRaw(raw: Int): GamepadInput? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Types of input that can be reported in a [GamepadInputEvent]. */
enum class GamepadInputType(val raw: Int) {
  BUTTON(0),
  AXIS(1);

  companion object {
    fun ofRaw(raw: Int): GamepadInputType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * An event sent when a gamepad receives input.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class GamepadInputEvent (
  /** The identifier of the gamepad that received the input. */
  val gamepadId: Long,
  /** The input received. */
  val input: GamepadInput,
  /** The type of input received. */
  val type: GamepadInputType,
  /**
   * The value of the input.
   * For buttons, this will be either 0 (unpressed) or 1 (pressed).
   * For axes, this ranges from 0 to 1.
   */
  val value: Double

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): GamepadInputEvent {
      val gamepadId = list[0].let { if (it is Int) it.toLong() else it as Long }
      val input = GamepadInput.ofRaw(list[1] as Int)!!
      val type = GamepadInputType.ofRaw(list[2] as Int)!!
      val value = list[3] as Double
      return GamepadInputEvent(gamepadId, input, type, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      gamepadId,
      input.raw,
      type.raw,
      value,
    )
  }
}
/**
 * API that receives messages about gamepad input in the host language.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface GamepadHostApi {
  /** Get the current list of connected gamepad IDs. */
  fun getActiveGamepadIds(): List<Long>

  companion object {
    /** The codec used by GamepadHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      StandardMessageCodec()
    }
    /** Sets up an instance of `GamepadHostApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: GamepadHostApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.live_link_vcam.GamepadHostApi.getActiveGamepadIds", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.getActiveGamepadIds())
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
@Suppress("UNCHECKED_CAST")
private object GamepadFlutterApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GamepadInputEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is GamepadInputEvent -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * API that receives messages about gamepad input in Flutter.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
@Suppress("UNCHECKED_CAST")
class GamepadFlutterApi(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by GamepadFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      GamepadFlutterApiCodec
    }
  }
  /** Called when a gamepad connects to the app. */
  fun onGamepadConnected(gamepadIdArg: Long, callback: (Result<Unit>) -> Unit) {
    val channelName = "dev.flutter.pigeon.live_link_vcam.GamepadFlutterApi.onGamepadConnected"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(gamepadIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Called when a gamepad disconnects from the app. */
  fun onGamepadDisconnected(gamepadIdArg: Long, callback: (Result<Unit>) -> Unit) {
    val channelName = "dev.flutter.pigeon.live_link_vcam.GamepadFlutterApi.onGamepadDisconnected"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(gamepadIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Called when a gamepad receives input. */
  fun onGamepadInputEvent(eventArg: GamepadInputEvent, callback: (Result<Unit>) -> Unit) {
    val channelName = "dev.flutter.pigeon.live_link_vcam.GamepadFlutterApi.onGamepadInputEvent"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
