[Staging]
; maintain PC GDK compatibility with other GDK-based platforms
; titles should put Achivements.json in $(ProjectDir)/Config/Xbl instead
+AllowedDirectories=$(ProjectName)/Platforms/GDK/Config/OSS
