// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "MetaHumanGeneratedAssetMetadata.h"

#include "Materials/MaterialParameters.h"
#include "Misc/TVariant.h"
#include "Misc/NotNull.h"
#include "Templates/Function.h"

#include "MetaHumanMaterialPipelineCommon.generated.h"

#define UE_API METAHUMANDEFAULTPIPELINE_API

// Material parameters that can be changed at runtime
//
// A subset of EMaterialParameterType
UENUM()
enum class EMetaHumanRuntimeMaterialParameterType
{
	Toggle,
	Scalar,
	Vector,
	DoubleVector,
	Texture,
	TextureCollection,
	Font,
	RuntimeVirtualTexture,
	SparseVolumeTexture
};

/**
 * Used to determine how to obtain material interface for the given parameter.
 */
UENUM()
enum class EMetaHumanRuntimeMaterialParameterSlotTarget
{
	/** Apply to the material slots whose names are listed in SlotNames. */
	SlotNames,
	/** Apply to the material slots whose indices are listed in SlotIndices. */
	SlotIndices,
	/** Apply to every material slot managed by the pipeline. Slot names and indices are ignored. */
	AllSlots,
};

/**
 * Used to describe material parameter that we can modify on the material
 * obtained from the slot name or index.
 */
USTRUCT()
struct FMetaHumanMaterialParameter
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, Category = "Material")
	FName InstanceParameterName;

	UPROPERTY(EditAnywhere, Category = "Material")
	EMetaHumanRuntimeMaterialParameterSlotTarget SlotTarget = EMetaHumanRuntimeMaterialParameterSlotTarget::SlotNames;

	UPROPERTY(EditAnywhere, Category = "Material", meta = (EditCondition = "SlotTarget == EMetaHumanRuntimeMaterialParameterSlotTarget::SlotNames"))
	TArray<FName> SlotNames;

	UPROPERTY(EditAnywhere, Category = "Material", meta = (EditCondition = "SlotTarget == EMetaHumanRuntimeMaterialParameterSlotTarget::SlotIndices"))
	TArray<int32> SlotIndices;

	UPROPERTY(EditAnywhere, Category = "Material")
	FMaterialParameterInfo MaterialParameter;

	UPROPERTY(EditAnywhere, Category = "Material")
	EMetaHumanRuntimeMaterialParameterType ParameterType = EMetaHumanRuntimeMaterialParameterType::Scalar;

	UPROPERTY(EditAnywhere, Category = "Material")
	TMap<FName, FString> PropertyMetadata;
};

class UMaterialInstanceConstant;
class UMaterialInstanceDynamic;
struct FInstancedPropertyBag;
struct FSkeletalMaterial;

namespace UE::MetaHuman::MaterialUtils
{
	/**
	 * On an asset that has material slots, such as a mesh, return the name of the material slot 
	 * that corresponds to the given slot index.
	 * 
	 * Should handle invalid slot indices gracefully and return NAME_None.
	 */
	using FFetchSlotNameDelegate = TDelegate<FName(int32)>;

	/** Similar to FFetchSlotNameDelegate, but returns the material assigned to the slot, if any. */
	using FFetchSlotMaterialDelegate = TDelegate<const UMaterialInterface*(int32)>;
	
	UE_API FFetchSlotNameDelegate MakeFetchSlotNameDelegate(TConstArrayView<FSkeletalMaterial> SkeletalMaterials);
	UE_API FFetchSlotMaterialDelegate MakeFetchSlotMaterialDelegate(TConstArrayView<FSkeletalMaterial> SkeletalMaterials);
	UE_API TMap<FName, TObjectPtr<UMaterialInstanceDynamic>> CastMaterialMapToDynamic(const TMap<FName, TObjectPtr<UMaterialInterface>>& MaterialMap);

#if WITH_EDITOR
	/** Generate Assembly Parameters for an item at build time */
	UE_API void GenerateAssemblyParameters(
		const TMap<FName, TObjectPtr<UMaterialInterface>>& OverrideMaterials,
		TConstArrayView<FMetaHumanMaterialParameter> RuntimeMaterialParameters,
		int32 NumMaterialSlots,
		const FFetchSlotNameDelegate& FetchSlotName,
		const FFetchSlotMaterialDelegate& FetchSlotMaterial,
		FInstancedPropertyBag& OutAssemblyParameters);
#endif

	/**
	 * Creates a UObject with a deterministic, unique name under InOuter.
	 *
	 * InOutGeneratedName is used as the initial name, and if the name is taken, it's 
	 * permuted until a unique name is found.
	 *
	 * InMakeObject should be a function that makes the actual object.
	 */
	UE_API UObject* CreateUniqueNamedObject(
		UObject* InOuter,
		FName& InOutGeneratedName,
		TFunctionRef<UObject*(FName)> InMakeObject);

	/**
	 * Creates a UMaterialInstanceDynamic with a deterministic, unique name.
	 *
	 * @see CreateUniqueNamedObject
	 */
	UE_API UMaterialInstanceDynamic* CreateUniqueNamedMaterialInstanceDynamic(
		TNotNull<const UMaterialInterface*> InParentMaterial,
		UObject* InOuter,
		FName& InOutGeneratedName);

	/**
	 * At assembly time, set any Assembly Parameters generated by GenerateAssemblyParameters
	 * and generate Post-Assembly Parameters, including generating dynamic Material Instances for
	 * the materials.
	 */
	UE_API void ProcessAssemblyParameters(
		const TMap<FName, TObjectPtr<UMaterialInterface>>& SourceOverrideMaterials,
		TConstArrayView<FMetaHumanMaterialParameter> RuntimeMaterialParameters,
		const FString& ItemFriendlyName,
		const FString& PreferredSubfolderPathForGeneratedAssets,
		int32 NumMaterialSlots,
		const FFetchSlotNameDelegate& FetchSlotName,
		const FFetchSlotMaterialDelegate& FetchSlotMaterial,
		UObject* OuterForGeneratedObjects,
		TMap<FName, TObjectPtr<UMaterialInterface>>& OutOverrideMaterials,
		FInstancedPropertyBag& OutPostAssemblyParameters,
		TArray<FMetaHumanGeneratedAssetMetadata>& OutMetadata);

	/**
	 * Updates materials from the given material parameters.
	 *
	 * @param InMaterialParameters Parameters that will be applied onto the material (doesn't contain the actual data)
	 * @param InMaterialInstanceMapping Materials to updated
	 * @param InFetchSlotName Returns the name of the material slot for a given slot index
	 * @param InPropertyBag Values for the material parameters.
	 */
	UE_API void SetInstanceParameters(
		const TArray<FMetaHumanMaterialParameter>& InMaterialParameters,
		const TMap<FName, TObjectPtr<class UMaterialInstanceDynamic>>& InMaterialInstanceMapping,
		const FFetchSlotNameDelegate& InFetchSlotName,
		const FInstancedPropertyBag& InPropertyBag);

	UE_DEPRECATED(5.8, "Use the SetInstanceParameters overload that takes a delegate instead of InAvailableSlots")
	void SetInstanceParameters(
		const TArray<FMetaHumanMaterialParameter>& InMaterialParameters,
		const TMap<FName, TObjectPtr<UMaterialInstanceDynamic>>& InMaterialInstanceMapping,
		const TArray<FName>& InAvailableSlots,
		const struct FInstancedPropertyBag& InPropertyBag);

	/**
	 * Outputs the property bag with parameters that are present on the given material.
	 *
	 * @param InMaterial Material to get values from
	 * @param InMaterialParameters Parameters to look for
	 * @param InOutPropertyBag Output result containing property name and the material parameter value
	 * @return true if any of the parameters were adeded or already in the bag.
	 */
	UE_API bool ParametersToPropertyBag(
		TNotNull<const UMaterialInterface*> InMaterial,
		const TArray<FMetaHumanMaterialParameter>& InMaterialParameters,
		FInstancedPropertyBag& InOutPropertyBag);

	/**
	 * Converts the given property name to the parameter type.
	 */
	UE_API EMetaHumanRuntimeMaterialParameterType PropertyToParameterType(TNotNull<FProperty*> InProperty);

#if WITH_EDITOR
	/**
	 * Reads metadata from the given property.
	 */
	UE_API TMap<FName, FString> CopyMetadataFromProperty(TNotNull<FProperty*> InProperty);
#endif
}

#undef UE_API

